export type ItemTier = 'apprentice' | 'journeyman' | 'adept' | 'masterwork';
export type ItemForm =
  | 'weapon-1h'
  | 'weapon-great'
  | 'weapon-polearm'
  | 'weapon-spear'
  | 'weapon-implement'
  | 'weapon-paired'
  | 'armour'
  | 'talisman'
  | 'talisman-icon'
  | 'talisman-reliquary'
  | 'talisman-paraphernalia'
  | 'standard';

export interface MaterialCost {
  gi?: number;    // Green Iron
  or?: number;    // Orichalcum
  tj?: number;    // Tempest Jade
  ws?: number;    // Weltsilver
  am?: number;    // Ambergelt
  bl?: number;    // Beggar's Lye
  db?: number;    // Dragonbone
  ig?: number;    // Iridescent Gloaming
  ilium?: number; // rings of ilium (artefacts / special items)
}

export interface CatalogueItem {
  id: string;
  name: string;
  tier: ItemTier;
  form: ItemForm;
  effect: string;
  materials: MaterialCost;
  totalMaterials: number;
  nations: 'all' | string[];
  skillRequired?: string;
  notes?: string;
}

export const MATERIAL_NAMES: Record<keyof MaterialCost, string> = {
  gi: 'Green Iron',
  or: 'Orichalcum',
  tj: 'Tempest Jade',
  ws: 'Weltsilver',
  am: 'Ambergelt',
  bl: "Beggar's Lye",
  db: 'Dragonbone',
  ig: 'Iridescent Gloaming',
  ilium: 'Ilium'
};

export const TIER_LABELS: Record<ItemTier, string> = {
  apprentice: 'Apprentice',
  journeyman: 'Journeyman',
  adept: 'Adept',
  masterwork: 'Masterwork'
};

// 249 items generated from Empire_Magic_Reference.xlsx
export const MAGIC_ITEMS_CATALOGUE: CatalogueItem[] = [
  // ============================================================
  // APPRENTICE TIER — 0 materials (38 items)
  // ============================================================
  {
    id: 'acolytes-mercy',
    name: 'Acolyte\'s Mercy',
    tier: 'apprentice',
    form: 'talisman',
    effect: 'Cast or swift cast heal as if you know it.',
    materials: {},
    totalMaterials: 0,
    nations: 'all',
  },
  {
    id: 'agramants-bargain',
    name: 'Agramant\'s Bargain',
    tier: 'apprentice',
    form: 'weapon-implement',
    effect: 'Cast weakness as if you know it.',
    materials: {},
    totalMaterials: 0,
    nations: 'all',
  },
  {
    id: 'apprentices-blade',
    name: 'Apprentice\'s Blade',
    tier: 'apprentice',
    form: 'weapon-1h',
    effect: 'Spend hero point to call CLEAVE with this one-handed weapon.',
    materials: {},
    totalMaterials: 0,
    nations: 'all',
  },
  {
    id: 'banner-of-the-bold',
    name: 'Banner of the Bold',
    tier: 'apprentice',
    form: 'standard',
    effect: 'Wield for +1 hero point; source of spiritual strength vs roleplaying effects.',
    materials: {},
    totalMaterials: 0,
    nations: 'all',
  },
  {
    id: 'butchers-cleaver',
    name: 'Butcher\'s Cleaver',
    tier: 'apprentice',
    form: 'weapon-great',
    effect: 'Spend hero point to call IMPALE with this great weapon.',
    materials: {},
    totalMaterials: 0,
    nations: 'all',
  },
  {
    id: 'circlet-of-falling-snow',
    name: 'Circlet of Falling Snow',
    tier: 'apprentice',
    form: 'talisman',
    effect: 'Spend 1 personal mana instead of hero point to overcome a roleplaying effect.',
    materials: {},
    totalMaterials: 0,
    nations: 'all',
    skillRequired: 'Magician',
  },
  {
    id: 'crystaltenders-vestment',
    name: 'Crystaltender\'s Vestment',
    tier: 'apprentice',
    form: 'armour',
    effect: 'Once/day consume 1 crystal mana to restore 3 personal mana.',
    materials: {},
    totalMaterials: 0,
    nations: 'all',
    skillRequired: 'Magician',
  },
  {
    id: 'dragonbone-symbol',
    name: 'Dragonbone Symbol',
    tier: 'apprentice',
    form: 'talisman',
    effect: 'Once/day: 10 min RP in matching consecrated area restores all hero points. Not in combat.',
    materials: {},
    totalMaterials: 0,
    nations: 'all',
    skillRequired: 'Dedication',
  },
  {
    id: 'farmers-scythe',
    name: 'Farmer\'s Scythe',
    tier: 'apprentice',
    form: 'weapon-polearm',
    effect: 'Spend hero point to call STRIKEDOWN with this pole-arm.',
    materials: {},
    totalMaterials: 0,
    nations: 'all',
    skillRequired: 'Weapon Master',
  },
  {
    id: 'forlorn-hope',
    name: 'Forlorn Hope',
    tier: 'apprentice',
    form: 'weapon-implement',
    effect: 'Cast or swift cast heal as if you know it.',
    materials: {},
    totalMaterials: 0,
    nations: 'all',
  },
  {
    id: 'heros-girdle',
    name: 'Hero\'s Girdle',
    tier: 'apprentice',
    form: 'talisman',
    effect: '+1 rank Endurance.',
    materials: {},
    totalMaterials: 0,
    nations: 'all',
  },
  {
    id: 'icon-of-the-judge',
    name: 'Icon of the Judge',
    tier: 'apprentice',
    form: 'talisman-icon',
    effect: 'Wield to perform excommunicate ceremony as if you know it.',
    materials: {},
    totalMaterials: 0,
    nations: 'all',
    skillRequired: 'Dedication',
  },
  {
    id: 'icon-of-the-justicar',
    name: 'Icon of the Justicar',
    tier: 'apprentice',
    form: 'talisman-icon',
    effect: 'Wield to perform exorcism ceremony as if you know it.',
    materials: {},
    totalMaterials: 0,
    nations: 'all',
    skillRequired: 'Dedication',
  },
  {
    id: 'icon-of-the-pilgrim',
    name: 'Icon of the Pilgrim',
    tier: 'apprentice',
    form: 'talisman-icon',
    effect: 'Wield to perform anointing ceremony as if you know it.',
    materials: {},
    totalMaterials: 0,
    nations: 'all',
    skillRequired: 'Dedication',
  },
  {
    id: 'icon-of-the-seer',
    name: 'Icon of the Seer',
    tier: 'apprentice',
    form: 'talisman-icon',
    effect: 'Wield to perform insight ceremony as if you know it.',
    materials: {},
    totalMaterials: 0,
    nations: 'all',
    skillRequired: 'Dedication',
  },
  {
    id: 'icon-of-the-smith',
    name: 'Icon of the Smith',
    tier: 'apprentice',
    form: 'talisman-icon',
    effect: 'Wield to perform hallow ceremony as if you know it.',
    materials: {},
    totalMaterials: 0,
    nations: 'all',
    skillRequired: 'Dedication',
  },
  {
    id: 'icon-of-the-steward',
    name: 'Icon of the Steward',
    tier: 'apprentice',
    form: 'talisman-icon',
    effect: 'Wield to perform consecrate ceremony as if you know it.',
    materials: {},
    totalMaterials: 0,
    nations: 'all',
    skillRequired: 'Dedication',
  },
  {
    id: 'icon-of-the-witness',
    name: 'Icon of the Witness',
    tier: 'apprentice',
    form: 'talisman-icon',
    effect: 'Wield to perform testimony ceremony as if you know it.',
    materials: {},
    totalMaterials: 0,
    nations: 'all',
    skillRequired: 'Dedication',
  },
  {
    id: 'lamias-whisper',
    name: 'Lamia\'s Whisper',
    tier: 'apprentice',
    form: 'weapon-implement',
    effect: 'Cast venom as if you know it.',
    materials: {},
    totalMaterials: 0,
    nations: 'all',
  },
  {
    id: 'landskeepers-oath',
    name: 'Landskeeper\'s Oath',
    tier: 'apprentice',
    form: 'weapon-implement',
    effect: 'Cast entangle as if you know it.',
    materials: {},
    totalMaterials: 0,
    nations: 'all',
  },
  {
    id: 'litany-of-the-labyrinth',
    name: 'Litany of the Labyrinth',
    tier: 'apprentice',
    form: 'talisman-reliquary',
    effect: 'Sect: members never become ghosts/heralds; roleplay dying stoically; appear calm when questioned while dead.',
    materials: {},
    totalMaterials: 0,
    nations: 'all',
  },
  {
    id: 'marauders-cote',
    name: 'Marauder\'s Cote',
    tier: 'apprentice',
    form: 'armour',
    effect: 'Spend hero point to call CLEAVE with any melee weapon (not pike).',
    materials: {},
    totalMaterials: 0,
    nations: 'all',
  },
  {
    id: 'mazzarine-spindle',
    name: 'Mazzarine Spindle',
    tier: 'apprentice',
    form: 'weapon-implement',
    effect: 'Cast or swift cast restore limb as if you know it.',
    materials: {},
    totalMaterials: 0,
    nations: 'all',
  },
  {
    id: 'mendicant-cassock',
    name: 'Mendicant Cassock',
    tier: 'apprentice',
    form: 'armour',
    effect: 'Once/day perform religious skill without spending liao.',
    materials: {},
    totalMaterials: 0,
    nations: 'all',
    skillRequired: 'Dedication',
  },
  {
    id: 'mountebanks-surprise',
    name: 'Mountebank\'s Surprise',
    tier: 'apprentice',
    form: 'talisman',
    effect: 'Once/day: after casting empower on a target, you also gain empower.',
    materials: {},
    totalMaterials: 0,
    nations: 'all',
  },
  {
    id: 'pilgrims-shield',
    name: 'Pilgrim\'s Shield',
    tier: 'apprentice',
    form: 'talisman',
    effect: '+1 rank Endurance while Dedicated or Anointed.',
    materials: {},
    totalMaterials: 0,
    nations: 'all',
    skillRequired: 'Dedication',
  },
  {
    id: 'pugilists-shillelagh',
    name: 'Pugilist\'s Shillelagh',
    tier: 'apprentice',
    form: 'weapon-1h',
    effect: 'Cast repel as if you know it.',
    materials: {},
    totalMaterials: 0,
    nations: 'all',
  },
  {
    id: 'razorleaf-hasta',
    name: 'Razorleaf Hasta',
    tier: 'apprentice',
    form: 'weapon-spear',
    effect: 'Spend hero point to call CLEAVE with this one-handed spear.',
    materials: {},
    totalMaterials: 0,
    nations: 'all',
    skillRequired: 'Weapon Master',
  },
  {
    id: 'runesmiths-gavel',
    name: 'Runesmith\'s Gavel',
    tier: 'apprentice',
    form: 'weapon-implement',
    effect: 'Cast or swift cast mend as if you know it.',
    materials: {},
    totalMaterials: 0,
    nations: 'all',
  },
  {
    id: 'snow-might-fall',
    name: 'Snow might fall',
    tier: 'apprentice',
    form: 'talisman-paraphernalia',
    effect: '★ Cast Timeless Hammer Rhythm on yourself once per summit.',
    materials: {},
    totalMaterials: 0,
    nations: ['Wintermark'],
    skillRequired: 'Artisan',
  },
  {
    id: 'storm-sceptre',
    name: 'Storm Sceptre',
    tier: 'apprentice',
    form: 'weapon-implement',
    effect: 'Cast repel as if you know it.',
    materials: {},
    totalMaterials: 0,
    nations: 'all',
  },
  {
    id: 'stoutheart-gambeson',
    name: 'Stoutheart Gambeson',
    tier: 'apprentice',
    form: 'armour',
    effect: '+1 rank Fortitude.',
    materials: {},
    totalMaterials: 0,
    nations: 'all',
  },
  {
    id: 'straw-mask',
    name: 'Straw Mask',
    tier: 'apprentice',
    form: 'talisman',
    effect: '+1 rank for Blessing of New Spring, Strong Ox Golden Sun, Gathering the Harvest, Fallow Fields rituals.',
    materials: {},
    totalMaterials: 0,
    nations: 'all',
  },
  {
    id: 'swanfeather-schema',
    name: 'Swanfeather Schema',
    tier: 'apprentice',
    form: 'weapon-implement',
    effect: 'Cast or swift cast purify as if you know it.',
    materials: {},
    totalMaterials: 0,
    nations: 'all',
  },
  {
    id: 'tacticians-demand',
    name: 'Tactician\'s Demand',
    tier: 'apprentice',
    form: 'weapon-implement',
    effect: 'Cast empower as if you know it.',
    materials: {},
    totalMaterials: 0,
    nations: 'all',
  },
  {
    id: 'unseen-encasement',
    name: 'Unseen Encasement',
    tier: 'apprentice',
    form: 'weapon-implement',
    effect: 'Cast paralysis as if you know it.',
    materials: {},
    totalMaterials: 0,
    nations: 'all',
  },
  {
    id: 'warriors-plate',
    name: 'Warrior\'s Plate',
    tier: 'apprentice',
    form: 'armour',
    effect: '+1 rank Endurance.',
    materials: {},
    totalMaterials: 0,
    nations: 'all',
  },
  {
    id: 'yeomans-bounty',
    name: 'Yeoman\'s Bounty',
    tier: 'apprentice',
    form: 'weapon-implement',
    effect: 'Cast weakness as if you know it.',
    materials: {},
    totalMaterials: 0,
    nations: 'all',
  },
  // ============================================================
  // JOURNEYMAN TIER — 1–10 materials (36 items)
  // ============================================================
  {
    id: 'guided-path',
    name: 'Guided Path',
    tier: 'journeyman',
    form: 'armour',
    effect: 'Perform religious skill on terminal character without spending liao.',
    materials: { db: 4 },
    totalMaterials: 4,
    nations: 'all',
    skillRequired: 'Dedication',
  },
  {
    id: 'whelpmasters-fang',
    name: 'Whelpmaster\'s Fang',
    tier: 'journeyman',
    form: 'weapon-1h',
    effect: 'Once/day cast weakness without spending mana.',
    materials: { bl: 4 },
    totalMaterials: 4,
    nations: 'all',
  },
  {
    id: 'windreaping-sickle',
    name: 'Windreaping Sickle',
    tier: 'journeyman',
    form: 'weapon-1h',
    effect: 'Once/day cast repel without spending mana.',
    materials: { tj: 4 },
    totalMaterials: 4,
    nations: 'all',
  },
  {
    id: 'sanguine-spear',
    name: 'Sanguine Spear',
    tier: 'journeyman',
    form: 'weapon-polearm',
    effect: 'Spend hero point to call CLEAVE with this pole-arm.',
    materials: { gi: 5 },
    totalMaterials: 5,
    nations: 'all',
    skillRequired: 'Weapon Master',
  },
  {
    id: 'biting-blade',
    name: 'Biting Blade',
    tier: 'journeyman',
    form: 'weapon-1h',
    effect: 'Once/day call CLEAVE with this one-handed weapon.',
    materials: { or: 7 },
    totalMaterials: 7,
    nations: 'all',
  },
  {
    id: 'bloodamber-hauberk',
    name: 'Bloodamber Hauberk',
    tier: 'journeyman',
    form: 'armour',
    effect: '+1 rank Endurance.',
    materials: { or: 3, am: 4 },
    totalMaterials: 7,
    nations: 'all',
  },
  {
    id: 'bondring',
    name: 'Bondring',
    tier: 'journeyman',
    form: 'talisman',
    effect: 'Bond to one willing person; once/day use stay with me or get it together on them free.',
    materials: { db: 7 },
    totalMaterials: 7,
    nations: 'all',
  },
  {
    id: 'enduring-breastplate',
    name: 'Enduring Breastplate',
    tier: 'journeyman',
    form: 'armour',
    effect: 'Ignore RP effects of one traumatic wound until end of battle.',
    materials: { or: 7 },
    totalMaterials: 7,
    nations: 'all',
  },
  {
    id: 'escharotic-cauldron',
    name: 'Escharotic Cauldron',
    tier: 'journeyman',
    form: 'talisman-paraphernalia',
    effect: 'Substitute 2× Marrowort for 1× Cerulean Mazzarine (or vice versa) once per potion preparation.',
    materials: { am: 7 },
    totalMaterials: 7,
    nations: 'all',
    skillRequired: 'Apothecary',
  },
  {
    id: 'reaving-mattock',
    name: 'Reaving Mattock',
    tier: 'journeyman',
    form: 'weapon-great',
    effect: 'Once/day call IMPALE with this great weapon.',
    materials: { tj: 7 },
    totalMaterials: 7,
    nations: 'all',
    skillRequired: 'Weapon Master',
  },
  {
    id: 'shears-of-winter',
    name: 'Shears of Winter',
    tier: 'journeyman',
    form: 'weapon-implement',
    effect: 'Arcane weapon pair: cast shatter as if you know it.',
    materials: { tj: 4, db: 3 },
    totalMaterials: 7,
    nations: 'all',
    skillRequired: 'Ambidexterity',
  },
  {
    id: 'witchwood-wand',
    name: 'Witchwood Wand',
    tier: 'journeyman',
    form: 'weapon-implement',
    effect: '+1 personal mana.',
    materials: { ig: 7 },
    totalMaterials: 7,
    nations: 'all',
    skillRequired: 'Magician',
  },
  {
    id: 'wyrmstone-mortar',
    name: 'Wyrmstone Mortar',
    tier: 'journeyman',
    form: 'talisman-paraphernalia',
    effect: 'Substitute 2× Bladeroot for 1× Imperial Roseweald (or vice versa) once per preparation.',
    materials: { bl: 7 },
    totalMaterials: 7,
    nations: 'all',
    skillRequired: 'Apothecary',
  },
  {
    id: 'bloodsilver-spike',
    name: 'Bloodsilver Spike',
    tier: 'journeyman',
    form: 'weapon-implement',
    effect: 'Once/day swift cast heal without spending mana.',
    materials: { ws: 8 },
    totalMaterials: 8,
    nations: 'all',
    skillRequired: 'Magician',
  },
  {
    id: 'quiet-word',
    name: 'Quiet Word',
    tier: 'journeyman',
    form: 'weapon-implement',
    effect: 'Once/day cast paralysis without spending mana.',
    materials: { am: 8 },
    totalMaterials: 8,
    nations: 'all',
  },
  {
    id: 'shadowbound-donjon',
    name: 'Shadowbound Donjon',
    tier: 'journeyman',
    form: 'talisman',
    effect: 'Once/day cast paralysis without mana (must know paralysis).',
    materials: { am: 5, ig: 3 },
    totalMaterials: 8,
    nations: 'all',
    skillRequired: 'Magician',
  },
  {
    id: 'soldiers-harness',
    name: 'Soldier\'s Harness',
    tier: 'journeyman',
    form: 'armour',
    effect: '+1 rank Endurance.',
    materials: { am: 8 },
    totalMaterials: 8,
    nations: 'all',
  },
  {
    id: 'volhovs-robe',
    name: 'Volhov\'s Robe',
    tier: 'journeyman',
    form: 'armour',
    effect: 'Twice/day join a same-nation coven ritual without being in the coven. Cannot be in a coven while bonded.',
    materials: { db: 5, ig: 3 },
    totalMaterials: 8,
    nations: ['Varushka'],
    skillRequired: 'Magician',
  },
  {
    id: 'wardens-fists',
    name: 'Warden\'s Fists',
    tier: 'journeyman',
    form: 'weapon-implement',
    effect: 'Once/day: call CLEAVE with weapon OR cast repel without mana.',
    materials: { gi: 2, or: 2, tj: 2, db: 2 },
    totalMaterials: 8,
    nations: 'all',
    skillRequired: 'Ambidexterity',
  },
  {
    id: 'altruists-recompense',
    name: 'Altruist\'s Recompense',
    tier: 'journeyman',
    form: 'talisman',
    effect: 'Whenever you cast/swift cast heal, you regain 1 hit.',
    materials: { ws: 5, ig: 4 },
    totalMaterials: 9,
    nations: 'all',
  },
  {
    id: 'amberglass-chain',
    name: 'Amberglass Chain',
    tier: 'journeyman',
    form: 'talisman',
    effect: 'Twice/day cast entangle without mana.',
    materials: { am: 9 },
    totalMaterials: 9,
    nations: 'all',
  },
  {
    id: 'boarskin-vest',
    name: 'Boarskin Vest',
    tier: 'journeyman',
    form: 'armour',
    effect: '+2 ranks Fortitude.',
    materials: { ws: 6, am: 3 },
    totalMaterials: 9,
    nations: 'all',
  },
  {
    id: 'deaths-door',
    name: 'Death\'s Door',
    tier: 'journeyman',
    form: 'weapon-implement',
    effect: 'Twice/day cast venom without mana.',
    materials: { bl: 6, ig: 3 },
    totalMaterials: 9,
    nations: 'all',
  },
  {
    id: 'enfeebling-echo',
    name: 'Enfeebling Echo',
    tier: 'journeyman',
    form: 'weapon-implement',
    effect: 'Twice/day cast weakness without mana.',
    materials: { bl: 9 },
    totalMaterials: 9,
    nations: 'all',
  },
  {
    id: 'redsteel-chisel',
    name: 'Redsteel Chisel',
    tier: 'journeyman',
    form: 'talisman-paraphernalia',
    effect: 'Twice/day cast mend without mana.',
    materials: { or: 6, ig: 3 },
    totalMaterials: 9,
    nations: 'all',
    skillRequired: 'Artisan',
  },
  {
    id: 'shackle-of-the-unvirtuous',
    name: 'Shackle of the Unvirtuous',
    tier: 'journeyman',
    form: 'talisman',
    effect: 'Aura concealed from insight; cannot use liao/ceremonies; do not dream.',
    materials: { tj: 4, db: 5 },
    totalMaterials: 9,
    nations: 'all',
  },
  {
    id: 'shimmergold-coat',
    name: 'Shimmergold Coat',
    tier: 'journeyman',
    form: 'armour',
    effect: '+1 rank Endurance.',
    materials: { or: 3, ws: 3, ig: 3 },
    totalMaterials: 9,
    nations: 'all',
  },
  {
    id: 'splintering-gorget',
    name: 'Splintering Gorget',
    tier: 'journeyman',
    form: 'armour',
    effect: 'Twice/day cast weakness without mana (must know weakness).',
    materials: { tj: 3, bl: 3, ig: 3 },
    totalMaterials: 9,
    nations: 'all',
  },
  {
    id: 'stumbleroot-spear',
    name: 'Stumbleroot Spear',
    tier: 'journeyman',
    form: 'weapon-spear',
    effect: 'Spend hero point to call STRIKEDOWN with this one-handed spear.',
    materials: { gi: 6, am: 3 },
    totalMaterials: 9,
    nations: 'all',
    skillRequired: 'Weapon Master',
  },
  {
    id: 'tumultuous-gyre',
    name: 'Tumultuous Gyre',
    tier: 'journeyman',
    form: 'weapon-implement',
    effect: 'Twice/day cast repel without mana.',
    materials: { tj: 6, ig: 3 },
    totalMaterials: 9,
    nations: 'all',
  },
  {
    id: 'wyvernsting-spaulders',
    name: 'Wyvernsting Spaulders',
    tier: 'journeyman',
    form: 'armour',
    effect: 'Twice/day cast venom without mana (must know venom).',
    materials: { ws: 3, bl: 3, ig: 3 },
    totalMaterials: 9,
    nations: 'all',
  },
  {
    id: 'beneficent-sigil',
    name: 'Beneficent Sigil',
    tier: 'journeyman',
    form: 'talisman',
    effect: 'When using exorcism, may instead remove WEAKNESS from target.',
    materials: { bl: 5, db: 5 },
    totalMaterials: 10,
    nations: 'all',
    skillRequired: 'Dedication',
  },
  {
    id: 'phial-of-the-sun',
    name: 'Phial of the Sun',
    tier: 'journeyman',
    form: 'talisman-paraphernalia',
    effect: 'Once/day physick use: acts as 1 dose of any single herb.',
    materials: { ws: 3, am: 5, bl: 2 },
    totalMaterials: 10,
    nations: 'all',
    skillRequired: 'Physick',
  },
  {
    id: 'sungold-basin',
    name: 'Sungold Basin',
    tier: 'journeyman',
    form: 'talisman',
    effect: 'When using dedication on dying target, restore to 1 hit instead.',
    materials: { or: 5, db: 5 },
    totalMaterials: 10,
    nations: 'all',
    skillRequired: 'Dedication',
  },
  {
    id: 'wayfarers-pyx',
    name: 'Wayfarer\'s Pyx',
    tier: 'journeyman',
    form: 'talisman-reliquary',
    effect: 'Sect ceremony strength +1 when one participant wields this.',
    materials: { db: 10 },
    totalMaterials: 10,
    nations: 'all',
  },
  {
    id: 'wayfarers-robe',
    name: 'Wayfarer\'s Robe',
    tier: 'journeyman',
    form: 'armour',
    effect: 'Spend extra liao during ceremony to increase strength by 1.',
    materials: { bl: 3, db: 4, ig: 3 },
    totalMaterials: 10,
    nations: 'all',
    skillRequired: 'Dedication',
  },
  // ============================================================
  // ADEPT TIER — 11–20 materials (92 items)
  // ============================================================
  {
    id: 'butchers-bill',
    name: 'Butcher\'s Bill',
    tier: 'adept',
    form: 'weapon-polearm',
    effect: 'Once/day call STRIKEDOWN or CLEAVE with this pole-arm.',
    materials: { or: 8, ig: 3 },
    totalMaterials: 11,
    nations: 'all',
    skillRequired: 'Weapon Master',
  },
  {
    id: 'corsairs-bloody-mask',
    name: 'Corsair\'s Bloody Mask',
    tier: 'adept',
    form: 'talisman',
    effect: '+1 rank Blood and Salt and Merciless Wrath of the Reaver rituals.',
    materials: { tj: 5, db: 3, ig: 3 },
    totalMaterials: 11,
    nations: 'all',
    skillRequired: 'Magician',
  },
  {
    id: 'jack-of-irons',
    name: 'Jack of Irons',
    tier: 'adept',
    form: 'armour',
    effect: 'Once/day use relentless without hero points.',
    materials: { ws: 3, am: 5, ig: 3 },
    totalMaterials: 11,
    nations: 'all',
  },
  {
    id: 'mask-of-gold-and-lead',
    name: 'Mask of Gold and Lead',
    tier: 'adept',
    form: 'talisman',
    effect: '+1 rank Eight-Spoked Wheel, Retrograde Wheel, Distil the Serpent\'s Stone, Amalgamation rituals; +3 extra transmutations per wearer.',
    materials: { bl: 5, db: 3, ig: 3 },
    totalMaterials: 11,
    nations: 'all',
    skillRequired: 'Magician',
  },
  {
    id: 'mercantilists-mask',
    name: 'Mercantilist\'s Mask',
    tier: 'adept',
    form: 'talisman',
    effect: '+1 rank Streams of Silver, Rivers of Gold, Winds of Fortune rituals.',
    materials: { or: 5, db: 3, ig: 3 },
    totalMaterials: 11,
    nations: 'all',
    skillRequired: 'Magician',
  },
  {
    id: 'rakes-progress',
    name: 'Rake\'s Progress',
    tier: 'adept',
    form: 'weapon-1h',
    effect: 'Twice/day when you use CLEAVE, may deliver it to two targets within 10 seconds.',
    materials: { or: 8, db: 3 },
    totalMaterials: 11,
    nations: 'all',
  },
  {
    id: 'warmages-belt',
    name: 'Warmage\'s Belt',
    tier: 'adept',
    form: 'talisman',
    effect: 'Once/day use unstoppable without hero points.',
    materials: { ws: 7, am: 4 },
    totalMaterials: 11,
    nations: 'all',
  },
  {
    id: 'winters-breath',
    name: 'Winter\'s Breath',
    tier: 'adept',
    form: 'armour',
    effect: 'Once/day use unstoppable without hero points.',
    materials: { ws: 5, am: 6 },
    totalMaterials: 11,
    nations: 'all',
  },
  {
    id: 'alders-edge',
    name: 'Alder\'s Edge',
    tier: 'adept',
    form: 'weapon-1h',
    effect: 'Gain Weapon Master skill.',
    materials: { tj: 9, db: 3 },
    totalMaterials: 12,
    nations: 'all',
  },
  {
    id: 'cerulean-protector',
    name: 'Cerulean Protector',
    tier: 'adept',
    form: 'armour',
    effect: 'Spend hero point to use relentless as if you know it.',
    materials: { or: 3, ws: 3, am: 6 },
    totalMaterials: 12,
    nations: 'all',
  },
  {
    id: 'goldentide-mail',
    name: 'Goldentide Mail',
    tier: 'adept',
    form: 'armour',
    effect: 'After 5s RP, spend hero point to remove VENOM from yourself.',
    materials: { or: 7, bl: 5 },
    totalMaterials: 12,
    nations: 'all',
  },
  {
    id: 'greensteel-bracelets',
    name: 'Greensteel Bracelets',
    tier: 'adept',
    form: 'talisman',
    effect: 'Gain Shield skill.',
    materials: { gi: 9, or: 3 },
    totalMaterials: 12,
    nations: 'all',
  },
  {
    id: 'healers-harness',
    name: 'Healer\'s Harness',
    tier: 'adept',
    form: 'armour',
    effect: 'When you cast/swift cast heal or purify, regain 1 hit.',
    materials: { tj: 7, ig: 5 },
    totalMaterials: 12,
    nations: 'all',
    skillRequired: 'Magician',
  },
  {
    id: 'mart-ns-mark',
    name: 'Martán\'s Mark',
    tier: 'adept',
    form: 'talisman',
    effect: 'Once/day use relentless without hero points.',
    materials: { ws: 3, am: 9 },
    totalMaterials: 12,
    nations: 'all',
  },
  {
    id: 'oakheart-shield',
    name: 'Oakheart Shield',
    tier: 'adept',
    form: 'talisman',
    effect: '+1 rank Fortitude AND +1 rank Endurance.',
    materials: { ws: 5, am: 7 },
    totalMaterials: 12,
    nations: 'all',
  },
  {
    id: 'scorpions-sting',
    name: 'Scorpion\'s Sting',
    tier: 'adept',
    form: 'weapon-1h',
    effect: 'Once/day call VENOM with this dagger; you are also venomed.',
    materials: { am: 5, bl: 7 },
    totalMaterials: 12,
    nations: 'all',
  },
  {
    id: 'scriveners-guard',
    name: 'Scrivener\'s Guard',
    tier: 'adept',
    form: 'talisman',
    effect: 'Spend hero point to use unstoppable as if you know it.',
    materials: { ws: 7, am: 5 },
    totalMaterials: 12,
    nations: 'all',
  },
  {
    id: 'blackwillow-twist',
    name: 'Blackwillow Twist',
    tier: 'adept',
    form: 'weapon-spear',
    effect: 'Once/day call STRIKEDOWN with this one-handed spear.',
    materials: { gi: 8, am: 5 },
    totalMaterials: 13,
    nations: 'all',
    skillRequired: 'Weapon Master',
  },
  {
    id: 'lodestone-shears',
    name: 'Lodestone Shears',
    tier: 'adept',
    form: 'talisman-paraphernalia',
    effect: 'Twice/day cut any bond to items you can make, without casting create bond.',
    materials: { tj: 6, bl: 7 },
    totalMaterials: 13,
    nations: 'all',
    skillRequired: 'Artisan',
  },
  {
    id: 'ambergelt-baton',
    name: 'Ambergelt Baton',
    tier: 'adept',
    form: 'weapon-implement',
    effect: 'Once/day cast heal, purify and restore limb simultaneously on one target, no mana.',
    materials: { ws: 4, am: 7, ig: 3 },
    totalMaterials: 14,
    nations: 'all',
    skillRequired: 'Magician',
  },
  {
    id: 'amberglass-orb',
    name: 'Amberglass Orb',
    tier: 'adept',
    form: 'talisman-paraphernalia',
    effect: 'Coven: use ambergelt instead of crystal mana for Spring rituals (2 measures = 1 mana).',
    materials: { tj: 7, am: 4, db: 3 },
    totalMaterials: 14,
    nations: 'all',
  },
  {
    id: 'bolstering-bill',
    name: 'Bolstering Bill',
    tier: 'adept',
    form: 'weapon-polearm',
    effect: 'Once/day while wielding, use stay with me without hero point.',
    materials: { gi: 6, ws: 8 },
    totalMaterials: 14,
    nations: 'all',
    skillRequired: 'Weapon Master',
  },
  {
    id: 'burnished-orb',
    name: 'Burnished Orb',
    tier: 'adept',
    form: 'talisman-paraphernalia',
    effect: 'Coven: use orichalcum instead of crystal mana for Summer rituals (2 measures = 1 mana).',
    materials: { or: 4, tj: 7, db: 3 },
    totalMaterials: 14,
    nations: 'all',
  },
  {
    id: 'dawns-glory',
    name: 'Dawn\'s Glory',
    tier: 'adept',
    form: 'weapon-1h',
    effect: '+1 hero point.',
    materials: { gi: 11, ws: 3 },
    totalMaterials: 14,
    nations: ['Dawn'],
  },
  {
    id: 'dragonbone-orb',
    name: 'Dragonbone Orb',
    tier: 'adept',
    form: 'talisman-paraphernalia',
    effect: 'Coven: use dragonbone instead of crystal mana for any mastered ritual (2 measures = 1 mana).',
    materials: { tj: 9, db: 5 },
    totalMaterials: 14,
    nations: 'all',
  },
  {
    id: 'greensteel-orb',
    name: 'Greensteel Orb',
    tier: 'adept',
    form: 'talisman-paraphernalia',
    effect: 'Coven: use green iron instead of crystal mana for Autumn rituals (2 measures = 1 mana).',
    materials: { gi: 4, tj: 7, db: 3 },
    totalMaterials: 14,
    nations: 'all',
  },
  {
    id: 'ironbrand-thorn',
    name: 'Ironbrand Thorn',
    tier: 'adept',
    form: 'weapon-spear',
    effect: '+1 hero point.',
    materials: { gi: 10, tj: 4 },
    totalMaterials: 14,
    nations: 'all',
  },
  {
    id: 'neophytes-aid',
    name: 'Neophyte\'s Aid',
    tier: 'adept',
    form: 'talisman',
    effect: '+2 personal mana.',
    materials: { tj: 9, ig: 5 },
    totalMaterials: 14,
    nations: 'all',
    skillRequired: 'Magician',
  },
  {
    id: 'radiant-orb',
    name: 'Radiant Orb',
    tier: 'adept',
    form: 'talisman-paraphernalia',
    effect: 'Coven: use weltsilver instead of crystal mana for Day rituals (2 measures = 1 mana).',
    materials: { tj: 7, ws: 4, db: 3 },
    totalMaterials: 14,
    nations: 'all',
  },
  {
    id: 'runebound-ward',
    name: 'Runebound Ward',
    tier: 'adept',
    form: 'armour',
    effect: '+1 hero point.',
    materials: { gi: 10, db: 4 },
    totalMaterials: 14,
    nations: ['Wintermark'],
  },
  {
    id: 'runemark-shirt',
    name: 'Runemark Shirt',
    tier: 'adept',
    form: 'armour',
    effect: '+1 hero point.',
    materials: { gi: 9, ig: 5 },
    totalMaterials: 14,
    nations: ['Wintermark'],
  },
  {
    id: 'triumphant-blade',
    name: 'Triumphant Blade',
    tier: 'adept',
    form: 'weapon-1h',
    effect: '+1 hero point.',
    materials: { gi: 10, or: 4 },
    totalMaterials: 14,
    nations: 'all',
  },
  {
    id: 'twilight-orb',
    name: 'Twilight Orb',
    tier: 'adept',
    form: 'talisman-paraphernalia',
    effect: 'Coven: use iridescent gloaming instead of crystal mana for Night rituals (2 measures = 1 mana).',
    materials: { tj: 7, db: 3, ig: 4 },
    totalMaterials: 14,
    nations: 'all',
  },
  {
    id: 'vitriolic-orb',
    name: 'Vitriolic Orb',
    tier: 'adept',
    form: 'talisman-paraphernalia',
    effect: 'Coven: use beggar\'s lye instead of crystal mana for Winter rituals (2 measures = 1 mana).',
    materials: { tj: 7, bl: 4, db: 3 },
    totalMaterials: 14,
    nations: 'all',
  },
  {
    id: 'vowkeeper',
    name: 'Vowkeeper',
    tier: 'adept',
    form: 'weapon-1h',
    effect: '+1 hero point.',
    materials: { gi: 9, am: 5 },
    totalMaterials: 14,
    nations: 'all',
  },
  {
    id: 'wardens-bardiche',
    name: 'Warden\'s Bardiche',
    tier: 'adept',
    form: 'weapon-polearm',
    effect: '+1 hero point.',
    materials: { gi: 10, am: 4 },
    totalMaterials: 14,
    nations: 'all',
    skillRequired: 'Weapon Master',
  },
  {
    id: 'arms-of-the-warwitch',
    name: 'Arms of the Warwitch',
    tier: 'adept',
    form: 'armour',
    effect: 'Spend 1 hero point → gain 1 mana OR spend 3 mana → gain 1 hero point.',
    materials: { gi: 3, db: 9, ig: 3 },
    totalMaterials: 15,
    nations: 'all',
    skillRequired: 'Battle Mage',
  },
  {
    id: 'blacksmiths-wage',
    name: 'Blacksmith\'s Wage',
    tier: 'adept',
    form: 'weapon-polearm',
    effect: 'Repair this pole-arm by spending hero point + 5s RP.',
    materials: { or: 9, am: 6 },
    totalMaterials: 15,
    nations: 'all',
    skillRequired: 'Weapon Master',
  },
  {
    id: 'brother-blades',
    name: 'Brother Blades',
    tier: 'adept',
    form: 'weapon-paired',
    effect: 'Once/day repair one or both weapons with 10s RP.',
    materials: { or: 9, am: 3, ig: 3 },
    totalMaterials: 15,
    nations: 'all',
    skillRequired: 'Ambidexterity',
  },
  {
    id: 'furrowed-wake',
    name: 'Furrowed Wake',
    tier: 'adept',
    form: 'weapon-implement',
    effect: 'When you cast entangle, may call STRIKEDOWN instead.',
    materials: { tj: 5, am: 5, ig: 5 },
    totalMaterials: 15,
    nations: 'all',
  },
  {
    id: 'giants-maul',
    name: 'Giant\'s Maul',
    tier: 'adept',
    form: 'weapon-great',
    effect: 'Once/day call STRIKEDOWN with this great weapon.',
    materials: { gi: 7, tj: 8 },
    totalMaterials: 15,
    nations: 'all',
    skillRequired: 'Weapon Master',
  },
  {
    id: 'jade-hammers',
    name: 'Jade Hammers',
    tier: 'adept',
    form: 'weapon-implement',
    effect: 'Arcane weapons: spend 1 mana to call STRIKEDOWN.',
    materials: { tj: 5, db: 5, ig: 5 },
    totalMaterials: 15,
    nations: 'all',
    skillRequired: 'Ambidexterity',
  },
  {
    id: 'opaline-coat',
    name: 'Opaline Coat',
    tier: 'adept',
    form: 'armour',
    effect: '+2 personal mana.',
    materials: { bl: 3, db: 3, ig: 9 },
    totalMaterials: 15,
    nations: 'all',
    skillRequired: 'Magician',
  },
  {
    id: 'staff-of-power',
    name: 'Staff of Power',
    tier: 'adept',
    form: 'weapon-implement',
    effect: 'Once/day cast or swift cast any known spell for free.',
    materials: { tj: 5, ig: 10 },
    totalMaterials: 15,
    nations: 'all',
    skillRequired: 'Battle Mage',
  },
  {
    id: 'alabaster-cerement',
    name: 'Alabaster Cerement',
    tier: 'adept',
    form: 'armour',
    effect: '+3 ranks Fortitude.',
    materials: { am: 6, bl: 7, db: 3 },
    totalMaterials: 16,
    nations: 'all',
  },
  {
    id: 'bloodsteel-barb',
    name: 'Bloodsteel Barb',
    tier: 'adept',
    form: 'weapon-spear',
    effect: 'Twice/day call CLEAVE with this one-handed spear.',
    materials: { or: 10, am: 3, bl: 3 },
    totalMaterials: 16,
    nations: 'all',
    skillRequired: 'Weapon Master',
  },
  {
    id: 'blood-sweat-hauberk',
    name: 'Blood-sweat Hauberk',
    tier: 'adept',
    form: 'armour',
    effect: 'Twice/day: 5s RP self-inflicted cut to remove VENOM from yourself.',
    materials: { or: 5, bl: 11 },
    totalMaterials: 16,
    nations: 'all',
  },
  {
    id: 'captains-mask',
    name: 'Captain\'s Mask',
    tier: 'adept',
    form: 'talisman',
    effect: '+2 ranks Splendid Panoply of Knighthood and Strength of the Bull rituals.',
    materials: { or: 8, db: 3, ig: 5 },
    totalMaterials: 16,
    nations: 'all',
    skillRequired: 'Magician',
  },
  {
    id: 'cartographers-eye',
    name: 'Cartographer\'s Eye',
    tier: 'adept',
    form: 'talisman-paraphernalia',
    effect: 'Coven ritual targeting resources in one territory can include a second territory of same nation.',
    materials: { tj: 7, ws: 5, db: 4 },
    totalMaterials: 16,
    nations: 'all',
  },
  {
    id: 'chrysalis-pendant',
    name: 'Chrysalis Pendant',
    tier: 'adept',
    form: 'talisman',
    effect: 'Spend hero point + 5s RP to restore a CLEAVE/IMPALE ruined limb on target.',
    materials: { ws: 8, am: 5, bl: 3 },
    totalMaterials: 16,
    nations: 'all',
  },
  {
    id: 'duelists-scales',
    name: 'Duelist\'s Scales',
    tier: 'adept',
    form: 'weapon-1h',
    effect: 'Spend hero point to call WEAKNESS with this weapon; you are also WEAKENED.',
    materials: { or: 7, tj: 3, ws: 3, bl: 3 },
    totalMaterials: 16,
    nations: 'all',
  },
  {
    id: 'knightly-redoubt',
    name: 'Knightly Redoubt',
    tier: 'adept',
    form: 'armour',
    effect: '+2 ranks Endurance.',
    materials: { or: 11, ws: 5 },
    totalMaterials: 16,
    nations: 'all',
  },
  {
    id: 'landsknechts-zweihander',
    name: 'Landsknecht\'s Zweihander',
    tier: 'adept',
    form: 'weapon-great',
    effect: 'Twice/day call IMPALE with this great weapon.',
    materials: { or: 3, tj: 13 },
    totalMaterials: 16,
    nations: 'all',
    skillRequired: 'Weapon Master',
  },
  {
    id: 'mask-of-the-mountebank',
    name: 'Mask of the Mountebank',
    tier: 'adept',
    form: 'talisman',
    effect: '+2 ranks Twilight Masquerade ritual; substitute iridescent gloaming for crystal mana in that ritual.',
    materials: { bl: 3, db: 3, ig: 10 },
    totalMaterials: 16,
    nations: 'all',
    skillRequired: 'Magician',
  },
  {
    id: 'orators-chalice',
    name: 'Orator\'s Chalice',
    tier: 'adept',
    form: 'talisman-paraphernalia',
    effect: 'Coven ritual targeting single-band characters can include a second band of same nation.',
    materials: { gi: 4, tj: 7, db: 5 },
    totalMaterials: 16,
    nations: 'all',
  },
  {
    id: 'stormguard-bulwark',
    name: 'Stormguard Bulwark',
    tier: 'adept',
    form: 'talisman',
    effect: '+1 rank Endurance AND +1 personal mana.',
    materials: { or: 7, tj: 3, ig: 6 },
    totalMaterials: 16,
    nations: 'all',
  },
  {
    id: 'sunfire-pectoral',
    name: 'Sunfire Pectoral',
    tier: 'adept',
    form: 'armour',
    effect: '+1 personal mana AND +1 rank Endurance.',
    materials: { gi: 8, or: 4, ig: 4 },
    totalMaterials: 16,
    nations: 'all',
  },
  {
    id: 'troubadours-ring',
    name: 'Troubadour\'s Ring',
    tier: 'adept',
    form: 'talisman',
    effect: 'Spend hero point to use stay with me. Once/day use stay with me free.',
    materials: { gi: 5, am: 4, db: 7 },
    totalMaterials: 16,
    nations: 'all',
  },
  {
    id: 'vorpal-sword',
    name: 'Vorpal Sword',
    tier: 'adept',
    form: 'weapon-1h',
    effect: 'Twice/day call CLEAVE with this weapon.',
    materials: { gi: 3, or: 10, bl: 3 },
    totalMaterials: 16,
    nations: 'all',
  },
  {
    id: 'warcasters-oath',
    name: 'Warcaster\'s Oath',
    tier: 'adept',
    form: 'talisman',
    effect: 'Spend 2 mana to use unstoppable (not while in regular armour).',
    materials: { gi: 7, tj: 5, db: 4 },
    totalMaterials: 16,
    nations: 'all',
    skillRequired: 'Magician',
  },
  {
    id: 'wardensweave',
    name: 'Wardensweave',
    tier: 'adept',
    form: 'armour',
    effect: '+2 ranks Endurance.',
    materials: { or: 9, am: 7 },
    totalMaterials: 16,
    nations: 'all',
  },
  {
    id: 'witches-hammer',
    name: 'Witches\' Hammer',
    tier: 'adept',
    form: 'weapon-great',
    effect: 'Twice/day cast shatter without mana.',
    materials: { tj: 7, bl: 3, ig: 6 },
    totalMaterials: 16,
    nations: 'all',
    skillRequired: 'Weapon Master',
  },
  {
    id: 'binding-threads',
    name: 'Binding Threads',
    tier: 'adept',
    form: 'weapon-implement',
    effect: 'Spend hero point to call ENTANGLE when you hit. Not while wearing armour.',
    materials: { gi: 3, am: 7, db: 7 },
    totalMaterials: 17,
    nations: 'all',
    skillRequired: 'Ambidexterity',
  },
  {
    id: 'boneweaver',
    name: 'Boneweaver',
    tier: 'adept',
    form: 'weapon-implement',
    effect: '3×/day cast restore limb without mana (must know restore limb).',
    materials: { ws: 5, am: 7, ig: 5 },
    totalMaterials: 17,
    nations: 'all',
    skillRequired: 'Magician',
  },
  {
    id: 'burnished-rampart',
    name: 'Burnished Rampart',
    tier: 'adept',
    form: 'talisman',
    effect: 'Spend hero point + 5s RP to repair this shield.',
    materials: { or: 14, ig: 3 },
    totalMaterials: 17,
    nations: 'all',
  },
  {
    id: 'champions-bastion',
    name: 'Champion\'s Bastion',
    tier: 'adept',
    form: 'talisman',
    effect: 'Whenever you spend a hero point, regain 1 hit immediately.',
    materials: { gi: 7, tj: 5, ws: 5 },
    totalMaterials: 17,
    nations: 'all',
  },
  {
    id: 'children-of-thunder',
    name: 'Children of Thunder',
    tier: 'adept',
    form: 'weapon-implement',
    effect: 'Spend hero point to call REPEL when you hit. Not while wearing armour.',
    materials: { gi: 3, tj: 7, db: 7 },
    totalMaterials: 17,
    nations: 'all',
    skillRequired: 'Ambidexterity',
  },
  {
    id: 'earthquake-drummers',
    name: 'Earthquake Drummers',
    tier: 'adept',
    form: 'weapon-paired',
    effect: 'Spend hero point to call REPEL when hitting with both weapons simultaneously.',
    materials: { tj: 10, db: 7 },
    totalMaterials: 17,
    nations: 'all',
    skillRequired: 'Ambidexterity',
  },
  {
    id: 'oathsworn-spine',
    name: 'Oathsworn Spine',
    tier: 'adept',
    form: 'weapon-spear',
    effect: 'Once/day call ENTANGLE with this one-handed spear.',
    materials: { am: 10, ig: 7 },
    totalMaterials: 17,
    nations: 'all',
    skillRequired: 'Weapon Master',
  },
  {
    id: 'blessing-wheel',
    name: 'Blessing Wheel',
    tier: 'adept',
    form: 'talisman',
    effect: 'During hallow, spend up to 3 extra liao to increase strength by same amount.',
    materials: { ws: 3, bl: 5, db: 7, ig: 3 },
    totalMaterials: 18,
    nations: 'all',
    skillRequired: 'Dedication',
  },
  {
    id: 'blood-dimming-tide',
    name: 'Blood-dimming Tide',
    tier: 'adept',
    form: 'weapon-implement',
    effect: 'Twice/day swift cast heal without mana.',
    materials: { ws: 7, am: 4, ig: 7 },
    totalMaterials: 18,
    nations: 'all',
    skillRequired: 'Magician',
  },
  {
    id: 'bloodfeather-harness',
    name: 'Bloodfeather Harness',
    tier: 'adept',
    form: 'armour',
    effect: '+3 ranks Fortitude.',
    materials: { ws: 10, am: 5, bl: 3 },
    totalMaterials: 18,
    nations: 'all',
  },
  {
    id: 'bloodwoven-braid',
    name: 'Bloodwoven Braid',
    tier: 'adept',
    form: 'talisman',
    effect: '3×/day cast heal without mana.',
    materials: { ws: 7, am: 5, bl: 3, ig: 3 },
    totalMaterials: 18,
    nations: 'all',
  },
  {
    id: 'brazier-of-benediction',
    name: 'Brazier of Benediction',
    tier: 'adept',
    form: 'talisman',
    effect: 'During consecration, spend up to 3 extra liao to increase strength by same amount.',
    materials: { gi: 5, or: 3, am: 5, db: 5 },
    totalMaterials: 18,
    nations: 'all',
    skillRequired: 'Dedication',
  },
  {
    id: 'ethereal-manacle',
    name: 'Ethereal Manacle',
    tier: 'adept',
    form: 'weapon-implement',
    effect: '3×/day cast entangle without mana.',
    materials: { am: 11, db: 4, ig: 3 },
    totalMaterials: 18,
    nations: 'all',
  },
  {
    id: 'ivory-aketon',
    name: 'Ivory Aketon',
    tier: 'adept',
    form: 'armour',
    effect: '+3 ranks Fortitude.',
    materials: { ws: 5, am: 10, bl: 3 },
    totalMaterials: 18,
    nations: 'all',
  },
  {
    id: 'pilgrims-cup',
    name: 'Pilgrim\'s Cup',
    tier: 'adept',
    form: 'talisman',
    effect: 'During anointing, spend up to 3 extra liao to increase strength by same amount.',
    materials: { or: 6, bl: 5, db: 7 },
    totalMaterials: 18,
    nations: 'all',
    skillRequired: 'Dedication',
  },
  {
    id: 'roaring-chimera-rod',
    name: 'Roaring Chimera Rod',
    tier: 'adept',
    form: 'weapon-implement',
    effect: '3×/day cast empower without mana.',
    materials: { gi: 3, or: 3, tj: 3, ig: 9 },
    totalMaterials: 18,
    nations: 'all',
    skillRequired: 'Magician',
  },
  {
    id: 'stalwarts-sword',
    name: 'Stalwart\'s Sword',
    tier: 'adept',
    form: 'weapon-1h',
    effect: '★ +1 hero point. Source of spiritual strength vs. fear roleplaying effects.',
    materials: { gi: 10, or: 4, db: 4 },
    totalMaterials: 18,
    nations: ['Wintermark'],
  },
  {
    id: 'stormweaver',
    name: 'Stormweaver',
    tier: 'adept',
    form: 'weapon-implement',
    effect: '3×/day cast repel without mana.',
    materials: { tj: 8, bl: 3, ig: 7 },
    totalMaterials: 18,
    nations: 'all',
    skillRequired: 'Battle Mage',
  },
  {
    id: 'trollsweave-vest',
    name: 'Trollsweave Vest',
    tier: 'adept',
    form: 'armour',
    effect: 'Twice/day cast/swift cast heal without mana (must know heal).',
    materials: { ws: 8, am: 7, ig: 3 },
    totalMaterials: 18,
    nations: 'all',
  },
  {
    id: 'barbed-spear',
    name: 'Barbed Spear',
    tier: 'adept',
    form: 'weapon-polearm',
    effect: 'Spend hero point to call VENOM with this pole-arm.',
    materials: { gi: 3, or: 3, bl: 13 },
    totalMaterials: 19,
    nations: 'all',
    skillRequired: 'Weapon Master',
  },
  {
    id: 'magistrates-grasp',
    name: 'Magistrate\'s Grasp',
    tier: 'adept',
    form: 'weapon-polearm',
    effect: 'Spend hero point to call ENTANGLE when you hit with this pole-arm.',
    materials: { gi: 4, or: 5, am: 10 },
    totalMaterials: 19,
    nations: 'all',
    skillRequired: 'Weapon Master',
  },
  {
    id: 'the-barren-land',
    name: 'The Barren Land',
    tier: 'adept',
    form: 'talisman-paraphernalia',
    effect: 'Once/day coven may perform a Winter ritual that doesn\'t count toward daily limit.',
    materials: { gi: 3, tj: 5, bl: 5, db: 6 },
    totalMaterials: 19,
    nations: 'all',
  },
  {
    id: 'the-empty-horizon',
    name: 'The Empty Horizon',
    tier: 'adept',
    form: 'talisman-paraphernalia',
    effect: 'Once/day coven may perform a Day ritual that doesn\'t count toward daily limit.',
    materials: { tj: 5, ws: 5, bl: 3, db: 6 },
    totalMaterials: 19,
    nations: 'all',
  },
  {
    id: 'the-fields-of-glory',
    name: 'The Fields of Glory',
    tier: 'adept',
    form: 'talisman-paraphernalia',
    effect: 'Once/day coven may perform a Summer ritual that doesn\'t count toward daily limit.',
    materials: { gi: 3, or: 5, tj: 5, db: 6 },
    totalMaterials: 19,
    nations: 'all',
  },
  {
    id: 'the-flickering-flame',
    name: 'The Flickering Flame',
    tier: 'adept',
    form: 'talisman-paraphernalia',
    effect: 'Once/day coven may perform a Night ritual that doesn\'t count toward daily limit.',
    materials: { tj: 5, am: 3, db: 6, ig: 5 },
    totalMaterials: 19,
    nations: 'all',
  },
  {
    id: 'the-green-world',
    name: 'The Green World',
    tier: 'adept',
    form: 'talisman-paraphernalia',
    effect: 'Once/day coven may perform a Spring ritual that doesn\'t count toward daily limit.',
    materials: { tj: 5, ws: 3, am: 5, db: 6 },
    totalMaterials: 19,
    nations: 'all',
  },
  {
    id: 'the-iron-labyrinth',
    name: 'The Iron Labyrinth',
    tier: 'adept',
    form: 'talisman-paraphernalia',
    effect: 'Once/day coven may perform an Autumn ritual that doesn\'t count toward daily limit.',
    materials: { gi: 5, tj: 5, ws: 3, db: 6 },
    totalMaterials: 19,
    nations: 'all',
  },
  {
    id: 'seers-probe',
    name: 'Seer\'s Probe',
    tier: 'adept',
    form: 'weapon-implement',
    effect: '3×/day cast detect magic or voice for the dead without mana.',
    materials: { tj: 5, ws: 9, db: 3, ig: 3 },
    totalMaterials: 20,
    nations: 'all',
    skillRequired: 'Magician',
  },
  {
    id: 'sydanjaas-call',
    name: 'Sydanjaa\'s Call',
    tier: 'adept',
    form: 'weapon-spear',
    effect: 'Spend hero point to call REPEL with this one-handed spear.',
    materials: { tj: 10, am: 10 },
    totalMaterials: 20,
    nations: 'all',
    skillRequired: 'Weapon Master',
  },
  {
    id: 'threshers-cudgel',
    name: 'Thresher\'s Cudgel',
    tier: 'adept',
    form: 'weapon-1h',
    effect: 'Spend hero point to call SHATTER on a mage implement when striking it.',
    materials: { gi: 5, tj: 9, am: 3, bl: 3 },
    totalMaterials: 20,
    nations: 'all',
  },
  // ============================================================
  // MASTERWORK TIER — 21+ materials (83 items)
  // ============================================================
  {
    id: 'bishops-chalice',
    name: 'Bishop\'s Chalice',
    tier: 'masterwork',
    form: 'talisman-reliquary',
    effect: 'Once/day: sect members in consecrated area regain all hero points after 10 min RP. Not in combat.',
    materials: { gi: 5, or: 7, db: 9 },
    totalMaterials: 21,
    nations: 'all',
  },
  {
    id: 'celebrants-fiddle',
    name: 'Celebrant\'s Fiddle',
    tier: 'masterwork',
    form: 'talisman',
    effect: '★ Dedicated to Prosperity only. Once/day in Prosperity area: 10 min play restores all listeners\' hero points.',
    materials: { tj: 7, db: 9, ig: 5 },
    totalMaterials: 21,
    nations: 'all',
    skillRequired: 'Dedication',
  },
  {
    id: 'goldwood-pipes',
    name: 'Goldwood Pipes',
    tier: 'masterwork',
    form: 'talisman',
    effect: '★ Dedicated to Wisdom only. Once/day in Wisdom area: 10 min play restores all listeners\' hero points.',
    materials: { am: 7, bl: 9, db: 5 },
    totalMaterials: 21,
    nations: 'all',
    skillRequired: 'Dedication',
  },
  {
    id: 'heroes-horn',
    name: 'Heroes\' Horn',
    tier: 'masterwork',
    form: 'talisman',
    effect: '★ Dedicated to Courage only. Once/day in Courage area: 10 min play restores all listeners\' hero points.',
    materials: { gi: 9, or: 7, db: 5 },
    totalMaterials: 21,
    nations: 'all',
    skillRequired: 'Dedication',
  },
  {
    id: 'horn-resounding',
    name: 'Horn Resounding',
    tier: 'masterwork',
    form: 'talisman',
    effect: '★ Dedicated to Pride only. Once/day in Pride area: 10 min play restores all listeners\' hero points.',
    materials: { or: 7, tj: 9, db: 5 },
    totalMaterials: 21,
    nations: 'all',
    skillRequired: 'Dedication',
  },
  {
    id: 'icon-of-the-devoted',
    name: 'Icon of the Devoted',
    tier: 'masterwork',
    form: 'talisman-icon',
    effect: 'Perform ceremonial skills as if dedicated to Loyalty.',
    materials: { gi: 7, db: 9, ig: 5 },
    totalMaterials: 21,
    nations: 'all',
    skillRequired: 'Dedication',
  },
  {
    id: 'icon-of-the-driven',
    name: 'Icon of the Driven',
    tier: 'masterwork',
    form: 'talisman-icon',
    effect: 'Perform ceremonial skills as if dedicated to Ambition.',
    materials: { or: 5, db: 9, ig: 7 },
    totalMaterials: 21,
    nations: 'all',
    skillRequired: 'Dedication',
  },
  {
    id: 'icon-of-the-industrious',
    name: 'Icon of the Industrious',
    tier: 'masterwork',
    form: 'talisman-icon',
    effect: 'Perform ceremonial skills as if dedicated to Prosperity.',
    materials: { am: 7, db: 9, ig: 5 },
    totalMaterials: 21,
    nations: 'all',
    skillRequired: 'Dedication',
  },
  {
    id: 'icon-of-the-insightful',
    name: 'Icon of the Insightful',
    tier: 'masterwork',
    form: 'talisman-icon',
    effect: 'Perform ceremonial skills as if dedicated to Wisdom.',
    materials: { bl: 7, db: 9, ig: 5 },
    totalMaterials: 21,
    nations: 'all',
    skillRequired: 'Dedication',
  },
  {
    id: 'icon-of-the-proud',
    name: 'Icon of the Proud',
    tier: 'masterwork',
    form: 'talisman-icon',
    effect: 'Perform ceremonial skills as if dedicated to Pride.',
    materials: { or: 7, db: 9, ig: 5 },
    totalMaterials: 21,
    nations: 'all',
    skillRequired: 'Dedication',
  },
  {
    id: 'icon-of-the-righteous',
    name: 'Icon of the Righteous',
    tier: 'masterwork',
    form: 'talisman-icon',
    effect: 'Perform ceremonial skills as if dedicated to Courage.',
    materials: { tj: 7, db: 9, ig: 5 },
    totalMaterials: 21,
    nations: 'all',
    skillRequired: 'Dedication',
  },
  {
    id: 'icon-of-the-watchful',
    name: 'Icon of the Watchful',
    tier: 'masterwork',
    form: 'talisman-icon',
    effect: 'Perform ceremonial skills as if dedicated to Vigilance.',
    materials: { ws: 7, db: 9, ig: 5 },
    totalMaterials: 21,
    nations: 'all',
    skillRequired: 'Dedication',
  },
  {
    id: 'silver-gate',
    name: 'Silver Gate',
    tier: 'masterwork',
    form: 'talisman',
    effect: '★ Dedicated to Ambition only. Once/day in Ambition area: 10 min play restores all listeners\' hero points.',
    materials: { or: 7, ws: 9, db: 5 },
    totalMaterials: 21,
    nations: 'all',
    skillRequired: 'Dedication',
  },
  {
    id: 'splintering-hammer',
    name: 'Splintering Hammer',
    tier: 'masterwork',
    form: 'weapon-great',
    effect: 'Once/day call SHATTER with this great weapon.',
    materials: { gi: 3, or: 5, tj: 10, am: 3 },
    totalMaterials: 21,
    nations: 'all',
    skillRequired: 'Weapon Master',
  },
  {
    id: 'thundering-drum',
    name: 'Thundering Drum',
    tier: 'masterwork',
    form: 'talisman',
    effect: '★ Dedicated to Loyalty only. Once/day in Loyalty area: 10 min play restores all listeners\' hero points.',
    materials: { gi: 9, tj: 7, db: 5 },
    totalMaterials: 21,
    nations: 'all',
    skillRequired: 'Dedication',
  },
  {
    id: 'thundering-mace',
    name: 'Thundering Mace',
    tier: 'masterwork',
    form: 'weapon-1h',
    effect: 'Once/day call STRIKEDOWN with this one-handed weapon.',
    materials: { gi: 8, or: 5, tj: 8 },
    totalMaterials: 21,
    nations: 'all',
  },
  {
    id: 'watchers-flute',
    name: 'Watchers\' Flute',
    tier: 'masterwork',
    form: 'talisman',
    effect: '★ Dedicated to Vigilance only. Once/day in Vigilance area: 10 min play restores all listeners\' hero points.',
    materials: { ws: 7, bl: 9, db: 5 },
    totalMaterials: 21,
    nations: 'all',
    skillRequired: 'Dedication',
  },
  {
    id: 'paupers-key',
    name: 'Pauper\'s Key',
    tier: 'masterwork',
    form: 'talisman',
    effect: 'Twice/day open a portal with 30s RP (as operate portal). Works while armoured.',
    materials: { ws: 6, bl: 7, ig: 9 },
    totalMaterials: 22,
    nations: 'all',
  },
  {
    id: 'scriveners-seal',
    name: 'Scrivener\'s Seal',
    tier: 'masterwork',
    form: 'talisman',
    effect: 'Cast create bond (bond-creation only) without mana.',
    materials: { gi: 3, db: 7, ig: 12 },
    totalMaterials: 22,
    nations: 'all',
    skillRequired: 'Magician',
  },
  {
    id: 'staff-of-command',
    name: 'Staff of Command',
    tier: 'masterwork',
    form: 'weapon-implement',
    effect: 'Cast entangle, repel and paralysis as if you know them.',
    materials: { tj: 10, am: 7, ig: 5 },
    totalMaterials: 22,
    nations: 'all',
    skillRequired: 'Battle Mage',
  },
  {
    id: 'staff-of-life',
    name: 'Staff of Life',
    tier: 'masterwork',
    form: 'weapon-implement',
    effect: 'Cast/swift cast heal, purify and restore limb as if you know them.',
    materials: { ws: 7, bl: 10, ig: 5 },
    totalMaterials: 22,
    nations: 'all',
    skillRequired: 'Battle Mage',
  },
  {
    id: 'runesmiths-glare',
    name: 'Runesmith\'s Glare',
    tier: 'masterwork',
    form: 'talisman',
    effect: '★ +1 rank Endurance AND +1 hero point.',
    materials: { gi: 8, or: 7, am: 3, db: 5 },
    totalMaterials: 23,
    nations: ['Wintermark'],
  },
  {
    id: 'strigine-mask',
    name: 'Strigine Mask',
    tier: 'masterwork',
    form: 'talisman',
    effect: '+2 ranks Eyes of the Sun and Moon and Eye of the High Places rituals.',
    materials: { or: 7, ws: 10, db: 3, ig: 3 },
    totalMaterials: 23,
    nations: 'all',
    skillRequired: 'Magician',
  },
  {
    id: 'defiant-steel',
    name: 'Defiant Steel',
    tier: 'masterwork',
    form: 'armour',
    effect: 'Twice/day use relentless without hero points.',
    materials: { gi: 5, or: 5, ws: 9, am: 5 },
    totalMaterials: 24,
    nations: 'all',
  },
  {
    id: 'spiritskin-coat',
    name: 'Spiritskin Coat',
    tier: 'masterwork',
    form: 'armour',
    effect: 'Twice/day use unstoppable without hero points.',
    materials: { ws: 5, am: 11, bl: 5, ig: 3 },
    totalMaterials: 24,
    nations: 'all',
  },
  {
    id: 'suzerains-command',
    name: 'Suzerain\'s Command',
    tier: 'masterwork',
    form: 'weapon-implement',
    effect: '3×/day cast entangle or repel without mana.',
    materials: { tj: 9, am: 9, ig: 6 },
    totalMaterials: 24,
    nations: 'all',
    skillRequired: 'Battle Mage',
  },
  {
    id: 'tombshroud-guardian',
    name: 'Tombshroud Guardian',
    tier: 'masterwork',
    form: 'armour',
    effect: 'Twice/day use unstoppable without hero points.',
    materials: { or: 3, ws: 13, am: 5, db: 3 },
    totalMaterials: 24,
    nations: 'all',
  },
  {
    id: 'trodwalkers-readiness',
    name: 'Trodwalker\'s Readiness',
    tier: 'masterwork',
    form: 'talisman',
    effect: '+1 hero point AND +1 personal mana.',
    materials: { gi: 6, or: 5, tj: 3, db: 5, ig: 5 },
    totalMaterials: 24,
    nations: ['Navarr'],
  },
  {
    id: 'vambraces-of-regeneration',
    name: 'Vambraces of Regeneration',
    tier: 'masterwork',
    form: 'armour',
    effect: 'Twice/day use relentless without hero points.',
    materials: { or: 8, ws: 3, am: 8, ig: 5 },
    totalMaterials: 24,
    nations: 'all',
  },
  {
    id: 'web-of-celestial-attunement',
    name: 'Web of Celestial Attunement',
    tier: 'masterwork',
    form: 'talisman-paraphernalia',
    effect: 'Coven may join another same-nation coven for one ritual. Counts as daily use for both.',
    materials: { or: 5, tj: 9, db: 10 },
    totalMaterials: 24,
    nations: 'all',
  },
  {
    id: 'fell-iron-fury',
    name: 'Fell Iron Fury',
    tier: 'masterwork',
    form: 'weapon-polearm',
    effect: 'Twice/day call CLEAVE or STRIKEDOWN with this pole-arm.',
    materials: { gi: 13, or: 7, am: 5 },
    totalMaterials: 25,
    nations: 'all',
    skillRequired: 'Weapon Master',
  },
  {
    id: 'robe-of-blood-and-bone',
    name: 'Robe of Blood and Bone',
    tier: 'masterwork',
    form: 'armour',
    effect: '3×/day cast heal, purify or restore limb on others without mana (must know the spell).',
    materials: { ws: 9, am: 6, bl: 7, ig: 3 },
    totalMaterials: 25,
    nations: 'all',
    skillRequired: 'Magician',
  },
  {
    id: 'caress-of-arhallogen',
    name: 'Caress of Arhallogen',
    tier: 'masterwork',
    form: 'weapon-implement',
    effect: '3×/day cast venom or paralysis without mana.',
    materials: { am: 9, bl: 9, ig: 9 },
    totalMaterials: 27,
    nations: 'all',
  },
  {
    id: 'bloodfire-periapt',
    name: 'Bloodfire Periapt',
    tier: 'masterwork',
    form: 'talisman',
    effect: 'While VENOMED: +3 ranks Endurance. Lose 3 hits if VENOM is cured or item lost.',
    materials: { gi: 3, or: 7, ws: 11, bl: 7 },
    totalMaterials: 28,
    nations: 'all',
  },
  {
    id: 'ironbound-axe',
    name: 'Ironbound Axe',
    tier: 'masterwork',
    form: 'weapon-1h',
    effect: '3×/day call CLEAVE with this one-handed weapon.',
    materials: { gi: 9, or: 15, bl: 5 },
    totalMaterials: 29,
    nations: 'all',
  },
  {
    id: 'thorns-of-the-rose',
    name: 'Thorns of the Rose',
    tier: 'masterwork',
    form: 'weapon-1h',
    effect: 'After entangling a character, spend hero point to call IMPALE when hitting them.',
    materials: { gi: 5, tj: 12, db: 7, ig: 5 },
    totalMaterials: 29,
    nations: 'all',
  },
  {
    id: 'abraxus-stone',
    name: 'Abraxus Stone',
    tier: 'masterwork',
    form: 'talisman',
    effect: 'When hits are restored to you, also cured of VENOM. Immune to vallorn miasma/green lung/vallornspawn.',
    materials: { tj: 7, ws: 10, bl: 13 },
    totalMaterials: 30,
    nations: ['Navarr'],
  },
  {
    id: 'almery-of-silence',
    name: 'Almery of Silence',
    tier: 'masterwork',
    form: 'talisman-reliquary',
    effect: 'All sect members\' auras concealed from insight ceremony.',
    materials: { or: 5, tj: 7, bl: 7, db: 11 },
    totalMaterials: 30,
    nations: 'all',
  },
  {
    id: 'glamourweave-robe',
    name: 'Glamourweave Robe',
    tier: 'masterwork',
    form: 'armour',
    effect: '4×/day cast empower without mana (must know empower).',
    materials: { gi: 12, or: 7, bl: 3, ig: 8 },
    totalMaterials: 30,
    nations: 'all',
    skillRequired: 'Magician',
  },
  {
    id: 'lowthers-gaze',
    name: 'Lowther\'s Gaze',
    tier: 'masterwork',
    form: 'talisman',
    effect: 'Gain Marksman skill.',
    materials: { gi: 3, tj: 9, am: 6, db: 12 },
    totalMaterials: 30,
    nations: 'all',
  },
  {
    id: 'woundbinder',
    name: 'Woundbinder',
    tier: 'masterwork',
    form: 'weapon-implement',
    effect: '4×/day cast heal without mana.',
    materials: { ws: 11, am: 5, bl: 7, ig: 7 },
    totalMaterials: 30,
    nations: 'all',
    skillRequired: 'Magician',
  },
  {
    id: 'ashen-mantle',
    name: 'Ashen Mantle',
    tier: 'masterwork',
    form: 'armour',
    effect: '+4 personal mana.',
    materials: { am: 4, bl: 5, db: 7, ig: 15 },
    totalMaterials: 31,
    nations: 'all',
    skillRequired: 'Magician',
  },
  {
    id: 'bullroarers-shout',
    name: 'Bullroarer\'s Shout',
    tier: 'masterwork',
    form: 'weapon-polearm',
    effect: '3×/day call STRIKEDOWN with this pole-arm.',
    materials: { gi: 13, or: 5, tj: 8, bl: 5 },
    totalMaterials: 31,
    nations: 'all',
    skillRequired: 'Weapon Master',
  },
  {
    id: 'chirurgeons-ensign',
    name: 'Chirurgeon\'s Ensign',
    tier: 'masterwork',
    form: 'standard',
    effect: 'Use stay with me on two characters simultaneously for cost of one hero point.',
    materials: { or: 5, ws: 11, bl: 5, db: 7, ig: 3 },
    totalMaterials: 31,
    nations: 'all',
  },
  {
    id: 'cowl-of-ashes',
    name: 'Cowl of Ashes',
    tier: 'masterwork',
    form: 'talisman',
    effect: '+3 ranks Whispers through the Black Gate. While wearing, invisible to summoned spirits during ritual.',
    materials: { ws: 3, bl: 12, db: 9, ig: 7 },
    totalMaterials: 31,
    nations: 'all',
    skillRequired: 'Magician',
  },
  {
    id: 'fireglass',
    name: 'Fireglass',
    tier: 'masterwork',
    form: 'talisman',
    effect: '3×/day when using anointing, restore a hero point to target instead of creating aura.',
    materials: { gi: 5, or: 7, tj: 9, db: 10 },
    totalMaterials: 31,
    nations: 'all',
    skillRequired: 'Dedication',
  },
  {
    id: 'keepers-habit',
    name: 'Keeper\'s Habit',
    tier: 'masterwork',
    form: 'armour',
    effect: '3×/day use get it together without hero points.',
    materials: { gi: 4, or: 7, am: 5, bl: 4, db: 7, ig: 4 },
    totalMaterials: 31,
    nations: 'all',
    skillRequired: 'Dedication',
  },
  {
    id: 'trollslayers-crescent',
    name: 'Trollslayer\'s Crescent',
    tier: 'masterwork',
    form: 'weapon-1h',
    effect: '+2 hero points.',
    materials: { gi: 20, or: 5, ws: 3, db: 3 },
    totalMaterials: 31,
    nations: 'all',
  },
  {
    id: 'twilight-pauldrons',
    name: 'Twilight Pauldrons',
    tier: 'masterwork',
    form: 'armour',
    effect: '+4 personal mana.',
    materials: { tj: 5, ws: 3, bl: 5, db: 3, ig: 15 },
    totalMaterials: 31,
    nations: 'all',
    skillRequired: 'Battle Mage',
  },
  {
    id: 'wayfinder',
    name: 'Wayfinder',
    tier: 'masterwork',
    form: 'weapon-1h',
    effect: '+2 hero points.',
    materials: { gi: 15, am: 10, bl: 3, db: 3 },
    totalMaterials: 31,
    nations: 'all',
  },
  {
    id: 'winterborn-warmail',
    name: 'Winterborn Warmail',
    tier: 'masterwork',
    form: 'armour',
    effect: '+3 ranks Endurance.',
    materials: { or: 14, ws: 7, am: 7, bl: 3 },
    totalMaterials: 31,
    nations: 'all',
  },
  {
    id: 'grimnirs-hearthfire',
    name: 'Grimnir\'s Hearthfire',
    tier: 'masterwork',
    form: 'weapon-implement',
    effect: 'When you cast (not swift cast) heal, also restore all CLEAVE/IMPALE ruined limbs.',
    materials: { ws: 16, am: 9, ig: 7 },
    totalMaterials: 32,
    nations: 'all',
    skillRequired: 'Magician',
  },
  {
    id: 'labyrinths-gate',
    name: 'Labyrinth\'s Gate',
    tier: 'masterwork',
    form: 'weapon-polearm',
    effect: 'Spend hero point to call IMPALE with this pole-arm.',
    materials: { gi: 11, or: 4, tj: 17 },
    totalMaterials: 32,
    nations: 'all',
    skillRequired: 'Weapon Master',
  },
  {
    id: 'sanguine-thorn',
    name: 'Sanguine Thorn',
    tier: 'masterwork',
    form: 'weapon-implement',
    effect: 'When you cast (not swift cast) heal, also remove VENOM and/or WEAKNESS from target.',
    materials: { or: 6, ws: 3, bl: 13, ig: 10 },
    totalMaterials: 32,
    nations: 'all',
    skillRequired: 'Magician',
  },
  {
    id: 'the-eternal-gambit',
    name: 'The Eternal Gambit',
    tier: 'masterwork',
    form: 'talisman-paraphernalia',
    effect: 'Once/day coven may perform any realm ritual without counting toward daily limit.',
    materials: { gi: 3, or: 3, tj: 7, ws: 3, am: 3, bl: 3, db: 7, ig: 3 },
    totalMaterials: 32,
    nations: 'all',
  },
  {
    id: 'trollhammer',
    name: 'Trollhammer',
    tier: 'masterwork',
    form: 'weapon-great',
    effect: '★ Spend hero point to call PARALYSE with this great weapon.',
    materials: { gi: 7, tj: 10, am: 9, bl: 6 },
    totalMaterials: 32,
    nations: ['Wintermark'],
    skillRequired: 'Weapon Master',
  },
  {
    id: 'runeplate',
    name: 'Runeplate',
    tier: 'masterwork',
    form: 'armour',
    effect: '★ +2 hero points. Powerful urge to perform great deeds (roleplaying effect).',
    materials: { gi: 24, or: 5, bl: 3, db: 3 },
    totalMaterials: 35,
    nations: ['Wintermark'],
  },
  {
    id: 'troubadours-tunic',
    name: 'Troubadour\'s Tunic',
    tier: 'masterwork',
    form: 'armour',
    effect: '+2 hero points.',
    materials: { gi: 7, bl: 4, db: 19, ig: 5 },
    totalMaterials: 35,
    nations: 'all',
    skillRequired: 'Dedication',
  },
  {
    id: 'shieldbreaker',
    name: 'Shieldbreaker',
    tier: 'masterwork',
    form: 'weapon-1h',
    effect: 'Twice/day call SHATTER when you strike an enemy\'s weapon or shield.',
    materials: { gi: 7, or: 8, tj: 11, am: 3, bl: 7 },
    totalMaterials: 36,
    nations: 'all',
  },
  {
    id: 'the-drowned-threshold',
    name: 'The Drowned Threshold',
    tier: 'masterwork',
    form: 'talisman-paraphernalia',
    effect: '✦ Once/day coven may perform any realm ritual that doesn\'t count toward daily limit.',
    materials: { or: 5, tj: 7, ws: 5, am: 5, bl: 5, db: 5, ig: 5 },
    totalMaterials: 37,
    nations: 'all',
    notes: 'Cost needs wiki verification',
  },
  {
    id: 'virtuous-ward',
    name: 'Virtuous Ward',
    tier: 'masterwork',
    form: 'talisman',
    effect: 'When another character heals you with spell/ritual/heroic/chirurgeon skill, regain 2 additional hits.',
    materials: { or: 7, tj: 9, bl: 7, db: 9, ig: 5 },
    totalMaterials: 37,
    nations: 'all',
    skillRequired: 'Dedication',
  },
  {
    id: 'semblance-of-the-witch',
    name: 'Semblance of the Witch',
    tier: 'masterwork',
    form: 'armour',
    effect: '+3 ranks Night lore for next Night ritual (tonic effect). Confidence bonus in social situations.',
    materials: { tj: 5, ws: 7, bl: 7, db: 5, ig: 16 },
    totalMaterials: 40,
    nations: ['League'],
    skillRequired: 'Magician',
  },
  {
    id: 'sceptre-of-the-necropolis',
    name: 'Sceptre of the Necropolis',
    tier: 'masterwork',
    form: 'weapon-implement',
    effect: 'Once/day: spend hero point to call PARALYSE and CLEAVE simultaneously; if target survives you gain WEAKNESS.',
    materials: { tj: 5, am: 12, bl: 20, ig: 5 },
    totalMaterials: 42,
    nations: 'all',
    skillRequired: 'Magician',
  },
  {
    id: 'the-key-and-the-gate',
    name: 'The Key and the Gate',
    tier: 'masterwork',
    form: 'talisman-paraphernalia',
    effect: 'Once/day coven: one additional non-coven character may contribute to a ritual as a contributor.',
    materials: { or: 7, tj: 7, ws: 12, bl: 9, db: 5, ig: 2 },
    totalMaterials: 42,
    nations: 'all',
  },
  {
    id: 'the-spiders-web',
    name: 'The Spider\'s Web',
    tier: 'masterwork',
    form: 'talisman-paraphernalia',
    effect: 'Once/day coven: one additional character who hasn\'t mastered the ritual gains +1 effective rank.',
    materials: { gi: 12, tj: 7, ws: 9, bl: 7, db: 5, ig: 2 },
    totalMaterials: 42,
    nations: 'all',
  },
  {
    id: 'woodcutters-axe',
    name: 'Woodcutter\'s Axe',
    tier: 'masterwork',
    form: 'weapon-great',
    effect: 'Once/day call SHATTER on any weapon, shield or armour you strike with this great weapon.',
    materials: { gi: 9, or: 9, tj: 15, am: 3, bl: 3, db: 3 },
    totalMaterials: 42,
    nations: 'all',
    skillRequired: 'Weapon Master',
  },
  {
    id: 'terunael-warlord',
    name: 'Terunael Warlord',
    tier: 'masterwork',
    form: 'weapon-spear',
    effect: 'Once/day call CLEAVE, ENTANGLE, SHATTER or PARALYSE with this one-handed spear.',
    materials: { or: 9, tj: 9, am: 12, bl: 10, ig: 3 },
    totalMaterials: 43,
    nations: ['Navarr'],
    skillRequired: 'Weapon Master',
  },
  {
    id: 'thaneshall-banner',
    name: 'Thaneshall Banner',
    tier: 'masterwork',
    form: 'standard',
    effect: 'Once/day use unstoppable without hero points. Once/day use stay with me without hero points.',
    materials: { gi: 11, or: 7, bl: 7, db: 11, ig: 7 },
    totalMaterials: 43,
    nations: 'all',
  },
  {
    id: 'silent-bell',
    name: 'Silent Bell',
    tier: 'masterwork',
    form: 'talisman',
    effect: '3×/day use exorcism without liao. Once/day your exorcism also removes WEAKNESS.',
    materials: { or: 7, ws: 7, bl: 14, db: 11, ig: 5 },
    totalMaterials: 44,
    nations: 'all',
    skillRequired: 'Dedication',
  },
  {
    id: 'skein-bowl',
    name: 'Skein Bowl',
    tier: 'masterwork',
    form: 'talisman',
    effect: 'When you use testimony, spend up to 3 extra doses of liao to increase strength by same amount.',
    materials: { tj: 5, ws: 7, am: 7, bl: 9, db: 11, ig: 5 },
    totalMaterials: 44,
    nations: 'all',
    skillRequired: 'Dedication',
  },
  {
    id: 'sanguine-staff',
    name: 'Sanguine Staff',
    tier: 'masterwork',
    form: 'weapon-implement',
    effect: '+1 rank Spring Lore for rituals (effective skill).',
    materials: { tj: 11, am: 14, db: 20 },
    totalMaterials: 45,
    nations: 'all',
    skillRequired: 'Magician',
  },
  {
    id: 'staff-of-the-magi',
    name: 'Staff of the Magi',
    tier: 'masterwork',
    form: 'weapon-implement',
    effect: 'Cast detect magic, create bond and operate portal without spending mana (unlimited uses).',
    materials: { or: 9, tj: 9, bl: 12, ig: 15 },
    totalMaterials: 45,
    nations: 'all',
    skillRequired: 'Battle Mage',
  },
  {
    id: 'titans-battlemark',
    name: 'Titan\'s Battlemark',
    tier: 'masterwork',
    form: 'standard',
    effect: 'While wielding, you cannot be taken below 1 hit by any single blow (once per day).',
    materials: { gi: 7, or: 14, ws: 7, am: 9, bl: 5, ig: 5 },
    totalMaterials: 47,
    nations: 'all',
  },
  {
    id: 'thorns-mark',
    name: 'Thorn\'s Mark',
    tier: 'masterwork',
    form: 'weapon-spear',
    effect: '★ Once/day call PARALYSE with this one-handed spear.',
    materials: { gi: 12, or: 3, tj: 7, am: 8 },
    totalMaterials: 30,
    nations: ['Wintermark'],
    skillRequired: 'Weapon Master',
  },
  {
    id: 'the-syphon-of-stars',
    name: 'The Syphon of Stars',
    tier: 'masterwork',
    form: 'talisman-paraphernalia',
    effect: 'Once/day: all coven members who haven\'t mastered the ritual gain +1 effective rank.',
    materials: { gi: 5, or: 5, tj: 11, ws: 5, am: 5, bl: 5, db: 9, ig: 5 },
    totalMaterials: 50,
    nations: 'all',
  },
  {
    id: 'staff-of-imperial-mastery',
    name: 'Staff of Imperial Mastery',
    tier: 'masterwork',
    form: 'weapon-implement',
    effect: 'Cast ALL spells (detect magic, create bond, operate portal, heal, mend, night pouch, purify, restore limb, voice for the dead, empower, entangle, paralysis, repel, shatter, venom, weakness) as if you know them.',
    materials: { gi: 7, or: 7, tj: 7, ws: 7, am: 7, bl: 7, db: 7, ig: 7 },
    totalMaterials: 56,
    nations: 'all',
    skillRequired: 'Battle Mage',
  },
  {
    id: 'thorns-dance',
    name: 'Thorn\'s Dance',
    tier: 'masterwork',
    form: 'standard',
    effect: 'Once/day swift cast restore limb without mana on anyone near the banner.',
    materials: { ws: 9, am: 15, bl: 10, db: 13, ig: 9 },
    totalMaterials: 56,
    nations: ['Navarr'],
  },
  {
    id: 'three-tears',
    name: 'Three Tears',
    tier: 'masterwork',
    form: 'standard',
    effect: '★ Once/day use unstoppable without hero points. All allies who are terminal regain 1 hit.',
    materials: { gi: 16, or: 10, bl: 10, db: 14, ig: 10 },
    totalMaterials: 60,
    nations: ['Wintermark'],
  },
  {
    id: 'warsmiths-shingle',
    name: 'Warsmith\'s Shingle',
    tier: 'masterwork',
    form: 'standard',
    effect: 'Once/day repair any mundane weapon or shield with 10s RP. While wielding, all allies\' weapons/shields cannot be shattered.',
    materials: { or: 20, tj: 5, am: 14, bl: 9, db: 13, ig: 7 },
    totalMaterials: 68,
    nations: ['Varushka'],
  },
  {
    id: 'the-fountain-of-thorns',
    name: 'The Fountain of Thorns',
    tier: 'masterwork',
    form: 'talisman-paraphernalia',
    effect: '✦ Once/day coven may perform a Spring ritual that doesn\'t count toward daily limit.',
    materials: { tj: 9, ws: 3, am: 7, bl: 3, db: 7 },
    totalMaterials: 29,
    nations: 'all',
    notes: 'Cost needs wiki verification',
  },
  {
    id: 'the-mountainous-oak',
    name: 'The Mountainous Oak',
    tier: 'masterwork',
    form: 'talisman-paraphernalia',
    effect: '✦ Once/day coven may perform a Summer ritual that doesn\'t count toward daily limit.',
    materials: { gi: 7, or: 5, tj: 5, ws: 5, bl: 3, db: 5 },
    totalMaterials: 30,
    nations: 'all',
    notes: 'Cost needs wiki verification',
  },
  {
    id: 'the-vagabond-wyrm',
    name: 'The Vagabond Wyrm',
    tier: 'masterwork',
    form: 'talisman-paraphernalia',
    effect: '✦ Once/day coven may perform a Night ritual that doesn\'t count toward daily limit.',
    materials: { or: 3, tj: 7, ws: 3, am: 5, bl: 5, db: 7 },
    totalMaterials: 30,
    nations: 'all',
    notes: 'Cost needs wiki verification',
  },
  {
    id: 'winternight-lifestealer',
    name: 'Winternight Lifestealer',
    tier: 'masterwork',
    form: 'weapon-polearm',
    effect: 'Once/day call IMPALE AND CLEAVE simultaneously with this pole-arm.',
    materials: { gi: 7, or: 5, tj: 13, bl: 7 },
    totalMaterials: 32,
    nations: 'all',
    skillRequired: 'Weapon Master',
  },
];
