export interface Potion {
  name: string;
  rpEffect: string;
  mechEffect: string;
  materials: {
    bladeroot?: number;
    cerulean?: number;
    roseweald?: number;
    marrowort?: number;
    vervain?: number;
    mana?: number;
    liao?: number;
    ilium?: number;
  };
  total: number;
}

// 91 potions from Dump.xlsx
export const POTIONS_CATALOGUE: Potion[] = [
  {
    name: 'Anodyne Analgesic',
    rpEffect: 'The liquid numbs the pain of your injuries, and provides an invigoration that quickly clears your mind.',
    mechEffect: 'You can overcome the roleplaying effect of a single traumatic wound of your choice until the end of the current engagement.',
    materials: {marrowort: 1, vervain: 1},
    total: 2,
  },
  {
    name: 'Bloodharrow Philtre',
    rpEffect: 'Pain spreads rapidly through your body; you feel as if your blood is on fire. After a moment or two, the pain fades.',
    mechEffect: 'You lose the venom condition.',
    materials: {roseweald: 1, marrowort: 1},
    total: 2,
  },
  {
    name: 'Elixir Vitae',
    rpEffect: 'A warm glow spreads quickly through your body, removing pain, revitalising your spirit and creating a sense of enormous well-being.',
    mechEffect: 'You regain up to three lost hits.',
    materials: {cerulean: 1, vervain: 1},
    total: 2,
  },
  {
    name: 'Feverfail Elixir',
    rpEffect: 'You feel nauseous. A dizzying chill spreads through your body, leaving you incapacitated for a few moments. Both effects clear as quickly as they arose, leaving you feeling revitalised.',
    mechEffect: 'You lose the weakness condition.',
    materials: {bladeroot: 1, roseweald: 1},
    total: 2,
  },
  {
    name: 'Ossean Solution',
    rpEffect: 'You feel a numbness spreading through the flesh of your ruined limb as the torn ligaments and broken bones fuse together.',
    mechEffect: 'You regain the use of a single limb that has been ruined by cleave or impale.',
    materials: {bladeroot: 1, cerulean: 1},
    total: 2,
  },
  {
    name: 'Balms of the Fountainhead',
    rpEffect: '',
    mechEffect: '',
    materials: {},
    total: 0,
  },
  {
    name: 'Vernal Balm',
    rpEffect: 'You become prone to sudden mood shifts and displays of strong emotion. Your attitudes become more straightforward, and you find complex plans and overthinking frustrating. You would rather take action than talk about it.',
    mechEffect: 'If you possess the Spring lore skill then you gain one additional effective rank to the next Spring ritual that you perform within ten minutes, subject to the normal rules for effective skill. This is a tonic; the effect of any other tonic you have drunk immediately ends.',
    materials: {roseweald: 2, marrowort: 2, vervain: 1, mana: 1},
    total: 6,
  },
  {
    name: 'Suffusion of Blood',
    rpEffect: 'You become very direct, preferring to go directly to the heart of a problem, say what you think, or deal with immediate problems. You find it difficult to think about the past, or anything more pressing than the immediate future. You also become emotionally volatile, and are especially short-tempered. Anything that frustrates or irritates you is likely to cause you to lash out against its source.',
    mechEffect: 'If you possess the Spring lore skill then you can use up to 3 personal mana as if it were crystal mana on the next spring ritual that you perform within ten minutes.',
    materials: {bladeroot: 1, cerulean: 1, roseweald: 3, marrowort: 1, vervain: 2},
    total: 8,
  },
  {
    name: 'Talonvine Infusion',
    rpEffect: 'If you have inhaled the steam or smoke, you feel a rush of vitality and strength that quickly fades but leaves a powerful desire to take action - without concern for rules or long-term consequences. If instead you ate this substance, you experience stabbing stomach pains (consult a ref).',
    mechEffect: 'If you possess the Spring lore skill then you gain three additional ranks to the next spring ritual that you perform within ten minutes, subject to the normal rules for effective skill. This is a tonic; the effect of any other tonic you have drunk immediately ends.',
    materials: {roseweald: 3, marrowort: 3, vervain: 1, mana: 1, ilium: 1},
    total: 9,
  },
  {
    name: 'Decoctions of Hoarfrost',
    rpEffect: '',
    mechEffect: '',
    materials: {},
    total: 0,
  },
  {
    name: 'Decoction of the Hungry Moon',
    rpEffect: 'This potion tastes unpleasantly of spoiled meat. You become emotionally cold but highly possessive and protective of your friends and allies.',
    mechEffect: 'If you possess the Winter lore skill then you gain one additional effective rank to the next Winter ritual that you perform within ten minutes, subject to the normal rules for effective skill. This is a tonic; the effect of any other tonic you have drunk immediately ends.',
    materials: {bladeroot: 2, marrowort: 1, vervain: 2, mana: 1},
    total: 6,
  },
  {
    name: 'The Barren Watchtower',
    rpEffect: 'Drinking this elixir makes you very thirsty and dry mouthed. You become cold and calculating, seeing everything in terms of cost and benefit. Individual lives or needs become meaningless in the face of your goals and what you consider to be best. You feel a powerful urge to ensure you and yours are safe, regardless of the cost to other people.',
    mechEffect: 'If you possess the Winter lore skill then you can use up to 3 personal mana as if it were crystal mana on the next Winter ritual that you perform within ten minutes.',
    materials: {bladeroot: 3, cerulean: 1, roseweald: 1, marrowort: 2, vervain: 1},
    total: 8,
  },
  {
    name: 'Sorrow\'s Mask',
    rpEffect: 'Where this balm has been applied, your skin becomes numb. You are constantly reminded of your regrets; it is easy for you to succumb to feelings of grief, loss, despair, and sorrow if you do not keep focused on the task at hand.',
    mechEffect: 'If you possess the Winter lore skill then you gain three additional ranks to the next Winter ritual that you perform within ten minutes, subject to the normal rules for effective skill. This is a tonic; the effect of any other tonic you have drunk immediately ends.',
    materials: {bladeroot: 3, marrowort: 1, vervain: 3, mana: 1, ilium: 1},
    total: 9,
  },
  {
    name: 'Double-sided Blade',
    rpEffect: '',
    mechEffect: '',
    materials: {},
    total: 0,
  },
  {
    name: 'Warming Armour',
    rpEffect: 'You feel a warmth in your belly that spreads quickly throughout your body. You feel an urge to take bloody, violent revenge on anyone you feel has wronged you.',
    mechEffect: 'You are subject to the VENOM condition. If this condition is removed prematurely, you immediately drop to 0 hits. If you are an orc, you also gain 3 additional ranks of endurance. If you are a human, you gain 2 additional ranks of endurance. The effects last until the end of the next skirmish, battle, or quest or until the VENOM is removed. This is a tonic; the effect of any other tonic you have drunk immediately ends.',
    materials: {cerulean: 1, roseweald: 2, marrowort: 1, vervain: 2},
    total: 6,
  },
  {
    name: 'Weakening Sun',
    rpEffect: 'You feel a burst of euphoria that slowly fades but never goes away. Painful or uncomfortable sensations are muted, and you feel an urge to submit to anyone who you feel has authority over you.',
    mechEffect: 'You are subject to the WEAKNESS condition. If this condition is removed prematurely, you immediately drop to 0 hits. If you are an orc, you also gain 3 additional ranks of endurance. If you are a human, you gain 2 additional ranks of endurance. The effects last until the end of the next skirmish, battle, or quest, or the WEAKNESS is removed. This is a tonic; the effect of any other tonic you have drunk immediately ends.',
    materials: {bladeroot: 2, cerulean: 1, marrowort: 2, vervain: 1},
    total: 6,
  },
  {
    name: 'Infusions of Feathers',
    rpEffect: '',
    mechEffect: '',
    materials: {},
    total: 0,
  },
  {
    name: 'Magpie Infusion',
    rpEffect: 'Your tongue and lips are numbed, meaning your speech is slurred. You find yourself blinking rapidly, or suffering from watering eyes. Any spell that you hear being cast causes you to perceive dramatic displays of colourful light that can be quite distracting.',
    mechEffect: 'Inhaling the steam from this infusion grants you the ability to use the detect magic spell once during the next ten minutes without requiring you to know the spell or expend any mana.',
    materials: {cerulean: 2},
    total: 2,
  },
  {
    name: 'Ravenwing Infusion',
    rpEffect: 'You feel suddenly dizzy, and then lose the ability to see colours; everything becomes visible in shades of grey. The exception is that you can see colourful auras around living creatures, with the colour and intensity reflecting how you feel about that person. The night after taking this infusion, you will have exceptionally vivid dreams.',
    mechEffect: 'Inhaling the steam from this infusion grants you the ability to use the insight skill once during the next ten minutes without requiring you to know the skill or expend any liao.',
    materials: {bladeroot: 1, cerulean: 1, roseweald: 1, marrowort: 1},
    total: 4,
  },
  {
    name: 'Goosewhisper Infusion',
    rpEffect: 'For around an hour after experiencing this infusion, you see things out of the corner of your eye; anyone you are not looking at directly appears to be surrounded by a shimmering multicoloured halo. You tend to see things in symbolic ways, and may see weird images hanging around people you know, relating to how you feel about them. These effects are very pronounced if you are a member of the naga lineage.',
    mechEffect: 'Inhaling the steam from this infusion causes you to enter a trance during which you suffer a brief but intense vision. This vision is provided by a referee, and will contain information about things that are happening, have happened or may happen at the event. There is no way to direct this vision towards a specific topic. These visions are the same as those received from the Signs and Portents ritual; you will receive the same vision if you are part of that ritual, have already performed it, or have already taken a dose of Goosewhisper Infusion.',
    materials: {bladeroot: 2, marrowort: 1, vervain: 1},
    total: 4,
  },
  {
    name: 'Lambent Essences',
    rpEffect: '',
    mechEffect: '',
    materials: {},
    total: 0,
  },
  {
    name: 'Effulgent Primessence',
    rpEffect: 'You become calm and cerebral, fascinated by thoughts, ideas and knowledge. You are disinclined to physical action where mental action might be sufficient. Your movements and thoughts become precise and ordered',
    mechEffect: 'If you possess the Day lore skill, then you gain one additional effective rank to the next Day ritual that you perform within ten minutes, subject to the normal rules for effective skill. This is a tonic; the effect of any other tonic you have drunk immediately ends.',
    materials: {bladeroot: 1, cerulean: 1, marrowort: 2, vervain: 1, mana: 1},
    total: 6,
  },
  {
    name: 'Lucent Quintessence',
    rpEffect: 'You become highly focused, pursuing things that interest you with stubborn doggedness. You find it difficult to show interest in things that do not engage your intellect, no matter how important it might be to others.',
    mechEffect: 'If you possess the Day lore skill then you can use up to 3 personal mana as if it were crystal mana on the next day ritual that you perform within ten minutes.',
    materials: {bladeroot: 2, cerulean: 1, marrowort: 3, vervain: 2},
    total: 8,
  },
  {
    name: 'Radiant Transcendence',
    rpEffect: 'This salve cleans your skin as it is absorbed. You become increasingly offended by anything you see as disordered, random, or inefficient. You feel an urge to impose order on your surroundings, and on the people around you.',
    mechEffect: 'If you possess the Day lore skill, then you gain three additional ranks to the next Day ritual that you perform within ten minutes, subject to the normal rules for effective skill. This is a tonic; the effect of any other tonic you have drunk immediately ends.',
    materials: {bladeroot: 1, cerulean: 1, marrowort: 3, vervain: 2, mana: 1, ilium: 1},
    total: 9,
  },
  {
    name: 'Legacy of Thorns',
    rpEffect: '',
    mechEffect: '',
    materials: {},
    total: 0,
  },
  {
    name: 'Oil of Blackthorn',
    rpEffect: 'If you drink this oil, you are subject to nausea and painful stomach cramps for the next half hour, although if you vomit or are treated with the purify spell or by anything else that can end the weakness or venom conditions, you can alleviate these symptoms early.',
    mechEffect: 'This oil must be smeared on a melee weapon over 5 seconds. The wielder must call VENOM on the next blow with the weapon within 10 seconds.',
    materials: {bladeroot: 2, cerulean: 1, marrowort: 1, vervain: 1},
    total: 5,
  },
  {
    name: 'Redwillow Paste',
    rpEffect: 'If you drink this oil, you are subject to the sudden onset of a feverish temperature accompanied by severe sweating, headache, tiredness and other flu-like symptoms that last for the next half hour, although if you vomit or are treated with the purify spell or by anything else that can end the weakness or venom conditions, you can alleviate these symptoms early.',
    mechEffect: 'This oil must be smeared on a melee weapon over 5 seconds. The wielder must call WEAKNESS on the next blow with the weapon within 10 seconds.',
    materials: {cerulean: 1, roseweald: 2, marrowort: 1, vervain: 1},
    total: 5,
  },
  {
    name: 'Legionnaire\'s Stare',
    rpEffect: 'If you drink this oil, you are subject to the sudden onset of a feverish chill accompanied by severe sweating, significant lower back pain, and a strong need to urinate that last for the next half hour, although if you vomit or are treated with the purify spell or by anything else that can end the weakness or venom conditions, you can alleviate these symptoms early.',
    mechEffect: 'This oil must be smeared on a melee weapon over 5 seconds. The wielder must call PARALYSE on the next blow with the weapon within 10 seconds.',
    materials: {bladeroot: 3, cerulean: 1, marrowort: 2, vervain: 2},
    total: 8,
  },
  {
    name: 'Gutwrench',
    rpEffect: 'As long as you suffer from either weakness or venom, you feel as if your stomach is on fire; you may experience other symptoms including severe sweating, feverishly elevated temperature, throbbing aches in the head and joints, tiredness, agonising stomach cramps, nausea, dizziness and painfully heightened senses that make bright lights or loud noises almost unbearable.',
    mechEffect: 'You are subject to both the weakness and venom conditions. These conditions may be removed normally.',
    materials: {bladeroot: 2, cerulean: 1, roseweald: 2},
    total: 5,
  },
  {
    name: 'Magnum Opus',
    rpEffect: '',
    mechEffect: '',
    materials: {},
    total: 0,
  },
  {
    name: 'Chiaroscuran Balsam',
    rpEffect: 'You feel giddy and excitable for several minutes after applying this balsam. You feel every emotion very strongly and have a strong urge to be gregarious, to seek out opportunities to interact with others wherever they present themselves, and want to be comfortable, well-fed and content.',
    mechEffect: 'If you possess the Night lore skill, then you gain one additional effective rank to the next night ritual that you perform within ten minutes, subject to the normal rules for effective skill. This is a tonic; the effect of any other tonic you have drunk immediately ends.',
    materials: {bladeroot: 1, roseweald: 2, marrowort: 1, vervain: 1, mana: 1},
    total: 6,
  },
  {
    name: 'Philosopher\'s Stone',
    rpEffect: 'This elixir has a strong taste of something (practically any taste is possible). You feel a strong urge to be mysterious and enigmatic; to avoid direct answers, to conceal your intentions and to couch your speech in allusion and metaphor. Direct answers and direct solutions are unsatisfying.',
    mechEffect: 'If you possess the Night lore skill then you can use up to 3 personal mana as if it were crystal mana on the next night ritual that you perform within ten minutes.',
    materials: {bladeroot: 2, cerulean: 2, roseweald: 3, vervain: 1},
    total: 8,
  },
  {
    name: 'Black Star',
    rpEffect: 'You are filled with a growing sense that there is a conspiracy at work around you. It is easy to start speculating on the secret schemes that underlie anything from the performance of your ritual, to the formation of your coven, to the choice of clothing a stranger has made.',
    mechEffect: 'If you possess the Night Lore skill, then you gain three additional ranks to the next Night ritual that you perform within ten minutes, subject to the normal rules for effective skill. This is a tonic; the effect of any other tonic you have drunk immediately ends.',
    materials: {bladeroot: 2, roseweald: 3, marrowort: 1, vervain: 1, mana: 1, ilium: 1},
    total: 9,
  },
  {
    name: 'Master Medicinal',
    rpEffect: '',
    mechEffect: '',
    materials: {},
    total: 0,
  },
  {
    name: 'Tranquil Nostrum',
    rpEffect: 'You feel lethargic, sleepy and relaxed, disinclined to be active or aggressive.',
    mechEffect: 'This preparation is used to brew a pot of tea. Each person drinking a cup of the tea recovers all lost hits after fifteen minutes of rest and relaxation. There is no effect if the drinker is on a battlefield or similar stressful environment. If the drinker attacks a target or is attacked during this time then the effect is negated. The tea loses its beneficial properties fifteen minutes after being brewed regardless.',
    materials: {bladeroot: 1, marrowort: 1},
    total: 2,
  },
  {
    name: 'Maledict\'s Medicament',
    rpEffect: 'You feel nauseous and dizzy; you may be overcome with retching and vertigo for a few moments.',
    mechEffect: 'You are relieved of both the venom and the weakness conditions.',
    materials: {bladeroot: 1, cerulean: 1, roseweald: 1},
    total: 3,
  },
  {
    name: 'The Sovereign Specific',
    rpEffect: 'You feel lightheaded for a moment, then refreshed and full of energy, and an incredible sense of wellbeing suffuses you. It is hard not to be filled with optimism and enthusiasm.',
    mechEffect: 'This potion removes the venom and weakness conditions from you, restores all limbs ruined by cleave or impale, and restores you to full hits. You may ignore the roleplaying effects of any traumatic wounds you are suffering until the end of the battle.',
    materials: {bladeroot: 1, cerulean: 1, roseweald: 1, marrowort: 1, vervain: 3},
    total: 7,
  },
  {
    name: 'Philtres of the High Peaks',
    rpEffect: '',
    mechEffect: '',
    materials: {},
    total: 0,
  },
  {
    name: 'Mageblood',
    rpEffect: 'You feel an urge to gaze in wonder at the world around you for a few moments.',
    mechEffect: 'You regain up to 2 points of spent personal mana. If you do not have personal mana, the preparation has no effect.',
    materials: {roseweald: 1, vervain: 1},
    total: 2,
  },
  {
    name: 'The Philtre of Heavenly Lore',
    rpEffect: 'You feel a strong urge to gather magical power, items and knowledge.',
    mechEffect: 'You regain up to 6 points of personal mana. If you do not have personal mana, this preparation has no effect.',
    materials: {bladeroot: 2, cerulean: 1, roseweald: 2},
    total: 5,
  },
  {
    name: 'The Elixir of Empyrean Art',
    rpEffect: 'You are filled with almost painful amounts of magical power. As long as you have personal mana remaining, you feel a strong urge to perform magic as often as possible. When the effects wear off, you feel a vague urge to sample them again.',
    mechEffect: 'You regain all your spent personal mana, and gain an additional 2 points of temporary personal mana. These temporary points are the first ones spent when you spend personal mana. If you have not used these temporary points within half an hour, they are lost. If you do not have personal mana, this preparation has no effect.',
    materials: {bladeroot: 3, cerulean: 2, roseweald: 2, vervain: 1, ilium: 1},
    total: 9,
  },
  {
    name: 'Thresher\'s Tea',
    rpEffect: 'You are confused, unable to concentrate properly or focus your thoughts for at least the next ten minutes.',
    mechEffect: 'If you have any personal mana, you immediately lose it all. You can regain personal mana normally.',
    materials: {cerulean: 2, marrowort: 1, vervain: 1},
    total: 4,
  },
  {
    name: 'Philtres of War',
    rpEffect: '',
    mechEffect: '',
    materials: {},
    total: 0,
  },
  {
    name: 'Philtre of Strength',
    rpEffect: 'You feel all your cares and worries fall away; you feel a strong urge to shout, bellow or sing something as you are suddenly invigorated.',
    mechEffect: 'You regain one spent hero point. If you have no hero points this potion has no effect.',
    materials: {bladeroot: 1, vervain: 2},
    total: 3,
  },
  {
    name: 'Skop\'s Mead',
    rpEffect: 'You feel a burst of renewed energy, and an urge to act immediately in pursuit of your goals. You also feel a strong urge to share your confidence with, and raise the morale of, your allies - to inspire others to follow your lead.',
    mechEffect: 'You regain three spent hero points. If you have no hero points this potion has no effect.',
    materials: {bladeroot: 2, roseweald: 2, marrowort: 1, vervain: 3},
    total: 8,
  },
  {
    name: 'Elixir of Exalted Puissance',
    rpEffect: 'You are filled with a sensation of immense confidence and belief in your own abilities. You want to demonstrate your prowess to everyone.',
    mechEffect: 'You regain all your spent hero points, and gain an additional temporary hero point. This temporary point is the first one spent when you spend hero points. If you have not used this temporary hero point within half an hour, it is lost. If you do not have hero points, this preparation has no effect.',
    materials: {bladeroot: 2, roseweald: 3, marrowort: 1, vervain: 2, ilium: 1},
    total: 9,
  },
  {
    name: 'Tincture of the Whipped Cur',
    rpEffect: 'You are filled with self-doubt and uncertainty for at least ten minutes.',
    mechEffect: 'You immediately lose all your hero points. You can regain hero points normally.',
    materials: {bladeroot: 2, cerulean: 1, marrowort: 1},
    total: 4,
  },
  {
    name: 'Runa\'s Gift',
    rpEffect: '',
    mechEffect: '',
    materials: {},
    total: 0,
  },
  {
    name: 'Greenmaster\'s Reach',
    rpEffect: 'If you are an orc, you feel a surge of conviction of your past actions; you are strongly aware of the voices of those ancestors that encourage you to strengthen yourself or improve your status, urging you to surpass what you have achieved so far. If you are a human, you feel a dizzying sense of euphoria that slowly builds. At the same time you feel your senses becoming keener until any strong sensory stimulation becomes almost painful.',
    mechEffect: 'If you are an orc and you have the magician skill, you can cast either Repel or Entangle once without expending personal mana or crystal mana within 10 seconds. You do not need to be able to cast either spell to benefit from this effect. If you are a human, or an orc who does not have the magician skill, the potion has no mechanical effect.',
    materials: {roseweald: 1, ilium: 1},
    total: 0,
  },
  {
    name: 'Brokendraught',
    rpEffect: 'If you are an orc, you feel a sense of power surge through you that quickly becomes almost overwhelming. You feel empowered to take action, doubts and worries feel distant and indistinct. Taking action to reduce or prevent suffering or pain feels righteous and empowering, and after the effect ends you may experience a craving to feel it again. If you are human, you becomes increasingly certain that you can "smell" magic around you as your senses shift and become unreliable. You quickly become disoriented and confused, unsure of what is real and what is a hallucination.',
    mechEffect: 'If you are an orc and you have the magician skill, you can either swift cast Restore Limb or cast Shatter once without expending personal mana or crystal mana within 10 seconds. You do not need to be able to cast either spell to benefit from this effect. If you are a human, or an orc that does not have the magician skill, the potion has no mechanical effect.',
    materials: {cerulean: 1, ilium: 1},
    total: 0,
  },
  {
    name: 'Runa\'s Whisper',
    rpEffect: 'If you are an orc, you are intensely reminded of the fragility and value of life; seeing loved ones at risk can feel physically painful. It is easy for you to see the importance of life for strangers and even enemies; whatever your spiritual beliefs it is hard to escape the knowledge that once ended a life can never be regained. If you are human, you feel numbed to grief, sorrow, and suffering, and may experience moments of intense introspection. You may lose all interest in the outside world for a time, focusing entirely on your own feelings and thoughts.',
    mechEffect: 'If you are an orc and you have the magician skill, you can swift cast either Venom or Purify once without expending personal mana or crystal mana within 10 seconds. You do not need to be able to cast either spell to benefit from this effect. If you are a human, or an orc who does not have the magician skill, the potion has no mechanical effect.',
    materials: {bladeroot: 1, vervain: 1, ilium: 1},
    total: 0,
  },
  {
    name: 'Tender\'s Path',
    rpEffect: 'If you are an orc, you feel invigorated by the bonds of connection to your closest supporters. You are keenly aware of the connections you share with others, and how they effect your life. it is easy to become overwhelmed by an awareness of your place in the world. If you are human, you initially feel exhilarated and full of energy, each new experience is incredibly exciting. This quickly becomes overwhelming, making it hard to speak coherently or focus on anything for more than a few moments.',
    mechEffect: 'If you are an orc and you have the magician skill, you can swift cast either Heal or Empower once without expending personal mana or crystal mana within 10 seconds. You do not need to be able to cast either spell to benefit from this effect. If you are a human, or an orc who does not have the magician skill, the potion has no mechanical effect.',
    materials: {vervain: 1, ilium: 1},
    total: 0,
  },
  {
    name: 'Clodden Earth',
    rpEffect: 'If you are an orc, you become aware of a reservoir of magical power that lies just out of reach. If you push yourself, if you can gather sufficient power, you could achieve anything, change anything, create anything. If you are human, you are vividly reminded of times when you feel you failed yourself or others, and times when other people let you down. It is easy to feel guilty, or lash out at others, but the idea that anyone might be able to make amends for their mistakes feels alien and naive.If you are an orc, you feel a surge of conviction of your past actions; you are strongly aware of the voices of those ancestors that encourage you to strengthen yourself or improve your status, urging you to surpass what you have achieved so far. If you are a human, you feel a dizzying sense of euphoria that slowly builds. At the same time you feel your senses becoming keener until any strong sensory stimulation becomes almost painful.',
    mechEffect: 'If you are an orc with the magician skill, you gain two additional personal mana. Whether you are a magician or not, this counts as a source of spiritual strength to overcome roleplaying effects. If you are a human, the potion has no mechanical effect. The effects - mechanical and roleplaying - last until the end of the next skirmish, quest, or battle, or until sunrise, whichever comes first. This is a tonic; the effect of any other tonic you have drunk immediately ends.',
    materials: {roseweald: 2, vervain: 1, ilium: 1},
    total: 0,
  },
  {
    name: 'The Assassin\'s Gate',
    rpEffect: '',
    mechEffect: '',
    materials: {},
    total: 0,
  },
  {
    name: 'The Black Gate',
    rpEffect: 'You feel dizzy and enervated. Over the next fifteen minutes you become increasingly confused, suffering random aches and pains and a growing awareness of your own death. You may occasionally hallucinate that people around you are friends, loved ones or dead relatives.',
    mechEffect: 'You are immediately affected by weakness which cannot be removed until the poison is cured. After ten minutes you can no longer move under your own power and cannot attack, defend yourself or use any abilities or items. At the end of thirty minutes you suffer an agonising seizure and die.',
    materials: {bladeroot: 4, marrowort: 3, vervain: 3},
    total: 10,
  },
  {
    name: 'The Crimson Gate',
    rpEffect: 'You feel very warm and thirsty, quickly developing a raging fever. Over the next fifteen minutes you begin to suffer agonising pain in your joints and muscles, and begin to cough up blood, You have difficulty breathing, and a growing awareness of your own death. You begin to bleed from the eyes and nose.',
    mechEffect: 'You are immediately affected by venom which cannot be removed until the poison is cured. After ten minutes you can no longer move under your own power and cannot attack, defend yourself or use any abilities or items. At the end of thirty minutes you die, either drowning on your own blood or from massive internal haemorrhaging.',
    materials: {cerulean: 3, roseweald: 4, vervain: 3},
    total: 10,
  },
  {
    name: 'The Silver Key',
    rpEffect: 'You begin to cough uncontrollably, and after a few moments will vomit until your stomach is empty. You may lose consciousness. Over the next five minutes the symptoms of either The Black Gate or The Crimson Gate quickly recede.',
    mechEffect: 'Removes the effect of either or both of The Black Gate or The Crimson Gate. The weakness and venom effects need to be removed separately. If you are not poisoned, you are reduced to 0 hits by this unpleasant preparation.',
    materials: {bladeroot: 4, cerulean: 1, roseweald: 4, marrowort: 4, vervain: 2},
    total: 15,
  },
  {
    name: 'The Last Resort',
    rpEffect: '',
    mechEffect: '',
    materials: {},
    total: 0,
  },
  {
    name: 'Watery Grave',
    rpEffect: 'You feel nauseous and unwell. Over the next fifteen minutes you feel dehydrated and suffer stabbing stomach pains and vomiting. Your bowel movements are voluminous and watery. Your breathing becomes laboured.',
    mechEffect: 'You are immediately affected by WEAKNESS that cannot be removed until the poison is cured. After ten minutes your blood is viscous and foul smelling and your bleed time is increased by three minutes. At the end of thirty minutes your organs collapse leading to a fatal collapse.',
    materials: {bladeroot: 4, cerulean: 2, marrowort: 2, vervain: 2},
    total: 10,
  },
  {
    name: 'Python\'s Hug',
    rpEffect: 'You feel warm and unwell. After five minutes, you suffer a nosebleed, headache, and abdominal pain. After fifteen minutes you are enervated and feverish and barely able to move, feeling as if your guts are twisting inside you.',
    mechEffect: 'After fifteen minutes you are unable to move unaided, attack, defend, or use any skill or magical item unless it explicitly says that it can be used while dying. You may be fed a potion by another character. After thirty minutes, your organs rupture bloodily leading to a painful death.',
    materials: {bladeroot: 2, roseweald: 4, marrowort: 2, vervain: 2},
    total: 10,
  },
  {
    name: 'Restless Slumber',
    rpEffect: 'You experience a powerful chill and over the next few minutes lose consciousness. Over the next five minutes the symptoms of either watery grave or python\'s hug poisons quickly recede.',
    mechEffect: 'Removes the effect of either or both Watery Grave and Python\'s Hug. You are left subject to both venom and weakness, regardless. If you were not poisoned, you are weakened and venomed by this unpleasant preparation.',
    materials: {bladeroot: 5, roseweald: 5, vervain: 5},
    total: 15,
  },
  {
    name: 'Hooded Misery',
    rpEffect: 'This vile tasting liquid causes you to feel nauseous and unwell for several minutes.',
    mechEffect: 'If you have drunk this vile tasting liquid, you should show this lammy to a referee as soon as possible.',
    materials: {bladeroot: 4, cerulean: 1, marrowort: 1, vervain: 1},
    total: 7,
  },
  {
    name: 'The Winter Moon',
    rpEffect: '',
    mechEffect: '',
    materials: {},
    total: 0,
  },
  {
    name: 'Virus Lunarae',
    rpEffect: 'You feel a growing chill spreading through your body. Over the next fifteen minutes you become increasingly cold and numb; shivering despite all efforts to keep you warm. You lose all sensation in your extremities, and eventually are incapable of feeling any physical sensation or holding anything in your numb fingers. You also become increasingly incoherent, and will tend to babble incomprehensibly as the symptoms worsen.',
    mechEffect: 'You are immediately affected by weakness which cannot be removed until the poison is cured. After ten minutes you can no longer move under your own power and cannot attack, defend yourself or use any abilities or items. At the end of thirty minutes you slip into a coma from which you will never recover. A few minutes after that, you reanimate as a flesh-hungry zombie bent on killing and devouring the living.',
    materials: {bladeroot: 2, cerulean: 3, marrowort: 3, vervain: 2},
    total: 10,
  },
  {
    name: 'Hunger of the Wolf',
    rpEffect: 'You feel a growing heat spreading through your body. Over the next fifteen minutes you become extremely short tempered, often incoherent with rage, and lash out at anyone who annoys you. Your growing rage makes it harder and harder for you to concentrate; you begin to hear voices urging you to kill everyone around you.',
    mechEffect: 'You are immediately affected by venom which cannot be removed until the poison is cured. After ten minutes you can no longer communicate coherently with others, and become extremely violent. After thirty minutes you may choose to either enter a killing frenzy or suffer a fatal brain haemorrhage. You will never recover from this state.',
    materials: {bladeroot: 2, roseweald: 4, vervain: 4},
    total: 10,
  },
  {
    name: 'Feast for Crows',
    rpEffect: 'You are overwhelmed by alternating burning fever and freezing numbness that completely incapacitates you. You may lose consciousness, and suffer painful convulsions. Over the next five minutes the symptoms of either Virus Lunarae or Hunger of the Wolf quickly recede.',
    mechEffect: 'Removes the effect of either or both of Virus Lunarae or Hunger of the Wolf. The weakness and venom effects need to be removed separately. If you are not poisoned, you are reduced to 0 hits by this unpleasant preparation.',
    materials: {bladeroot: 3, cerulean: 4, roseweald: 3, marrowort: 4, vervain: 1},
    total: 15,
  },
  {
    name: 'Tisanes of the Labyrinth',
    rpEffect: '',
    mechEffect: '',
    materials: {},
    total: 0,
  },
  {
    name: 'Usher\'s Decoction',
    rpEffect: 'Until you next perform or participate in a ceremony, and for a short time afterward, you feel remarkably centred. If you are dedicated to a virtue, you feel a strong urge to take action in line with that virtue. If not, you feel a strong urge to take action in keeping with your personal philosophy. The night after drinking this potion you will have particularly vivid dreams.',
    mechEffect: 'The next time you perform or participate in a ceremony of anointing, consecration, hallow, exorcism, excommunication or testimony the effect is one rank higher than normal. You must possess the appropriate skill to take part in the ceremony. The effects last for ten minutes or until you next perform a religious ceremony. This is a tonic; the effect of any other tonic you have drunk immediately ends.',
    materials: {roseweald: 1, vervain: 1, liao: 1},
    total: 3,
  },
  {
    name: 'Waywalker\'s Suffusion',
    rpEffect: 'Until you next use a priest skill, and for a short time afterward, you are aware of unseen presences as if you are at the centre of an unseen crowd. Occasionally you hear distant muttering or occasionally a comprehensible word or fragment of a sentence.',
    mechEffect: 'The next time you perform or participate in a ceremony of anointing, consecration, hallow, exorcism, excommunication or testimony the effect is two ranks higher than normal. You must possess the appropriate skill to take part in the ceremony. The effects last for ten minutes or until you next perform a religious ceremony. This is a tonic; the effect of any other tonic you have drunk immediately ends.',
    materials: {cerulean: 2, marrowort: 2, vervain: 1, liao: 2},
    total: 7,
  },
  {
    name: 'Shadowcrow Infusion',
    rpEffect: 'Inhaling this infusion causes a momentary anguish, like the sudden separation from a loved one, but there are no other immediate effects.',
    mechEffect: 'Inhaling the steam from this infusion causes your aura to become impossible to read with the insight ceremony or similar effects. You are also unable to make use of liao, true liao, or any religious skill. The effects last until the next sunrise. If you are human, any time you sleep under the influence of the potion, you either do not dream or do not remember your dreams. This is a tonic; the effect of any other tonic you have drunk immediately ends.',
    materials: {marrowort: 1, liao: 1},
    total: 2,
  },
  {
    name: 'Tonics of the Deep Forest',
    rpEffect: '',
    mechEffect: '',
    materials: {},
    total: 0,
  },
  {
    name: 'Oakenhide Tonic',
    rpEffect: 'You feel very confident in your ability to survive dangerous situations.',
    mechEffect: 'You gain an additional rank of endurance until the next sunrise. This is a tonic; the effect of any other tonic you have drunk immediately ends.',
    materials: {bladeroot: 1, vervain: 1},
    total: 2,
  },
  {
    name: 'Winterskin Tonic',
    rpEffect: 'You feel distanced from your emotions, as if they were being experienced by someone else.',
    mechEffect: 'You gain two additional ranks of endurance until the next sunrise. This is a tonic; the effect of any other tonic you have drunk immediately ends.',
    materials: {bladeroot: 1, cerulean: 2, vervain: 1},
    total: 4,
  },
  {
    name: 'Ironblood Tonic',
    rpEffect: 'You find it very hard to care about the feelings of other people, and tend to take the most expedient course of action regardless of who it might hurt.',
    mechEffect: 'You gain three additional ranks of endurance until the next sunrise. This is a tonic; the effect of any other tonic you have drunk immediately ends.',
    materials: {bladeroot: 1, cerulean: 2, marrowort: 3, vervain: 2},
    total: 8,
  },
  {
    name: 'Tonics of the Open Sky',
    rpEffect: '',
    mechEffect: '',
    materials: {},
    total: 0,
  },
  {
    name: 'Tonic of Sunlit Glass',
    rpEffect: 'You feel a sudden burst of optimism and a rush of positive emotions; you are reminded of past triumphs, hopes and dreams.',
    mechEffect: 'You gain an additional rank of fortitude until the next sunrise. This is a tonic; the effect of any other tonic you have drunk immediately ends.',
    materials: {cerulean: 1, roseweald: 1},
    total: 2,
  },
  {
    name: 'Tonic of Surging Flame',
    rpEffect: 'Warmth spreads from your stomach to your entire body, and persists for the duration of the effect. It brings with it feelings of absolute confidence in your ability to survive no matter what happens. You find it hard to remember that risky behaviour might result in permanent injury or death.',
    mechEffect: 'Once today you may use the unstoppable skill as if you know it without spending hero points. The effect remains until used or until the next sunrise. This is a tonic; the effect of any other tonic you have drunk immediately ends.',
    materials: {cerulean: 1, roseweald: 2, vervain: 2},
    total: 5,
  },
  {
    name: 'Tonic of the Distant Shore',
    rpEffect: 'You feel a sudden burst of optimism and renewed hope; feelings of worry, doubt and uncertainty are banished.',
    mechEffect: 'You gain an additional three ranks of fortitude until the next sunrise. This is a tonic; the effect of any other tonic you have drunk immediately ends.',
    materials: {cerulean: 1, roseweald: 2, marrowort: 2},
    total: 5,
  },
  {
    name: 'Tinctures of True Eminence',
    rpEffect: '',
    mechEffect: '',
    materials: {},
    total: 0,
  },
  {
    name: 'Dragon\'s Blood',
    rpEffect: 'You are filled with personal pride and self-assurance. Any contradiction or lack of respect is profoundly annoying, and you find it difficult to tolerate mockery, insolence or being treated as if you are unimportant.',
    mechEffect: 'If you possess the Summer lore skill then you gain one additional effective rank to the next Summer ritual that you perform within ten minutes, subject to the normal rules for effective skill. This is a tonic; the effect of any other tonic you have drunk immediately ends.',
    materials: {cerulean: 2, roseweald: 1, vervain: 2, mana: 1},
    total: 6,
  },
  {
    name: 'Goldencrown',
    rpEffect: 'You feel a strong urge to take charge of any situation you find yourself in. Filled with pride and self-confidence, people who disagree with you or disrespect you make you exceptionally angry. Whatever you are doing, you very much want to be the centre of attention.',
    mechEffect: 'If you possess the Summer lore skill then you can use up to 3 personal mana as if it were crystal mana on the next Summer ritual that you perform within ten minutes.',
    materials: {bladeroot: 1, cerulean: 3, roseweald: 2, marrowort: 1, vervain: 1},
    total: 8,
  },
  {
    name: 'Firewine',
    rpEffect: 'You experience a rush of heat that flows down your throat and boils in your stomach. When you feel thwarted, belittled, or wronged you find it hard to avoid becoming enraged. If you are actually insulted, disrespected, or threatened you experience an urge to respond violently.',
    mechEffect: 'If you possess the Summer lore skill then you gain three additional ranks to the next Summer ritual that you perform within ten minutes, subject to the normal rules for effective skill. This is a tonic; the effect of any other tonic you have drunk immediately ends.',
    materials: {cerulean: 1, roseweald: 3, vervain: 3, mana: 1, ilium: 1},
    total: 9,
  },
  {
    name: 'Unguents of Falling Leaves',
    rpEffect: '',
    mechEffect: '',
    materials: {},
    total: 0,
  },
  {
    name: 'Bronze Spider Balsam',
    rpEffect: 'You are driven to match wits with those around you, and try to gain influence over them. You become acutely aware of anyone who owes you a favour, or to whom you in turn might owe a favour.',
    mechEffect: 'If you possess the Autumn lore skill then you gain one additional effective rank to the next Autumn ritual that you perform within ten minutes, subject to the normal rules for effective skill. This is a tonic; the effect of any other tonic you have drunk immediately ends.',
    materials: {cerulean: 2, marrowort: 2, vervain: 1, mana: 1},
    total: 6,
  },
  {
    name: 'Leaden Quicksilver',
    rpEffect: 'You become highly motivated to pursue and achieve your goals, whatever they may be. Anything that stands in the way of your success is an obstacle to be overcome, although you feel an urge to avoid personal physical confrontation. Other people should follow your advice because you alone know what is best for them. Anyone who refuses to heed your suggestions is probably plotting against you.',
    mechEffect: 'If you possess the Autumn lore skill then you can use up to 3 personal mana as if it were crystal mana on the next Autumn ritual that you perform within ten minutes.',
    materials: {bladeroot: 1, cerulean: 3, roseweald: 1, marrowort: 2, vervain: 1},
    total: 8,
  },
  {
    name: 'Essence of Verdigris',
    rpEffect: 'You feel an urge to test your skills against others. It is easy to become contrary and stubborn, to try and force people into competing with you. Only the competition matters - winning or losing is irrelevant.',
    mechEffect: 'If you possess the Autumn lore skill then you gain three additional ranks to the next Autumn ritual that you perform within ten minutes, subject to the normal rules for effective skill. This is a tonic; the effect of any other tonic you have drunk immediately ends.',
    materials: {cerulean: 3, marrowort: 3, vervain: 1, mana: 1, ilium: 1},
    total: 9,
  },
  {
    name: 'Unshackled Gift',
    rpEffect: '',
    mechEffect: '',
    materials: {},
    total: 0,
  },
  {
    name: 'Ancestor’s Word',
    rpEffect: 'You feel a surge of physical aggression building. You are strongly aware of the voices of your ancestors, urging you to fight and take joy in battle. If you are human you feel dizzy, and a burning pain spreads through your body.',
    mechEffect: 'If you are a human, you become subject to VENOM and the potion has no other effect. If you are an orc, you gain an additional hero point. In addition, this counts as a source of spiritual strength to overcome roleplaying effects. The effects last until the end of the next skirmish, battle, or quest. This is a tonic; the effect of any other tonic you have drunk immediately ends.',
    materials: {roseweald: 2, vervain: 1},
    total: 3,
  },
  {
    name: 'Legionnaire’s Will',
    rpEffect: 'If you are human you feel a sudden crippling fear and confusion. If you are an orc you feel a sudden bond of connection to those you trust. You are strongly aware of the voices of your ancestors, urging you to revel in the company of other orcs.',
    mechEffect: 'If you are a human, you become subject to VENOM and the potion has no other effect. If you are an orc, you gain two additional hero points. In addition, this counts as a source of spiritual strength to overcome roleplaying effects. The effects last until the end of the next skirmish, battle, or quest. This is a tonic; the effect of any other tonic you have drunk immediately ends.',
    materials: {roseweald: 3, marrowort: 1, vervain: 1},
    total: 5,
  },
  {
    name: 'Indomitable Might',
    rpEffect: 'If you are human you feel a sudden vertigo and lose your balance. If you are an orc, you are filled with the certainty that you are not alone. You are strongly aware of the voice of an ancestor, urging you to survive no matter the cost.',
    mechEffect: 'If you are a human, you become subject to WEAKNESS and the potion has no other effect. If you are an orc, you gain the ability to use the Unstoppable skill as if you know it. The effects last until the end of the next skirmish, battle, or quest. This is a tonic; the effect of any other tonic you have drunk immediately ends.',
    materials: {roseweald: 1, marrowort: 2, vervain: 2},
    total: 5,
  },
  {
    name: 'Skar\'s Strength',
    rpEffect: 'If you are human you feel a sudden crippling fear and confusion. If you are an orc, you feel a sense of your own power surge through you. You are strongly aware of the voices of your ancestors, urging you to take the lead.',
    mechEffect: 'If you are a human, you become subject to VENOM and the potion has no other effect. If you are an orc, you gain the ability to use the Cleaving Strike, Mighty Strikedown, and Mortal Blow skills as if you know them. The effects last until the end of the next skirmish, battle, or quest. This is a tonic; the effect of any other tonic you have drunk immediately ends.',
    materials: {bladeroot: 1, cerulean: 1, roseweald: 3, marrowort: 2, vervain: 2},
    total: 9,
  },
];
