export type RitualRealm = 'Spring' | 'Summer' | 'Autumn' | 'Winter' | 'Day' | 'Night' | 'Special';

export interface Ritual {
  name: string;
  realm: RitualRealm;
  effect: string;
  mastered: string;
}

export const REALM_COLORS: Record<RitualRealm, { bg: string; text: string; border: string }> = {
  Spring:  { bg: 'rgba(109,212,126,0.15)', text: '#6dd47e', border: 'rgba(109,212,126,0.4)' },
  Summer:  { bg: 'rgba(231,180,50,0.15)',  text: '#e7b432', border: 'rgba(231,180,50,0.4)' },
  Autumn:  { bg: 'rgba(212,130,50,0.15)',  text: '#d48232', border: 'rgba(212,130,50,0.4)' },
  Winter:  { bg: 'rgba(100,160,220,0.15)', text: '#6ca0dc', border: 'rgba(100,160,220,0.4)' },
  Day:     { bg: 'rgba(255,230,100,0.15)', text: '#ffe664', border: 'rgba(255,230,100,0.4)' },
  Night:   { bg: 'rgba(160,100,220,0.15)', text: '#a064dc', border: 'rgba(160,100,220,0.4)' },
  Special: { bg: 'rgba(231,110,181,0.15)', text: '#e76eb5', border: 'rgba(231,110,181,0.4)' },
};

export const RITUAL_REALM_ORDER: RitualRealm[] = ['Spring', 'Summer', 'Autumn', 'Winter', 'Day', 'Night', 'Special'];

// 286 rituals from Empire_Magic_Reference.xlsx
export const RITUALS_CATALOGUE: Ritual[] = [
  { name: 'Aid Once More', realm: 'Spring', effect: 'Allows a target to use a heroic skill they have already spent hero points on again.', mastered: 'Formulaic (Spring Lore)' },
  { name: 'Anathemic Call of Bug and Briar', realm: 'Spring', effect: 'Curse. Causes creeping vegetation to entangle and harm a target.', mastered: 'Formulaic (Spring Lore)' },
  { name: 'Blessing of New Spring', realm: 'Spring', effect: 'Enchantment that boosts the yield or production of a personal resource.', mastered: 'Formulaic (Spring Lore)' },
  { name: 'Blood of the Hydra', realm: 'Spring', effect: 'Powerful healing enchantment; target regenerates hits rapidly.', mastered: 'Formulaic (Spring Lore)' },
  { name: 'Call Down Lightning\'s Wrath', realm: 'Spring', effect: 'Battlefield ritual; calls lightning strikes against enemies.', mastered: 'Formulaic (Spring Lore)' },
  { name: 'Churning Cauldron of Bravash', realm: 'Spring', effect: 'Battlefield ritual; poisons a large area or enemy force.', mastered: 'Formulaic (Spring Lore)' },
  { name: 'Coil of the Black Leech', realm: 'Spring', effect: 'Curse. Drains hero points or personal mana from target over time.', mastered: 'Formulaic (Spring Lore)' },
  { name: 'Dance of Navarr and Thorn', realm: 'Spring', effect: 'Navarr-associated ritual; strengthens striding or steading bonds.', mastered: 'Formulaic (Spring Lore)' },
  { name: 'Fan the Flame of New Life', realm: 'Spring', effect: 'Healing; restores a character from dying or near-death state.', mastered: 'Formulaic (Spring Lore)' },
  { name: 'Fetid Breath of Teeming Plague', realm: 'Spring', effect: 'Curse. Spreads a magical disease through a target group.', mastered: 'Formulaic (Spring Lore)' },
  { name: 'Fight Tooth and Nail', realm: 'Spring', effect: 'Enchantment granting CLEAVE and IMPALE calls to an individual.', mastered: 'Formulaic (Spring Lore)' },
  { name: 'Fire in the Blood', realm: 'Spring', effect: 'Enchantment granting the VENOM call on weapons.', mastered: 'Formulaic (Spring Lore)' },
  { name: 'Flame and the Flood', realm: 'Spring', effect: 'Battlefield ritual; causes environmental chaos with fire and water.', mastered: 'Formulaic (Spring Lore)' },
  { name: 'Foam and Spittle of the Furious Sea', realm: 'Spring', effect: 'Battlefield ritual; creates area of churning water/mud to slow enemies.', mastered: 'Formulaic (Spring Lore)' },
  { name: 'Fountain of Life', realm: 'Spring', effect: 'Area healing ritual; restores hits to multiple targets.', mastered: 'Formulaic (Spring Lore)' },
  { name: 'Hallow of the Green World', realm: 'Spring', effect: 'Enchants a territory to be more fertile; boosts Herb Gardens.', mastered: 'Formulaic (Spring Lore)' },
  { name: 'Naeve\'s Twisting Blight', realm: 'Spring', effect: 'Curse on a territory; reduces production of herb gardens.', mastered: 'Formulaic (Spring Lore)' },
  { name: 'Rampant Growth', realm: 'Spring', effect: 'Boosts production of a Forest or Herb Garden personal resource.', mastered: 'Formulaic (Spring Lore)' },
  { name: 'Regrow the Land\'s Heart', realm: 'Spring', effect: 'Removes a curse or blight from a territory.', mastered: 'Formulaic (Spring Lore)' },
  { name: 'Rising Roots that Rend Stone', realm: 'Spring', effect: 'Battlefield ritual; creates difficult terrain with roots and vines.', mastered: 'Formulaic (Spring Lore)' },
  { name: 'Rivers of Life', realm: 'Spring', effect: 'Powerful area healing; regenerates hits for all targets over time.', mastered: 'Formulaic (Spring Lore)' },
  { name: 'Ruthless Vigilance, Healthy Crop', realm: 'Spring', effect: 'Protects a personal resource from enemy curses.', mastered: 'Formulaic (Spring Lore)' },
  { name: 'Skin of Bark, Blood of Amber', realm: 'Spring', effect: 'Enchantment granting extra hits and natural armour.', mastered: 'Formulaic (Spring Lore)' },
  { name: 'Swift Leaping Hare', realm: 'Spring', effect: 'Enchantment granting SPRINT ability to a target.', mastered: 'Formulaic (Spring Lore)' },
  { name: 'Thunderous Tread of the Trees', realm: 'Spring', effect: 'Battlefield ritual; awakens trees/vegetation to attack enemies.', mastered: 'Formulaic (Spring Lore)' },
  { name: 'Unending Cascade of Blood\'s Fire', realm: 'Spring', effect: 'Enchantment on a weapon; repeated VENOM calls.', mastered: 'Formulaic (Spring Lore)' },
  { name: 'Unleash the Beasts Within', realm: 'Spring', effect: 'Enchantment granting CLEAVE, IMPALE and extra endurance to a group.', mastered: 'Formulaic (Spring Lore)' },
  { name: 'Verdant Bounty of the Twilight Bayou', realm: 'Spring', effect: 'Boosts herb garden production significantly.', mastered: 'Formulaic (Spring Lore)' },
  { name: 'Wither the Seed', realm: 'Spring', effect: 'Curse; reduces production of a personal resource.', mastered: 'Formulaic (Spring Lore)' },
  { name: 'Woven Strands of Life', realm: 'Spring', effect: 'Mass healing; restores full hits to multiple characters.', mastered: 'Formulaic (Spring Lore)' },
  { name: 'Alignment of Mind and Blade', realm: 'Summer', effect: 'Enchantment; grants an additional hero point to a fighter.', mastered: 'Formulaic (Summer Lore)' },
  { name: 'Arete and the Fields of War', realm: 'Summer', effect: 'Battlefield; boosts fighting ability of an Imperial military unit.', mastered: 'Formulaic (Summer Lore)' },
  { name: 'Aspect of the Mountain', realm: 'Summer', effect: 'Enchantment; target gains ENDURE and extra hits.', mastered: 'Formulaic (Summer Lore)' },
  { name: 'Barked Command of the Iron Serjant', realm: 'Summer', effect: 'Enchantment granting extra hero points to a banner/group.', mastered: 'Formulaic (Summer Lore)' },
  { name: 'Before the Throne of Estavus', realm: 'Summer', effect: 'Allows communication with Estavus, the Forgemistress eternal.', mastered: 'Formulaic (Summer Lore)' },
  { name: 'Brazen Claws of the Lictor', realm: 'Summer', effect: 'Enchantment; calls IMPALE on unarmed strikes.', mastered: 'Formulaic (Summer Lore)' },
  { name: 'Challenge the Iron Duke', realm: 'Summer', effect: 'Allows communication with Barien, the Iron Duke eternal.', mastered: 'Formulaic (Summer Lore)' },
  { name: 'Champions Shining Resolve', realm: 'Summer', effect: 'Enchantment on armour; target ignores the first blow that would take them to 0 hits.', mastered: 'Formulaic (Summer Lore)' },
  { name: 'Clad in Golden Raiment', realm: 'Summer', effect: 'Ritual armour enchantment; provides significant extra protection.', mastered: 'Formulaic (Summer Lore)' },
  { name: 'Crimson Ward of Summer Stars', realm: 'Summer', effect: 'Defensive ward on a location or group; deflects hostile magic.', mastered: 'Formulaic (Summer Lore)' },
  { name: 'Crown of Phoenix Fire', realm: 'Summer', effect: 'Powerful personal enchantment; rises from dying state once.', mastered: 'Formulaic (Summer Lore)' },
  { name: 'Feast of Heroes', realm: 'Summer', effect: 'Restores hero points to a large group; requires a shared meal.', mastered: 'Formulaic (Summer Lore)' },
  { name: 'Glory to the Sovereign', realm: 'Summer', effect: 'Boosts the military effectiveness of an army.', mastered: 'Formulaic (Summer Lore)' },
  { name: 'Golden Ramparts', realm: 'Summer', effect: 'Defensive ritual; fortifies a structure against attack.', mastered: 'Formulaic (Summer Lore)' },
  { name: 'Hammer of Thunder', realm: 'Summer', effect: 'Enchantment on a weapon; calls SUNDER.', mastered: 'Formulaic (Summer Lore)' },
  { name: 'Irresistible Stance of Force and Focus', realm: 'Summer', effect: 'Personal enchantment; grants STRIKEDOWN and STAGGER calls.', mastered: 'Formulaic (Summer Lore)' },
  { name: 'Knights of Glory', realm: 'Summer', effect: 'Enchantment on a group; grants bonus hero points and extra hits.', mastered: 'Formulaic (Summer Lore)' },
  { name: 'Leonine Pavilion', realm: 'Summer', effect: 'Battlefield; creates a mobile fortified position.', mastered: 'Formulaic (Summer Lore)' },
  { name: 'Lions of Phoenix Reach', realm: 'Summer', effect: 'Boosts military power of an Imperial army.', mastered: 'Formulaic (Summer Lore)' },
  { name: 'Mantle of Lordly Might', realm: 'Summer', effect: 'Personal enchantment; grants significant combat buffs.', mastered: 'Formulaic (Summer Lore)' },
  { name: 'Merciless Wrath of the Reaver', realm: 'Summer', effect: 'Enchantment; grants CLEAVE, IMPALE and SUNDER on a weapon.', mastered: 'Formulaic (Summer Lore)' },
  { name: 'Might of the Myrmidon', realm: 'Summer', effect: 'Personal enchantment granting extra hero points and endurance.', mastered: 'Formulaic (Summer Lore)' },
  { name: 'Raise the Standard of War', realm: 'Summer', effect: 'Battlefield; grants a group enhanced fighting capability.', mastered: 'Formulaic (Summer Lore)' },
  { name: 'Ride the Noble Steed', realm: 'Summer', effect: 'Enchantment; grants SPRINT and other mounted benefits.', mastered: 'Formulaic (Summer Lore)' },
  { name: 'Sound of Drums', realm: 'Summer', effect: 'Battlefield ritual; inspires troops and boosts morale/effectiveness.', mastered: 'Formulaic (Summer Lore)' },
  { name: 'Splendid Panoply of Knighthood', realm: 'Summer', effect: 'Armour enchantment; grants significant extra protection.', mastered: 'Formulaic (Summer Lore)' },
  { name: 'Stag Knight\'s Glory', realm: 'Summer', effect: 'Dawn-associated; personal enchantment for questing knights.', mastered: 'Formulaic (Summer Lore)' },
  { name: 'Stalwart Stand on Solid Ground', realm: 'Summer', effect: 'Defensive enchantment; cannot be pushed back or knocked down.', mastered: 'Formulaic (Summer Lore)' },
  { name: 'Stone\'s Unyielding Defiance', realm: 'Summer', effect: 'Personal; target cannot be moved or disarmed.', mastered: 'Formulaic (Summer Lore)' },
  { name: 'Strength of the Bull', realm: 'Summer', effect: 'Enchantment; grants additional CLEAVE calls.', mastered: 'Formulaic (Summer Lore)' },
  { name: 'Strong Ox, Golden Sun', realm: 'Summer', effect: 'Boosts production of a Forest resource.', mastered: 'Formulaic (Summer Lore)' },
  { name: 'Swords in the Noonday Sun', realm: 'Summer', effect: 'Enchantment; grants extra hero points to a group.', mastered: 'Formulaic (Summer Lore)' },
  { name: 'Talon of the Gryphon', realm: 'Summer', effect: 'Weapon enchantment; grants IMPALE calls.', mastered: 'Formulaic (Summer Lore)' },
  { name: 'Tenacity of Jotra', realm: 'Summer', effect: 'Personal enchantment; target cannot be taken below 1 hit once per encounter.', mastered: 'Formulaic (Summer Lore)' },
  { name: 'Thundering Roar of the Lion-bound Horn', realm: 'Summer', effect: 'Battlefield; strikes fear into enemies, reducing their effectiveness.', mastered: 'Formulaic (Summer Lore)' },
  { name: 'Unbreakable Behemoth\'s Strength', realm: 'Summer', effect: 'Powerful personal enchantment; massive combat buffs.', mastered: 'Formulaic (Summer Lore)' },
  { name: 'Unbreakable Spirit, Unbreakable Blades', realm: 'Summer', effect: 'Group enchantment; weapons cannot be shattered.', mastered: 'Formulaic (Summer Lore)' },
  { name: 'Unending Onslaught', realm: 'Summer', effect: 'Battlefield; grants a group repeated use of heroic abilities.', mastered: 'Formulaic (Summer Lore)' },
  { name: 'Vital Strength of the Earth', realm: 'Summer', effect: 'Personal enchantment; restores hits and grants ENDURE.', mastered: 'Formulaic (Summer Lore)' },
  { name: 'A Goblet of Stars', realm: 'Autumn', effect: 'Divination; reveals information about a specific character\'s aura or history.', mastered: 'Formulaic (Autumn Lore)' },
  { name: 'Amalgamation of Silver and Gold', realm: 'Autumn', effect: 'Boosts production of a Mine personal resource.', mastered: 'Formulaic (Autumn Lore)' },
  { name: 'Ambassadorial Gatekeeper', realm: 'Autumn', effect: 'Allows communication with Autumn eternals.', mastered: 'Formulaic (Autumn Lore)' },
  { name: 'Anvil of Estavus', realm: 'Autumn', effect: 'Allows artisan to create superior magic items (schema-like).', mastered: 'Formulaic (Autumn Lore)' },
  { name: 'Balanced Scales of Lann', realm: 'Autumn', effect: 'Creates a binding magical contract between parties.', mastered: 'Formulaic (Autumn Lore)' },
  { name: 'Bells of Silver and Brass', realm: 'Autumn', effect: 'Enchants a business resource to improve income.', mastered: 'Formulaic (Autumn Lore)' },
  { name: 'Bound by Common Cause', realm: 'Autumn', effect: 'Enchantment linking two characters; if one falls, other is warned.', mastered: 'Formulaic (Autumn Lore)' },
  { name: 'Bulging at the Seams', realm: 'Autumn', effect: 'Boosts production of a Forest or Business resource significantly.', mastered: 'Formulaic (Autumn Lore)' },
  { name: 'Chalice of Callidius', realm: 'Autumn', effect: 'Divination ritual; reveals recent history of a person or item.', mastered: 'Formulaic (Autumn Lore)' },
  { name: 'Circle of Gold', realm: 'Autumn', effect: 'Enchantment on a business; significantly boosts income.', mastered: 'Formulaic (Autumn Lore)' },
  { name: 'Combing the Beach', realm: 'Autumn', effect: 'Boosts production of a Fleet personal resource.', mastered: 'Formulaic (Autumn Lore)' },
  { name: 'Conspirator\'s Cloak', realm: 'Autumn', effect: 'Conceals a character\'s magical aura and identity from divination.', mastered: 'Formulaic (Autumn Lore)' },
  { name: 'Delve Deep, Beneath the Mountain', realm: 'Autumn', effect: 'Boosts production of a Mine personal resource.', mastered: 'Formulaic (Autumn Lore)' },
  { name: 'Distillation of Diverse Parts', realm: 'Autumn', effect: 'Combines multiple resources into a more valuable single output.', mastered: 'Formulaic (Autumn Lore)' },
  { name: 'Eight-spoked Wheel', realm: 'Autumn', effect: 'Divination; provides information about the target\'s current status or location.', mastered: 'Formulaic (Autumn Lore)' },
  { name: 'Ephisis\' Scale', realm: 'Autumn', effect: 'Allows communication with Ephisis, eternal of trade.', mastered: 'Formulaic (Autumn Lore)' },
  { name: 'Fallow Fields and Dried Meat', realm: 'Autumn', effect: 'Curse; reduces production of a personal resource.', mastered: 'Formulaic (Autumn Lore)' },
  { name: 'Gathering the Harvest', realm: 'Autumn', effect: 'Boosts production of a Farm personal resource.', mastered: 'Formulaic (Autumn Lore)' },
  { name: 'Gift of the Wily Broker', realm: 'Autumn', effect: 'Enchantment making a character more persuasive in trade and negotiation.', mastered: 'Formulaic (Autumn Lore)' },
  { name: 'Golden Voyage', realm: 'Autumn', effect: 'Boosts production of a Fleet personal resource.', mastered: 'Formulaic (Autumn Lore)' },
  { name: 'Good Green Oak', realm: 'Autumn', effect: 'Boosts production of a Forest personal resource.', mastered: 'Formulaic (Autumn Lore)' },
  { name: 'Hand of the Dhomiro', realm: 'Autumn', effect: 'Brass Coast-associated; boosts a Freeborn business resource.', mastered: 'Formulaic (Autumn Lore)' },
  { name: 'Hand of the Maker', realm: 'Autumn', effect: 'Boosts artisan production; allows creating extra magic items.', mastered: 'Formulaic (Autumn Lore)' },
  { name: 'Horizon\'s Razor Edge', realm: 'Autumn', effect: 'Battlefield; enhances a fleet\'s combat effectiveness.', mastered: 'Formulaic (Autumn Lore)' },
  { name: 'Kimus\' Glaring Eye', realm: 'Autumn', effect: 'Divination; identifies forgeries, lies, or hidden values.', mastered: 'Formulaic (Autumn Lore)' },
  { name: 'Like Water Through Your Fingers', realm: 'Autumn', effect: 'Curse; causes a character\'s resources or money to mysteriously vanish.', mastered: 'Formulaic (Autumn Lore)' },
  { name: 'Lure of Distant Shores', realm: 'Autumn', effect: 'Boosts Fleet production; enchants a ship for greater returns.', mastered: 'Formulaic (Autumn Lore)' },
  { name: 'Madyn\'s Gift', realm: 'Autumn', effect: 'Enchantment; grants extra votes or influence in Conclave.', mastered: 'Formulaic (Autumn Lore)' },
  { name: 'Mantle of the Golden Orator', realm: 'Autumn', effect: 'Enchantment; grants persuasive ability in political contexts.', mastered: 'Formulaic (Autumn Lore)' },
  { name: 'Mark of Fellowship', realm: 'Autumn', effect: 'Marks two characters as bound allies; grants minor mutual benefits.', mastered: 'Formulaic (Autumn Lore)' },
  { name: 'Mark of Ownership', realm: 'Autumn', effect: 'Magically marks an item or resource as belonging to someone.', mastered: 'Formulaic (Autumn Lore)' },
  { name: 'Mirror of Perfection', realm: 'Autumn', effect: 'Divination; reveals the ideal or \'true\' form of a thing or person.', mastered: 'Formulaic (Autumn Lore)' },
  { name: 'Mystic scrolls of Estavus', realm: 'Autumn', effect: 'Creates ritual scrolls that can be used to perform specific rituals.', mastered: 'Formulaic (Autumn Lore)' },
  { name: 'Net of Gossamer Chains', realm: 'Autumn', effect: 'Binding ritual; creates a magical agreement or contract.', mastered: 'Formulaic (Autumn Lore)' },
  { name: 'Peregrine and Ichimos', realm: 'Autumn', effect: 'Allows communication with eternals of Autumn; diplomatic contact.', mastered: 'Formulaic (Autumn Lore)' },
  { name: 'Piranhas Devour the Kraken', realm: 'Autumn', effect: 'Battlefield; disrupts and weakens large enemy forces.', mastered: 'Formulaic (Autumn Lore)' },
  { name: 'Prowess of the Golden Magician', realm: 'Autumn', effect: 'Enchantment on a coven; boosts ritual strength.', mastered: 'Formulaic (Autumn Lore)' },
  { name: 'Retrograde Wheel', realm: 'Autumn', effect: 'Curse; reverses or reduces the production of a resource.', mastered: 'Formulaic (Autumn Lore)' },
  { name: 'Revelation of the Jewel\'s Sparkling Heart', realm: 'Autumn', effect: 'Divination; reveals the true monetary or magical value of an item.', mastered: 'Formulaic (Autumn Lore)' },
  { name: 'Rivers of Gold', realm: 'Autumn', effect: 'Significantly boosts income from a Business resource.', mastered: 'Formulaic (Autumn Lore)' },
  { name: 'Scrivener\'s Bloodmark', realm: 'Autumn', effect: 'Creates a magically binding document that cannot be forged.', mastered: 'Formulaic (Autumn Lore)' },
  { name: 'Secrets of Skilful Artifice', realm: 'Autumn', effect: 'Teaches or enhances artisan skills; allows learning a schema.', mastered: 'Formulaic (Autumn Lore)' },
  { name: 'Shared Mastery of the Magician\'s Guild', realm: 'Autumn', effect: 'Group enchantment; allows sharing of ritual lore within a coven.', mastered: 'Formulaic (Autumn Lore)' },
  { name: 'Sharp Eyes of the Corsair', realm: 'Autumn', effect: 'Brass Coast-associated; grants scouting and intelligence benefits.', mastered: 'Formulaic (Autumn Lore)' },
  { name: 'Silver Tongue of Virtue', realm: 'Autumn', effect: 'Enchantment on a speaker; words are more persuasive and trustworthy.', mastered: 'Formulaic (Autumn Lore)' },
  { name: 'Smooth Hands Shape the World', realm: 'Autumn', effect: 'Personal enchantment; grants advantage in social/political situations.', mastered: 'Formulaic (Autumn Lore)' },
  { name: 'Streams of Silver', realm: 'Autumn', effect: 'Boosts income from a Mine resource.', mastered: 'Formulaic (Autumn Lore)' },
  { name: 'Sum of the Parts', realm: 'Autumn', effect: 'Combines multiple resources to produce a higher-value single output.', mastered: 'Formulaic (Autumn Lore)' },
  { name: 'Sular\'s Promise', realm: 'Autumn', effect: 'Enchants a resource with extra production for one season.', mastered: 'Formulaic (Autumn Lore)' },
  { name: 'Thief\'s Arcane Gambit', realm: 'Autumn', effect: 'Allows theft of magical properties from one item to transfer to another.', mastered: 'Formulaic (Autumn Lore)' },
  { name: 'Ties that Bind', realm: 'Autumn', effect: 'Creates a lasting magical bond between two characters or groups.', mastered: 'Formulaic (Autumn Lore)' },
  { name: 'Treacher\'s Quill', realm: 'Autumn', effect: 'Curses a document so that agreeing to it harms the signer.', mastered: 'Formulaic (Autumn Lore)' },
  { name: 'Why Sulemaine Walked Away From The Baker', realm: 'Autumn', effect: 'Brass Coast-associated; breaks a magical contract or obligation.', mastered: 'Formulaic (Autumn Lore)' },
  { name: 'Wolves of the Hungry Sea', realm: 'Autumn', effect: 'Battlefield; enhances a raiding fleet\'s power.', mastered: 'Formulaic (Autumn Lore)' },
  { name: 'An Echo of Life Remains', realm: 'Winter', effect: 'Allows a dead character to be questioned briefly.', mastered: 'Formulaic (Winter Lore)' },
  { name: 'Bitter Mantle of the Leaden Crown', realm: 'Winter', effect: 'Powerful personal curse; significant debilitating effects.', mastered: 'Formulaic (Winter Lore)' },
  { name: 'Black Iron Blade', realm: 'Winter', effect: 'Weapon enchantment; calls WEAKNESS.', mastered: 'Formulaic (Winter Lore)' },
  { name: 'Blade Bites Back', realm: 'Winter', effect: 'Curse on an individual; injuries they deal are reflected.', mastered: 'Formulaic (Winter Lore)' },
  { name: 'Blood and Salt', realm: 'Winter', effect: 'Oath-binding ritual; breaking the oath causes harm to the breaker.', mastered: 'Formulaic (Winter Lore)' },
  { name: 'Blood-dimmed Tide', realm: 'Winter', effect: 'Battlefield; weakens and curses a large group of enemies.', mastered: 'Formulaic (Winter Lore)' },
  { name: 'Bright Eyes Gleam in the Depths', realm: 'Winter', effect: 'Allows communication with Winter eternals.', mastered: 'Formulaic (Winter Lore)' },
  { name: 'Crumbling Flesh and Withering Limbs', realm: 'Winter', effect: 'Curse; target suffers progressive physical deterioration.', mastered: 'Formulaic (Winter Lore)' },
  { name: 'Curse of Decrepitude', realm: 'Winter', effect: 'Powerful curse causing ageing-like weakness to a target.', mastered: 'Formulaic (Winter Lore)' },
  { name: 'Curse of Gangrenous Flesh', realm: 'Winter', effect: 'Nasty curse; wounds refuse to heal and worsen over time.', mastered: 'Formulaic (Winter Lore)' },
  { name: 'Devastating Scythe of Anguish and Loss', realm: 'Winter', effect: 'Powerful weapon enchantment; calls CLEAVE and extra damage.', mastered: 'Formulaic (Winter Lore)' },
  { name: 'Dripping Echoes of the Fen', realm: 'Winter', effect: 'Divination; gains information from death-touched sources.', mastered: 'Formulaic (Winter Lore)' },
  { name: 'Dreadful Ending', realm: 'Winter', effect: 'Kills a dying character immediately (ending lingering death).', mastered: 'Formulaic (Winter Lore)' },
  { name: 'Frozen Citadel of Cathan Canae', realm: 'Winter', effect: 'Creates an icy stronghold; defensive fortification.', mastered: 'Formulaic (Winter Lore)' },
  { name: 'Gnawing, Endless Hunger', realm: 'Winter', effect: 'Curse; target suffers escalating debilitating hunger effects.', mastered: 'Formulaic (Winter Lore)' },
  { name: 'Hold Back Frozen Hunger', realm: 'Winter', effect: 'Removes or suppresses a Winter curse from a target.', mastered: 'Formulaic (Winter Lore)' },
  { name: 'Hook of the Hoarfrost Guardian', realm: 'Winter', effect: 'Enchantment; grants abilities tied to the Hoarfrost Guardian eternal.', mastered: 'Formulaic (Winter Lore)' },
  { name: 'Howling Despite of the Yawning Maw', realm: 'Winter', effect: 'Powerful curse on a group; weakens and demoralises.', mastered: 'Formulaic (Winter Lore)' },
  { name: 'Hunger of the Draughir', realm: 'Winter', effect: 'Personal enchantment (often Draughir-relevant); boosts endurance at a cost.', mastered: 'Formulaic (Winter Lore)' },
  { name: 'Hungry Grasp of Despair', realm: 'Winter', effect: 'Curse; drains hero points and causes despair.', mastered: 'Formulaic (Winter Lore)' },
  { name: 'Icy Maw Devours the Spark of Essence', realm: 'Winter', effect: 'Powerful ritual stripping magical enchantments from a target.', mastered: 'Formulaic (Winter Lore)' },
  { name: 'Inescapable Chains of Bitter Glass', realm: 'Winter', effect: 'Binding curse; target cannot use heroic abilities.', mastered: 'Formulaic (Winter Lore)' },
  { name: 'Inevitable Collapse into Ruin', realm: 'Winter', effect: 'Curse on a territory or resource; causes progressive destruction.', mastered: 'Formulaic (Winter Lore)' },
  { name: 'Last Breath Echoes', realm: 'Winter', effect: 'Reveals the final moments and words of a dead character.', mastered: 'Formulaic (Winter Lore)' },
  { name: 'Mark of Agramant', realm: 'Winter', effect: 'Marks a character as touched by Agramant; grants and curses.', mastered: 'Formulaic (Winter Lore)' },
  { name: 'Pallid Flesh of the Dead King', realm: 'Winter', effect: 'Powerful personal enchantment; target appears and fights like undead.', mastered: 'Formulaic (Winter Lore)' },
  { name: 'Pakaanan\'s Iron Shutters', realm: 'Winter', effect: 'Defensive ward; blocks communication and passage into a location.', mastered: 'Formulaic (Winter Lore)' },
  { name: 'Quickening Cold Meat', realm: 'Winter', effect: 'Animates a corpse as a temporarily controlled undead servant.', mastered: 'Formulaic (Winter Lore)' },
  { name: 'Ravenous Tongue of Entropy', realm: 'Winter', effect: 'Curse; destroys items or resources over time.', mastered: 'Formulaic (Winter Lore)' },
  { name: 'Remember the Fallen', realm: 'Winter', effect: 'Allows a group to honour and gain strength from their dead.', mastered: 'Formulaic (Winter Lore)' },
  { name: 'Sorin\'s Chastising Touch', realm: 'Winter', effect: 'Curse; causes pain and weakness to target.', mastered: 'Formulaic (Winter Lore)' },
  { name: 'Sorin\'s Rite of Agony', realm: 'Winter', effect: 'Powerful curse inflicting significant ongoing suffering.', mastered: 'Formulaic (Winter Lore)' },
  { name: 'Swan\'s Cruel Wing', realm: 'Winter', effect: 'Curse; drains strength and vigour over time.', mastered: 'Formulaic (Winter Lore)' },
  { name: 'The Flower is Withered on the Stalk', realm: 'Winter', effect: 'Curse reducing a personal resource\'s production to near zero.', mastered: 'Formulaic (Winter Lore)' },
  { name: 'The Grave\'s Treacherous Edge', realm: 'Winter', effect: 'Battlefield; weakens and slows enemies significantly.', mastered: 'Formulaic (Winter Lore)' },
  { name: 'Thirst of the Devourer', realm: 'Winter', effect: 'Powerful curse stripping personal mana and magical ability.', mastered: 'Formulaic (Winter Lore)' },
  { name: 'Touch of Vile Humours', realm: 'Winter', effect: 'Curse inflicting VENOM and WEAKNESS on a target.', mastered: 'Formulaic (Winter Lore)' },
  { name: 'Traitor\'s Fate', realm: 'Winter', effect: 'Curse placed on someone who has broken an oath or betrayed allies.', mastered: 'Formulaic (Winter Lore)' },
  { name: 'Tribute to the Thrice-Cursed Court', realm: 'Winter', effect: 'Allows communication with the Winter Eternals of Sorin\'s Court.', mastered: 'Formulaic (Winter Lore)' },
  { name: 'Vale of Shadows', realm: 'Winter', effect: 'Battlefield; creates area of darkness and fear.', mastered: 'Formulaic (Winter Lore)' },
  { name: 'Vigour of Youth', realm: 'Winter', effect: 'Temporarily reverses debilitations and restores full function.', mastered: 'Formulaic (Winter Lore)' },
  { name: 'Vitality of Rushing Water', realm: 'Winter', effect: 'Powerful healing; restores hits and removes all conditions.', mastered: 'Formulaic (Winter Lore)' },
  { name: 'Ward of the Black Waste', realm: 'Winter', effect: 'Defensive ward against Winter entities and magic.', mastered: 'Formulaic (Winter Lore)' },
  { name: 'Wardens of the Black Waste', realm: 'Winter', effect: 'Calls on Winter wardens for protection against malign entities.', mastered: 'Formulaic (Winter Lore)' },
  { name: 'Whispers through the Black Gate', realm: 'Winter', effect: 'Communication ritual; speaks with the dead.', mastered: 'Formulaic (Winter Lore)' },
  { name: 'Winter\'s Ghosts', realm: 'Winter', effect: 'Battlefield; raises battlefield dead as temporary warriors.', mastered: 'Formulaic (Winter Lore)' },
  { name: 'Withering Touch of Frost', realm: 'Winter', effect: 'Weapon enchantment; calls WEAKNESS and reduces target hits.', mastered: 'Formulaic (Winter Lore)' },
  { name: 'Words of Ending', realm: 'Winter', effect: 'Destroys artefacts, schemata, herbals, and other permanent items permanently.', mastered: 'Formulaic (Winter Lore)' },
  { name: 'A Light That Moves', realm: 'Day', effect: 'Divination; tracks the movement of a target over time.', mastered: 'Formulaic (Day Lore)' },
  { name: 'A Perfect Moment', realm: 'Day', effect: 'Reveals a single true fact about a target, item or situation.', mastered: 'Formulaic (Day Lore)' },
  { name: 'Align the Celestial Net', realm: 'Day', effect: 'Boosts accuracy of astronomancy and divination rituals.', mastered: 'Formulaic (Day Lore)' },
  { name: 'All the World in a Grain of Sand', realm: 'Day', effect: 'Deep divination; reveals broad truths about the world or a territory.', mastered: 'Formulaic (Day Lore)' },
  { name: 'Arcane Mark', realm: 'Day', effect: 'Places a permanent magical mark on an item identifying owner or purpose.', mastered: 'Formulaic (Day Lore)' },
  { name: 'Ascendance of the Highest Mind', realm: 'Day', effect: 'Powerful personal enchantment enhancing mental clarity and knowledge.', mastered: 'Formulaic (Day Lore)' },
  { name: 'Ascetic Star of Atun', realm: 'Day', effect: 'Urizen-associated; enhances a character\'s magical focus.', mastered: 'Formulaic (Day Lore)' },
  { name: 'Celestial Library', realm: 'Day', effect: 'Access vast divination; reveals extensive information on a subject.', mastered: 'Formulaic (Day Lore)' },
  { name: 'Clarity of the Master Strategist', realm: 'Day', effect: 'Military ritual; reveals detailed information about enemy forces.', mastered: 'Formulaic (Day Lore)' },
  { name: 'Clear Counsel of the Everflowing River', realm: 'Day', effect: 'Removes confusion, mind-altering effects and compulsions from a group.', mastered: 'Formulaic (Day Lore)' },
  { name: 'Clear Lens of the Eternal River', realm: 'Day', effect: 'Powerful divination; removes concealment from a subject.', mastered: 'Formulaic (Day Lore)' },
  { name: 'Crystal Clarity of the Rational Soul', realm: 'Day', effect: 'Personal enchantment; protects against mind-affecting magic.', mastered: 'Formulaic (Day Lore)' },
  { name: 'Crystalline Focus of Aesh', realm: 'Day', effect: 'Enchantment on a coven; increases precision of Day rituals.', mastered: 'Formulaic (Day Lore)' },
  { name: 'Eye of the High Places', realm: 'Day', effect: 'Military divination; reveals information about a strategic region.', mastered: 'Formulaic (Day Lore)' },
  { name: 'Eyes of the Hills', realm: 'Day', effect: 'Divination; scries on activities in a territory.', mastered: 'Formulaic (Day Lore)' },
  { name: 'Eyes of the Soul\'s Past', realm: 'Day', effect: 'Divination of a character\'s past deeds and significant events.', mastered: 'Formulaic (Day Lore)' },
  { name: 'Eyes of the Sun and Moon', realm: 'Day', effect: 'Reveals magical enchantments and bonds on a target.', mastered: 'Formulaic (Day Lore)' },
  { name: 'Find the Best Path', realm: 'Day', effect: 'Navigation/strategic ritual; reveals the optimal route for a force.', mastered: 'Formulaic (Day Lore)' },
  { name: 'Gift of Knowledge', realm: 'Day', effect: 'Allows a character to temporarily gain knowledge they don\'t possess.', mastered: 'Formulaic (Day Lore)' },
  { name: 'Gidyon\'s Refrain', realm: 'Day', effect: 'Musical ritual; grants insights and knowledge through song.', mastered: 'Formulaic (Day Lore)' },
  { name: 'Illuminate the Higher Mind', realm: 'Day', effect: 'Powerful personal enchantment; vastly increases magical aptitude.', mastered: 'Formulaic (Day Lore)' },
  { name: 'Incantation\'s Mystic Mask', realm: 'Day', effect: 'Conceals the magical nature and specifics of another ritual.', mastered: 'Formulaic (Day Lore)' },
  { name: 'Judgement of the Magisters', realm: 'Day', effect: 'Authoritative divination ritual; determines truth of a matter.', mastered: 'Formulaic (Day Lore)' },
  { name: 'Netweaver\'s Eye', realm: 'Day', effect: 'Navarr-associated; monitors a network of allies or striding members.', mastered: 'Formulaic (Day Lore)' },
  { name: 'Piercing Light of Revelation', realm: 'Day', effect: 'Strips away illusions and reveals the true nature of things.', mastered: 'Formulaic (Day Lore)' },
  { name: 'Quick Study', realm: 'Day', effect: 'Allows a character to temporarily use a skill they don\'t own.', mastered: 'Formulaic (Day Lore)' },
  { name: 'Revelatory Light of the Empyrean Spheres', realm: 'Day', effect: 'Powerful mass divination; answers a significant question.', mastered: 'Formulaic (Day Lore)' },
  { name: 'Riddle Hides the Reward', realm: 'Day', effect: 'Places a puzzle or test; reward only accessible if solved.', mastered: 'Formulaic (Day Lore)' },
  { name: 'Rule of Risk and Reward', realm: 'Day', effect: 'Enchantment increasing production of a resource with associated risk.', mastered: 'Formulaic (Day Lore)' },
  { name: 'Sign of Aesh', realm: 'Day', effect: 'Urizen-associated; marks a location or person as under Day\'s protection.', mastered: 'Formulaic (Day Lore)' },
  { name: 'Signs and Portents', realm: 'Day', effect: 'Divination; provides visions about current events (same as Goosewhisper Infusion).', mastered: 'Formulaic (Day Lore)' },
  { name: 'Skein of Years', realm: 'Day', effect: 'Reveals the full history of a person, place or item.', mastered: 'Formulaic (Day Lore)' },
  { name: 'Still Waters, Running Deep', realm: 'Day', effect: 'Calms and stabilises a chaotic magical or political situation.', mastered: 'Formulaic (Day Lore)' },
  { name: 'Surcease of Sorrow', realm: 'Day', effect: 'Removes grief, despair and negative emotional roleplaying effects.', mastered: 'Formulaic (Day Lore)' },
  { name: 'The Certainty of Doubt', realm: 'Day', effect: 'Reveals the flaws or weaknesses in a plan or defence.', mastered: 'Formulaic (Day Lore)' },
  { name: 'The Stargazer\'s Astrolabe', realm: 'Day', effect: 'Urizen-associated; sophisticated astronomical divination.', mastered: 'Formulaic (Day Lore)' },
  { name: 'Transcendent Mastery', realm: 'Day', effect: 'Powerful enchantment; dramatically boosts a character\'s mastered skill.', mastered: 'Formulaic (Day Lore)' },
  { name: 'Twist of Moebius', realm: 'Day', effect: 'Paradox ritual; reverses or loops a sequence of events.', mastered: 'Formulaic (Day Lore)' },
  { name: 'Wisdom of the Balanced Blade', realm: 'Day', effect: 'Personal enchantment; grants combat insight and strategic advantage.', mastered: 'Formulaic (Day Lore)' },
  { name: 'An Echo of Songs', realm: 'Night', effect: 'Recovers details of a past ritual or ceremony performed at a location.', mastered: 'Formulaic (Night Lore)' },
  { name: 'Bright Lantern of Ophis', realm: 'Night', effect: 'Allows communication with Ophis, the Wanderer eternal.', mastered: 'Formulaic (Night Lore)' },
  { name: 'Brotherhood of Tian', realm: 'Night', effect: 'Enchantment creating unbreakable bonds between members of a group.', mastered: 'Formulaic (Night Lore)' },
  { name: 'Call Winged Messenger', realm: 'Night', effect: 'Sends a magical message to a known person anywhere in the world.', mastered: 'Formulaic (Night Lore)' },
  { name: 'Carve the Crystal Guardian', realm: 'Night', effect: 'Creates a bound crystal spirit that guards a location or item.', mastered: 'Formulaic (Night Lore)' },
  { name: 'Cast Off The Chain of Memory', realm: 'Night', effect: 'Removes a specific memory or knowledge from a target.', mastered: 'Formulaic (Night Lore)' },
  { name: 'Chamber of Delights', realm: 'Night', effect: 'Creates a magical space for meeting or negotiation; binds attendees.', mastered: 'Formulaic (Night Lore)' },
  { name: 'Chamber of Pallas', realm: 'Night', effect: 'Night ritual allowing private meeting with Autumn/Night eternal Pallas.', mastered: 'Formulaic (Night Lore)' },
  { name: 'Chastise the Foolish', realm: 'Night', effect: 'Curse inflicting embarrassment or social harm on a target.', mastered: 'Formulaic (Night Lore)' },
  { name: 'Chasuble of Majesty', realm: 'Night', effect: 'Enchants vestments to improve religious ceremony effectiveness.', mastered: 'Formulaic (Night Lore)' },
  { name: 'Chimes of Annulment', realm: 'Night', effect: 'Removes magical enchantments from a target or area.', mastered: 'Formulaic (Night Lore)' },
  { name: 'Conclave of Trees and Shadow', realm: 'Night', effect: 'Navarr-associated; communication with deep forest Night entities.', mastered: 'Formulaic (Night Lore)' },
  { name: 'Distil the Serpent\'s Stone', realm: 'Night', effect: 'Creates a potent magical artefact component from rare materials.', mastered: 'Formulaic (Night Lore)' },
  { name: 'Drawing the Penumbral Veil', realm: 'Night', effect: 'Concealment ritual; hides a location, item or group from detection.', mastered: 'Formulaic (Night Lore)' },
  { name: 'Dreams in the Witch House', realm: 'Night', effect: 'Sends a target vivid and potentially instructive dream.', mastered: 'Formulaic (Night Lore)' },
  { name: 'Dreamscape of the Endless Hunt', realm: 'Night', effect: 'Powerful personal enchantment tied to the Endless Hunt eternal.', mastered: 'Formulaic (Night Lore)' },
  { name: 'Emulsion of Lye and Lightning', realm: 'Night', effect: 'Alchemical night ritual; transmutes materials in unusual ways.', mastered: 'Formulaic (Night Lore)' },
  { name: 'Ethereal Courier', realm: 'Night', effect: 'Sends a physical item or written message to a known recipient.', mastered: 'Formulaic (Night Lore)' },
  { name: 'Fire on the Water', realm: 'Night', effect: 'Night battlefield ritual; creates confusion and chaos.', mastered: 'Formulaic (Night Lore)' },
  { name: 'Forest Remains', realm: 'Night', effect: 'Navarr-associated; ritual honouring the forest and ancestors.', mastered: 'Formulaic (Night Lore)' },
  { name: 'Forge the Wooden Fastness', realm: 'Night', effect: 'Creates a magical wooden fortification.', mastered: 'Formulaic (Night Lore)' },
  { name: 'Fountain\'s Bounty', realm: 'Night', effect: 'Boosts production of a herb garden, linked to natural springs.', mastered: 'Formulaic (Night Lore)' },
  { name: 'Freedom of the Soul', realm: 'Night', effect: 'Removes binding contracts, obligations or oaths from a target.', mastered: 'Formulaic (Night Lore)' },
  { name: 'Freezing Brand of Irremais', realm: 'Night', effect: 'Permanently marks a target with a visible magical brand.', mastered: 'Formulaic (Night Lore)' },
  { name: 'From the Mouths of Babes', realm: 'Night', effect: 'Divination; gains prophetic insight from innocence or purity.', mastered: 'Formulaic (Night Lore)' },
  { name: 'Garden of Teth-Anon', realm: 'Night', effect: 'Creates a magical garden producing rare and unusual herbs.', mastered: 'Formulaic (Night Lore)' },
  { name: 'Gardener\'s Wheel', realm: 'Night', effect: 'Seasonal cycle ritual; boosts herb garden production over time.', mastered: 'Formulaic (Night Lore)' },
  { name: 'Gralka\'s Gift to the Lost Seeker', realm: 'Night', effect: 'Provides guidance or information to a lost or confused party.', mastered: 'Formulaic (Night Lore)' },
  { name: 'Guardian Gate', realm: 'Night', effect: 'Creates a mystical gate or portal that only certain individuals can pass.', mastered: 'Formulaic (Night Lore)' },
  { name: 'Hakima\'s Glass', realm: 'Night', effect: 'Brass Coast-associated divination; truth-revealing scrying.', mastered: 'Formulaic (Night Lore)' },
  { name: 'Hearthfire Circle', realm: 'Night', effect: 'Creates a magical safe space; no violence or magic can occur within.', mastered: 'Formulaic (Night Lore)' },
  { name: 'Infant Starts with a Blank Slate', realm: 'Night', effect: 'Removes all magical marks, bonds and histories from a target.', mastered: 'Formulaic (Night Lore)' },
  { name: 'Irrepressible Monkey Spirit', realm: 'Night', effect: 'Night enchantment granting trickster-like magical abilities.', mastered: 'Formulaic (Night Lore)' },
  { name: 'Loosen the Shackles', realm: 'Night', effect: 'Breaks a magical binding or contract forcefully.', mastered: 'Formulaic (Night Lore)' },
  { name: 'Masque of the Blinded Weaver', realm: 'Night', effect: 'Powerful concealment; hides magical nature of all in an area.', mastered: 'Formulaic (Night Lore)' },
  { name: 'Missive for Sadogua', realm: 'Night', effect: 'Allows communication with Sadogua, eternal of the Labyrinth.', mastered: 'Formulaic (Night Lore)' },
  { name: 'Mirror of Perfection', realm: 'Night', effect: 'Shows target an idealised or alternate version of themselves.', mastered: 'Formulaic (Night Lore)' },
  { name: 'Mountain Remembers Its Youth', realm: 'Night', effect: 'Divination of a place; reveals its deep history.', mastered: 'Formulaic (Night Lore)' },
  { name: 'Muffled Oar', realm: 'Night', effect: 'Concealment; allows a group to move without detection.', mastered: 'Formulaic (Night Lore)' },
  { name: 'Petrifying Command of the Tyrant', realm: 'Night', effect: 'Powerful curse; target cannot disobey commands for duration.', mastered: 'Formulaic (Night Lore)' },
  { name: 'Retreat to the White Caves', realm: 'Night', effect: 'Retreat ritual; safely extracts a group from a dangerous situation.', mastered: 'Formulaic (Night Lore)' },
  { name: 'Rhythm of the Tempest', realm: 'Night', effect: 'Musical night ritual; creates magical effects through rhythm.', mastered: 'Formulaic (Night Lore)' },
  { name: 'Rivers Run Red', realm: 'Night', effect: 'Night battlefield ritual; territory curses or floods.', mastered: 'Formulaic (Night Lore)' },
  { name: 'Secrets for the Shadow Courier', realm: 'Night', effect: 'Sends a secret message that only the intended recipient can read.', mastered: 'Formulaic (Night Lore)' },
  { name: 'Secrets of the Empty Heart', realm: 'Night', effect: 'Divination revealing hidden motivations and secrets of a target.', mastered: 'Formulaic (Night Lore)' },
  { name: 'Secrets of the Soul\'s Desire', realm: 'Night', effect: 'Reveals what a target truly wants or fears most.', mastered: 'Formulaic (Night Lore)' },
  { name: 'Shadow of the Bronze Colossus', realm: 'Night', effect: 'Creates a powerful illusory construct used in battle.', mastered: 'Formulaic (Night Lore)' },
  { name: 'Shadowed Glass of Sung', realm: 'Night', effect: 'Creates a magical mirror showing hidden truths.', mastered: 'Formulaic (Night Lore)' },
  { name: 'Sift the Dreamscape\'s Sands', realm: 'Night', effect: 'Divination using dream imagery; vague but wide-ranging information.', mastered: 'Formulaic (Night Lore)' },
  { name: 'Silence of the Bronze Bell', realm: 'Night', effect: 'Ward; prevents magical communication in or out of an area.', mastered: 'Formulaic (Night Lore)' },
  { name: 'Shroud of Mist and Shadow', realm: 'Night', effect: 'Conceals a group; grants stealth in darkness.', mastered: 'Formulaic (Night Lore)' },
  { name: 'Skar\'s Gentle Push', realm: 'Night', effect: 'Subtle Night curse; nudges a target\'s behaviour or decision-making.', mastered: 'Formulaic (Night Lore)' },
  { name: 'Solace of Chimes', realm: 'Night', effect: 'Removes distressing Night effects and calms magical chaos.', mastered: 'Formulaic (Night Lore)' },
  { name: 'Star\'s Mantle', realm: 'Night', effect: 'Personal enchantment providing night-type concealment and trickery.', mastered: 'Formulaic (Night Lore)' },
  { name: 'Sutannir\'s Promise', realm: 'Night', effect: 'Brass Coast-associated; magical entertainment that also scries.', mastered: 'Formulaic (Night Lore)' },
  { name: 'The Crimson Feast', realm: 'Night', effect: 'Night ritual feasting; powerful bonding and debilitating effects.', mastered: 'Formulaic (Night Lore)' },
  { name: 'The Cuckoo\'s Egg', realm: 'Night', effect: 'Subterfuge; plants false information or a false identity.', mastered: 'Formulaic (Night Lore)' },
  { name: 'The Twilight Masquerade', realm: 'Night', effect: 'Creates a masked ball with magical effects and revelations.', mastered: 'Formulaic (Night Lore)' },
  { name: 'There Is No Welcome Here', realm: 'Night', effect: 'Ward; makes a location deeply unsettling and hard to remain in.', mastered: 'Formulaic (Night Lore)' },
  { name: 'Tithe of Bats', realm: 'Night', effect: 'Allows communication with and tribute to certain Night eternals.', mastered: 'Formulaic (Night Lore)' },
  { name: 'Transmogrification of the Soul\'s Echo', realm: 'Night', effect: 'Powerful ritual altering a character\'s fundamental nature.', mastered: 'Formulaic (Night Lore)' },
  { name: 'Turns the Circle', realm: 'Night', effect: 'Breaks or redirects a powerful magical effect.', mastered: 'Formulaic (Night Lore)' },
  { name: 'Unyielding Constitution', realm: 'Night', effect: 'Night personal enchantment granting resistance to all conditions.', mastered: 'Formulaic (Night Lore)' },
  { name: 'Vigour of Youth', realm: 'Night', effect: 'Restores vitality and reverses age-like decline.', mastered: 'Formulaic (Night Lore)' },
  { name: 'Viridian\'s Wildfire Emberstrike', realm: 'Night', effect: 'Weapon enchantment; calls SHATTER.', mastered: 'Formulaic (Night Lore)' },
  { name: 'Wellspring of the High Peak', realm: 'Night', effect: 'Boosts mana production for a coven or mana site.', mastered: 'Formulaic (Night Lore)' },
  { name: 'Whispering Shadow Courtiers', realm: 'Night', effect: 'Night eternal communication; shadow court contacts.', mastered: 'Formulaic (Night Lore)' },
  { name: 'Wind of Mundane Silence', realm: 'Night', effect: 'Strips enchantments and magical items of their power temporarily.', mastered: 'Formulaic (Night Lore)' },
  { name: 'Winds of Fortune', realm: 'Night', effect: 'Night ritual; foresees or nudges future events.', mastered: 'Formulaic (Night Lore)' },
  { name: 'Wondrous Forests of the Night', realm: 'Night', effect: 'Night-based production boost for Forest resources.', mastered: 'Formulaic (Night Lore)' },
  { name: 'Arcane projection', realm: 'Special', effect: 'Unformulated (improvised) ritual; can achieve any effect with sufficient mana.', mastered: 'Requires mastery of all six lores + ref approval' },
  { name: 'Formulaic ritual', realm: 'Special', effect: 'Reference article explaining how formulaic rituals work.', mastered: 'N/A – rules reference' },
  { name: 'Battlefield ritual', realm: 'Special', effect: 'Any ritual performed mid-battle; requires specific ritual text on a card.', mastered: 'Any realm lore' },
  { name: 'Enchantment', realm: 'Special', effect: 'Rules reference for the enchantment type of ritual effect.', mastered: 'N/A – rules reference' },
  { name: 'Curse', realm: 'Special', effect: 'Rules reference for the curse type of ritual effect.', mastered: 'N/A – rules reference' },
  { name: 'Ilium', realm: 'Special', effect: 'Rules on using ilium (the rare mineral) in rituals to create artefacts.', mastered: 'N/A – rules reference' },
];
