export type RitualRealm = 'Spring' | 'Summer' | 'Autumn' | 'Winter' | 'Day' | 'Night' | 'Special';

export interface Ritual {
  name: string;
  realm: RitualRealm;
  effect: string;
  magnitude: number;
  source: 'imperial' | 'urizen';
}

export const REALM_COLORS: Record<RitualRealm, { bg: string; text: string; border: string }> = {
  Spring:  { bg: 'rgba(109,212,126,0.15)', text: '#6dd47e', border: 'rgba(109,212,126,0.4)' },
  Summer:  { bg: 'rgba(231,180,50,0.15)', text: '#e7b432', border: 'rgba(231,180,50,0.4)' },
  Autumn:  { bg: 'rgba(212,130,50,0.15)', text: '#d48232', border: 'rgba(212,130,50,0.4)' },
  Winter:  { bg: 'rgba(100,160,220,0.15)', text: '#6ca0dc', border: 'rgba(100,160,220,0.4)' },
  Day:  { bg: 'rgba(255,230,100,0.15)', text: '#ffe664', border: 'rgba(255,230,100,0.4)' },
  Night:  { bg: 'rgba(160,100,220,0.15)', text: '#a064dc', border: 'rgba(160,100,220,0.4)' },
  Special:  { bg: 'rgba(231,110,181,0.15)', text: '#e76eb5', border: 'rgba(231,110,181,0.4)' },
};

export const RITUAL_REALM_ORDER: RitualRealm[] = ['Spring', 'Summer', 'Autumn', 'Winter', 'Day', 'Night', 'Special'];

// 258 Imperial Lore + 43 Urizen Lore rituals from Dump.xlsx
export const RITUALS_CATALOGUE: Ritual[] = [
  { name: 'Blessing of New Spring', realm: 'Spring', effect: 'Increase wealth gained from a farm for three seasons and serves as a foundation for other farm rituals.', magnitude: 2, source: 'imperial' },
  { name: 'Blood of the Hydra', realm: 'Spring', effect: 'Repairs ruined limbs.', magnitude: 2, source: 'imperial' },
  { name: 'Hands of Sacred Life', realm: 'Spring', effect: 'Heal lost hits.', magnitude: 2, source: 'imperial' },
  { name: 'Turns the Circle', realm: 'Spring', effect: 'Rots a body.', magnitude: 4, source: 'imperial' },
  { name: 'Fan the Flame of New Life', realm: 'Spring', effect: 'Makes a couple fertile.', magnitude: 6, source: 'imperial' },
  { name: 'Hearthfire Circle', realm: 'Spring', effect: 'Provides powerful healing to a patient.', magnitude: 7, source: 'imperial' },
  { name: 'Call Down Lightning\'s Wrath', realm: 'Spring', effect: 'Lets a battle mage call STRIKEDOWN with a staff by casting an offensive spell.', magnitude: 8, source: 'imperial' },
  { name: 'Chirurgeon\'s Healing Touch', realm: 'Spring', effect: 'Target gains two stay with me uses each day for a season.', magnitude: 8, source: 'imperial' },
  { name: 'Churning Cauldron of Bravash', realm: 'Spring', effect: 'Creates new herbs from existing herbs.', magnitude: 8, source: 'imperial' },
  { name: 'Merciless Wrath of the Reaver', realm: 'Spring', effect: 'Adds three ranks to a military unit that takes a raiding action during the next season.', magnitude: 8, source: 'imperial' },
  { name: 'Viridian\'s Wildfire Emberstrike', realm: 'Spring', effect: 'Lets a battlemage call CLEAVE with a staff by casting an offensive spell.', magnitude: 8, source: 'imperial' },
  { name: 'Fountain of Life', realm: 'Spring', effect: 'Target can cast heal, purify and restore limb as if they knew them for a season.', magnitude: 10, source: 'imperial' },
  { name: 'Rampant Growth', realm: 'Spring', effect: 'Grants additional money and herbs to the production of a forest.', magnitude: 10, source: 'imperial' },
  { name: 'Touch of Vile Humours', realm: 'Spring', effect: 'Grants the ability to call VENOM with any weapon or implement once per day.', magnitude: 11, source: 'imperial' },
  { name: 'Blood and Salt', realm: 'Spring', effect: 'Grants five extra ranks to a fleet taking a raiding action.', magnitude: 12, source: 'imperial' },
  { name: 'Madyn\'s Gift', realm: 'Spring', effect: 'Creates new doses of realmsroot', magnitude: 12, source: 'imperial' },
  { name: 'Unending Cascade of Blood\'s Fire', realm: 'Spring', effect: 'Grants a magician the ability to repeatedly use magical venom.', magnitude: 14, source: 'imperial' },
  { name: 'Vitality of Rushing Water', realm: 'Spring', effect: 'Reduces the effectiveness of venom for a season.', magnitude: 14, source: 'imperial' },
  { name: 'Skin of Bark, Blood of Amber', realm: 'Spring', effect: 'Target gains three ranks of endurance for a season.', magnitude: 15, source: 'imperial' },
  { name: 'Anathemic Call of Bug and Briar', realm: 'Spring', effect: 'Curses a target and halves the production of their farm, forest or garden resource for a year.', magnitude: 16, source: 'imperial' },
  { name: 'Irrepressible Monkey Spirit', realm: 'Spring', effect: 'Target gains two unstoppable or relentless uses each day for a season.', magnitude: 17, source: 'imperial' },
  { name: 'Hands of the Healer', realm: 'Spring', effect: 'Target casts heal faster for a season.', magnitude: 19, source: 'imperial' },
  { name: 'Fire in the Blood', realm: 'Spring', effect: 'Grants 1 rank of Spring lore, and additional prowess with venomous rituals for a season, at the cost of lasting venom.', magnitude: 20, source: 'imperial' },
  { name: 'Forest Remains', realm: 'Spring', effect: 'Grants two uses of SHATTER each day with a great weapon, for a season.', magnitude: 22, source: 'imperial' },
  { name: 'Curse of Gangrenous Flesh', realm: 'Spring', effect: 'A year-long curse of venom.', magnitude: 40, source: 'imperial' },
  { name: 'Dance of Navarr and Thorn', realm: 'Spring', effect: 'Extends or repairs trods.', magnitude: 40, source: 'imperial' },
  { name: 'Foam and Spittle of the Furious Sea', realm: 'Spring', effect: 'Curses a coastal territory with terrible storms that harm navies and fleets.', magnitude: 40, source: 'imperial' },
  { name: 'Regrow the Land\'s Heart', realm: 'Spring', effect: 'Replenishes a territory damaged by war or disaster', magnitude: 40, source: 'imperial' },
  { name: 'Thunderous Deluge', realm: 'Spring', effect: 'Curses a territory with catastrophic storms that harm businesses and farms.', magnitude: 46, source: 'imperial' },
  { name: 'Fetid Breath of Teeming Plague', realm: 'Spring', effect: 'Allows the use of an area-of-effect venom call.', magnitude: 50, source: 'imperial' },
  { name: 'Rising Roots that Rend Stone', realm: 'Spring', effect: 'Breaches a fortification on the battlefield.', magnitude: 50, source: 'imperial' },
  { name: 'Rivers of Life', realm: 'Spring', effect: 'Curses a territory halving casualties suffered by campaign armies, navies, and garrisons.', magnitude: 50, source: 'imperial' },
  { name: 'Rivers Run Red', realm: 'Spring', effect: 'Curses a territory doubling casualties suffered by campaign armies, navies, and garrisons.', magnitude: 50, source: 'imperial' },
  { name: 'Mountain Remembers Its Youth', realm: 'Spring', effect: 'Curses a territory with tremors and clouds of poisonous gasses.', magnitude: 60, source: 'imperial' },
  { name: 'Forge the Wooden Fastness', realm: 'Spring', effect: 'Conjures magical wards to defend a region with the forest quality.', magnitude: 80, source: 'imperial' },
  { name: 'Thunderous Tread of the Trees', realm: 'Spring', effect: 'Curses a territory, causing vegetation to become hostile and animate', magnitude: 120, source: 'imperial' },
  { name: 'Hallow of the Green World', realm: 'Spring', effect: 'Enchants the Empire with power drawn from the Spring realm.', magnitude: 210, source: 'imperial' },
  { name: 'Renewed Strength of the New Day', realm: 'Summer', effect: 'Removes weakness condition.', magnitude: 2, source: 'imperial' },
  { name: 'Stag Knight\'s Glory', realm: 'Summer', effect: 'Allows the target to make a single appropriate call with a weapon within the next 10 seconds', magnitude: 2, source: 'imperial' },
  { name: 'Tenacity of Jotra', realm: 'Summer', effect: 'Grants a rank of fortitude for a season.', magnitude: 2, source: 'imperial' },
  { name: 'Hammer of Thunder', realm: 'Summer', effect: 'Grants one use of IMPALE each day for a season with a great weapon.', magnitude: 3, source: 'imperial' },
  { name: 'Strength of the Bull', realm: 'Summer', effect: 'Grants one rank of endurance for a season.', magnitude: 3, source: 'imperial' },
  { name: 'Swan\'s Cruel Wing', realm: 'Summer', effect: 'Grants one use of CLEAVE each day for a season with any weapon.', magnitude: 3, source: 'imperial' },
  { name: 'Swift Leaping Hare', realm: 'Summer', effect: 'Grants one use of STRIKEDOWN each day for a season with a pole-arm.', magnitude: 3, source: 'imperial' },
  { name: 'Strong Ox, Golden Sun', realm: 'Summer', effect: 'Replaces Blessing of New Spring with enhanced production for a farm for two seasons.', magnitude: 4, source: 'imperial' },
  { name: 'Stout Resolve of the Unyielding', realm: 'Summer', effect: 'Suppresses the effects of a traumatic wound until end of battle.', magnitude: 5, source: 'imperial' },
  { name: 'Clad in Golden Raiment', realm: 'Summer', effect: 'Increase fighting force of a military unit by one rank if it takes a campaigning action.', magnitude: 6, source: 'imperial' },
  { name: 'Skar\'s Gentle Push', realm: 'Summer', effect: 'Grant the target the shield skill for the season.', magnitude: 6, source: 'imperial' },
  { name: 'Crimson Ward of Summer Stars', realm: 'Summer', effect: 'Grants two ranks of endurance while in mage armour for a season.', magnitude: 8, source: 'imperial' },
  { name: 'From the Mouths of Babes', realm: 'Summer', effect: 'Sends a message to the eternal Meraud.', magnitude: 8, source: 'imperial' },
  { name: 'Star\'s Mantle', realm: 'Summer', effect: 'Grants a magician a rank of Extra mana', magnitude: 8, source: 'imperial' },
  { name: 'Unbreakable Spirit, Unbreakable Blades', realm: 'Summer', effect: 'Grants ability to mend a weapon, implement or shield once a day for a season.', magnitude: 8, source: 'imperial' },
  { name: 'Vigour of Youth', realm: 'Summer', effect: 'Grants three ranks of fortitude for a season.', magnitude: 9, source: 'imperial' },
  { name: 'Chasuble of Majesty', realm: 'Summer', effect: 'Grants a priest the power to strengthen a ceremony with extra liao for a season.', magnitude: 10, source: 'imperial' },
  { name: 'Feast of Heroes', realm: 'Summer', effect: 'Enchants a military unit to provide five additional ranks if it takes a questing action.', magnitude: 10, source: 'imperial' },
  { name: 'Golden Voyage', realm: 'Summer', effect: 'Grants five extra ranks to a fleet taking a questing action.', magnitude: 10, source: 'imperial' },
  { name: 'Sutannir\'s Promise', realm: 'Summer', effect: 'Grants the ability to restore hero points to a group while in an area consecrated to Courage once each day for a season.', magnitude: 10, source: 'imperial' },
  { name: 'Sound of Drums', realm: 'Summer', effect: 'Grants two uses of unstoppable each day for a season.', magnitude: 11, source: 'imperial' },
  { name: 'Delve Deep, Beneath the Mountain', realm: 'Summer', effect: 'Adds additional ingots and wealth to the production of a mine for a season.', magnitude: 12, source: 'imperial' },
  { name: 'Gidyon\'s Refrain', realm: 'Summer', effect: 'Grants a source of spiritual strength, but only while singing.', magnitude: 12, source: 'imperial' },
  { name: 'Glorious Crown of Enchantment', realm: 'Summer', effect: 'Grants a magician the ability to repeatedly empower their allies.', magnitude: 14, source: 'imperial' },
  { name: 'Splendid Panoply of Knighthood', realm: 'Summer', effect: 'Grants one rank of endurance to a group for a season.', magnitude: 14, source: 'imperial' },
  { name: 'Talon of the Gryphon', realm: 'Summer', effect: 'Grants the ability to spend a hero point to call IMPALE with a one-handed spear.', magnitude: 15, source: 'imperial' },
  { name: 'Champions Shining Resolve', realm: 'Summer', effect: 'Grants two additional hero points for a season.', magnitude: 16, source: 'imperial' },
  { name: 'Devastating Maul of Inga Tarn', realm: 'Summer', effect: 'Grants the ability to spend a hero point to call SHATTER with a great weapon.', magnitude: 20, source: 'imperial' },
  { name: 'Leonine Pavilion', realm: 'Summer', effect: 'Creates roleplay aura encouraging celebration and boasting in an area', magnitude: 20, source: 'imperial' },
  { name: 'Piranhas Devour the Kraken', realm: 'Summer', effect: 'Grants five extra ranks to a fleet taking a campaigning action.', magnitude: 20, source: 'imperial' },
  { name: 'Prowess of the Golden Magician', realm: 'Summer', effect: 'Grants one rank of Summer lore for a season and additional prowess when performing powerful rituals.', magnitude: 20, source: 'imperial' },
  { name: 'Raise the Standard of War', realm: 'Summer', effect: 'Adds five ranks to a military unit that takes a campaigning action during the next season.', magnitude: 20, source: 'imperial' },
  { name: 'Mantle of Lordly Might', realm: 'Summer', effect: 'Grants three uses of Stay with Me or Get it Together every day for a season.', magnitude: 22, source: 'imperial' },
  { name: 'Mantle of the Kriegszauberer', realm: 'Summer', effect: 'Enchants a battle mage with three ranks of endurance and four personal mana while wearing mage armour', magnitude: 22, source: 'imperial' },
  { name: 'Glory to the Sovereign', realm: 'Summer', effect: 'Grants two ranks of endurance and 2 uses of CLEAVE each day for a season.', magnitude: 24, source: 'imperial' },
  { name: 'Lions of Phoenix Reach', realm: 'Summer', effect: 'This enchantment summons a military unit of summer warriors by using the power of a mana site.', magnitude: 24, source: 'imperial' },
  { name: 'Challenge the Iron Duke', realm: 'Summer', effect: 'Binds the eternal Barien to provide a challenge and a reward.', magnitude: 30, source: 'imperial' },
  { name: 'Remember the Fallen', realm: 'Summer', effect: 'Allows members of a small group to make calls in combat.', magnitude: 32, source: 'imperial' },
  { name: 'Unbreakable Behemoth\'s Strength', realm: 'Summer', effect: 'Grants five ranks of endurance for a season.', magnitude: 36, source: 'imperial' },
  { name: 'Might of the Myrmidon', realm: 'Summer', effect: 'Grants weapon master, shield, cleaving blow, mortal blow, strikedown and thrown skills for a season.', magnitude: 40, source: 'imperial' },
  { name: 'Hammers of the Brilliant Shore', realm: 'Summer', effect: 'Repairs the bastion of a target fortification over the coming season.', magnitude: 60, source: 'imperial' },
  { name: 'Stalwart Stand on Solid Ground', realm: 'Summer', effect: 'Prevents the bastion of a target fortification from being destroyed unless it is reduced to 0 strength.', magnitude: 60, source: 'imperial' },
  { name: 'Thundering Roar of the Lion-bound Horn', realm: 'Summer', effect: 'Allows one use of an area-effect repel call.', magnitude: 60, source: 'imperial' },
  { name: 'Golden Ramparts', realm: 'Summer', effect: 'Summons servants of Meraud to defend a fortification.', magnitude: 80, source: 'imperial' },
  { name: 'Frozen Citadel of Cathan Canae', realm: 'Summer', effect: 'Conjures a magical fortress and defenders into a region with the hills quality.', magnitude: 120, source: 'imperial' },
  { name: 'Knights of Glory', realm: 'Summer', effect: 'Summons supernatural troops to fight alongside an enchanted campaign army.', magnitude: 120, source: 'imperial' },
  { name: 'Anvil of Estavus', realm: 'Autumn', effect: 'Mends an item that has been affected by SHATTER.', magnitude: 2, source: 'imperial' },
  { name: 'Arcane Mark', realm: 'Autumn', effect: 'Places an enduring magical mark on a target that marks them as a member of a Conclave Order.', magnitude: 2, source: 'imperial' },
  { name: 'Call Winged Messenger', realm: 'Autumn', effect: 'Send a specially prepared message to a named individual in a known location.', magnitude: 2, source: 'imperial' },
  { name: 'Mark of Fellowship', realm: 'Autumn', effect: 'Places an enduring magical mark on a target indicating their membership of an Imperial Sodality.', magnitude: 2, source: 'imperial' },
  { name: 'Mark of Ownership', realm: 'Autumn', effect: 'Marks a bonded item as owned.', magnitude: 2, source: 'imperial' },
  { name: 'Streams of Silver', realm: 'Autumn', effect: 'Adds 24 rings to a business\' production during the next season.', magnitude: 2, source: 'imperial' },
  { name: 'Blade Bites Back', realm: 'Autumn', effect: 'Grants an extra use to a Biting Blade that has been used that day.', magnitude: 3, source: 'imperial' },
  { name: 'Before the Throne of Estavus', realm: 'Autumn', effect: 'Swaps raw materials for Autumn vis', magnitude: 4, source: 'imperial' },
  { name: 'Conspirator\'s Cloak', realm: 'Autumn', effect: 'Grants an aura of confidence to a character.', magnitude: 4, source: 'imperial' },
  { name: 'Ephisis\' Scale', realm: 'Autumn', effect: 'Allows trade with the eternal Ephisis.', magnitude: 4, source: 'imperial' },
  { name: 'Shared Mastery of the Magician\'s Guild', realm: 'Autumn', effect: 'Grants knowledge of a spell known by a member of the coven.', magnitude: 4, source: 'imperial' },
  { name: 'Aid Once More', realm: 'Autumn', effect: 'Enchants a magician with the ability to use a Volhov\'s Robe an additional time each day.', magnitude: 6, source: 'imperial' },
  { name: 'Bulging at the Seams', realm: 'Autumn', effect: 'Adds 6 additional ingots to the production of a mine over the next season.', magnitude: 6, source: 'imperial' },
  { name: 'Ties that Bind', realm: 'Autumn', effect: 'Divines the bonds, band affiliations, and nationality of a character.', magnitude: 6, source: 'imperial' },
  { name: 'Mantle of the Golden Orator', realm: 'Autumn', effect: 'Enhances a congregation for the next season granting additional 3 liao and 6 votes in the synod.', magnitude: 7, source: 'imperial' },
  { name: 'Chamber of Pallas', realm: 'Autumn', effect: 'Creates roleplay aura of conviviality in location.', magnitude: 8, source: 'imperial' },
  { name: 'Hand of the Maker', realm: 'Autumn', effect: 'Divines information about the crafter of an item.', magnitude: 8, source: 'imperial' },
  { name: 'Scrivener\'s Bloodmark', realm: 'Autumn', effect: 'Creates a delayed curse between contractees.', magnitude: 8, source: 'imperial' },
  { name: 'Stance of the Constricting Scourge', realm: 'Autumn', effect: 'Grants the ability to call ENTANGLE with weapon or implement once each day.', magnitude: 8, source: 'imperial' },
  { name: 'Twist of Moebius', realm: 'Autumn', effect: 'Allows a coven to perform an extra ritual tomorrow at the cost of a ritual today.', magnitude: 8, source: 'imperial' },
  { name: 'Winds of Fortune', realm: 'Autumn', effect: 'Adds 120 rings to the resources produced by a fleet provided it takes a trading action.', magnitude: 8, source: 'imperial' },
  { name: 'Ambassadorial Gatekeeper', realm: 'Autumn', effect: 'Lets someone accompany a ritualist to the Hall of Worlds.', magnitude: 10, source: 'imperial' },
  { name: 'Lure of Distant Shores', realm: 'Autumn', effect: 'Grants five extra ranks to a fleet taking a trading action.', magnitude: 10, source: 'imperial' },
  { name: 'Rivers of Gold', realm: 'Autumn', effect: 'Adds 180 rings to the production of a business in the next season.', magnitude: 12, source: 'imperial' },
  { name: 'Barked Command of the Iron Serjant', realm: 'Autumn', effect: 'Three targets gain partial weapon mastery for a day.', magnitude: 14, source: 'imperial' },
  { name: 'Brazen Claws of the Lictor', realm: 'Autumn', effect: 'Grants a magician the ability to repeatedly entangle their opponents.', magnitude: 14, source: 'imperial' },
  { name: 'Timeless Hammer Rhythm', realm: 'Autumn', effect: 'Grants an artisan the ability to craft an item overnight.', magnitude: 14, source: 'imperial' },
  { name: 'Gathering the Harvest', realm: 'Autumn', effect: 'Replaces Strong Ox, Golden Sun and adds 400 rings to the production of a farm.', magnitude: 15, source: 'imperial' },
  { name: 'Gift of the Wily Broker', realm: 'Autumn', effect: 'Adds 1 liao, eight resources, and 1 of each type of herb to production of a business over the next season.', magnitude: 15, source: 'imperial' },
  { name: 'Sum of the Parts', realm: 'Autumn', effect: 'Three participants contribute strength to a champion', magnitude: 15, source: 'imperial' },
  { name: 'Circle of Gold', realm: 'Autumn', effect: 'Five characters can use Stay With Me on each other once a day for a season.', magnitude: 16, source: 'imperial' },
  { name: 'Smooth Hands Shape The World', realm: 'Autumn', effect: 'Grants ability to cast mend faster for a season.', magnitude: 19, source: 'imperial' },
  { name: 'Balanced Scales of Lann', realm: 'Autumn', effect: 'Grants one rank of Autumn lore for a season, and allows the trade of metal for magical power.', magnitude: 20, source: 'imperial' },
  { name: 'Shadow of the Bronze Colossus', realm: 'Autumn', effect: 'Grants four ranks of endurance to heavy armour wearer for a season.', magnitude: 21, source: 'imperial' },
  { name: 'Like Water Through Your Fingers', realm: 'Autumn', effect: 'Curses a character to lose three-quarters of all resource production for a year.', magnitude: 30, source: 'imperial' },
  { name: 'Hand of the Dhomiro', realm: 'Autumn', effect: 'Protects the personal resources in a territory from raiders', magnitude: 40, source: 'imperial' },
  { name: 'Inescapable Chains of Bitter Glass', realm: 'Autumn', effect: 'Allows one use of MASS ENTANGLE.', magnitude: 40, source: 'imperial' },
  { name: 'Bound by Common Cause', realm: 'Autumn', effect: 'Enhances a campaign army to provide improved logistics and support', magnitude: 80, source: 'imperial' },
  { name: 'Find the Best Path', realm: 'Autumn', effect: 'Enchants an army letting them move through an additional territory.', magnitude: 80, source: 'imperial' },
  { name: 'Brotherhood of Tian', realm: 'Autumn', effect: 'Enchants an army providing additional natural resupply.', magnitude: 120, source: 'imperial' },
  { name: 'Fire on the Water', realm: 'Autumn', effect: 'Enchants an army to have the Seawatch quality', magnitude: 120, source: 'imperial' },
  { name: 'An Echo of Life Remains', realm: 'Winter', effect: 'Identifies a corpse.', magnitude: 2, source: 'imperial' },
  { name: 'Black Iron Blade', realm: 'Winter', effect: 'Cuts all bonds on target.', magnitude: 2, source: 'imperial' },
  { name: 'Fallow Fields and Dried Meat', realm: 'Winter', effect: 'Add 18 rings to the production of a farm over winter.', magnitude: 2, source: 'imperial' },
  { name: 'Hunger of the Draughir', realm: 'Winter', effect: 'Grants one rank of fortitude and the ability to eat anything for a season.', magnitude: 2, source: 'imperial' },
  { name: 'Mark the Flesh Incorruptible', realm: 'Winter', effect: 'Preserves a corpse.', magnitude: 4, source: 'imperial' },
  { name: 'Tribute to the Thrice-Cursed Court', realm: 'Winter', effect: 'Trades crafted items for Winter vis.', magnitude: 4, source: 'imperial' },
  { name: 'Words of Ending', realm: 'Winter', effect: 'Destroys the magic of a crafted item.', magnitude: 4, source: 'imperial' },
  { name: 'Surcease of Sorrow', realm: 'Winter', effect: 'Kills a willing target and turns them into a pile of dust and ash.', magnitude: 6, source: 'imperial' },
  { name: 'Wisdom of the Balanced Blade', realm: 'Winter', effect: 'Analyses a curse and provides information on how to break it.', magnitude: 6, source: 'imperial' },
  { name: 'Withering Touch of Frost', realm: 'Winter', effect: 'Curses a character to lose a quarter of farm, forest and herb garden production for a year.', magnitude: 6, source: 'imperial' },
  { name: 'Crumbling Flesh and Withering Limbs', realm: 'Winter', effect: 'Grants ability to call CLEAVE with a rod twice each day for a season.', magnitude: 8, source: 'imperial' },
  { name: 'Pakaanan\'s Iron Shutters', realm: 'Winter', effect: 'Seals a portal for ten minutes.', magnitude: 8, source: 'imperial' },
  { name: 'Ruthless Vigilance, Healthy Crop', realm: 'Winter', effect: 'Enhances a herb garden, increasing production of each herb by two over next season.', magnitude: 8, source: 'imperial' },
  { name: 'Traitor\'s Fate', realm: 'Winter', effect: 'Agree to let someone trigger a dangerous curse if they betray you.', magnitude: 8, source: 'imperial' },
  { name: 'Judgement of the Magisters', realm: 'Winter', effect: 'Grants a priest the power to strengthen the exorcism ceremony with extra liao for a season.', magnitude: 9, source: 'imperial' },
  { name: 'Freezing Brand of Irremais', realm: 'Winter', effect: 'Brands and influences a target.', magnitude: 10, source: 'imperial' },
  { name: 'Petrifying Command of the Tyrant', realm: 'Winter', effect: 'Grants a magician the ability to cast Paralysis twice per day as if they knew it without spending mana', magnitude: 10, source: 'imperial' },
  { name: 'Ravenous Tongue of Entropy', realm: 'Winter', effect: 'Grants the ability to cast shatter, weakness, and paralysis as if you know them.', magnitude: 10, source: 'imperial' },
  { name: 'Fight Tooth and Nail', realm: 'Winter', effect: 'Grants two uses of unstoppable each day for a season.', magnitude: 12, source: 'imperial' },
  { name: 'Unending Onslaught', realm: 'Winter', effect: 'Grants two uses of relentless each day', magnitude: 12, source: 'imperial' },
  { name: 'Wolves of the Hungry Sea', realm: 'Winter', effect: 'Grants five additional ranks to a fleet taking a guarding action.', magnitude: 12, source: 'imperial' },
  { name: 'Pallid Flesh of the Dead King', realm: 'Winter', effect: 'Grants three ranks of endurance for a season at the cost of persistent venom.', magnitude: 13, source: 'imperial' },
  { name: 'Unyielding Constitution', realm: 'Winter', effect: 'Grants the ability to endure the effects of traumatic wounds for a season.', magnitude: 13, source: 'imperial' },
  { name: 'Bitter Mantle of the Leaden Crown', realm: 'Winter', effect: 'Curses a character with moments of self-doubt and an inability to recover hero points or personal mana naturally', magnitude: 14, source: 'imperial' },
  { name: 'Hold Back Frozen Hunger', realm: 'Winter', effect: 'Wards an area against the dead.', magnitude: 14, source: 'imperial' },
  { name: 'Hungry Grasp of Despair', realm: 'Winter', effect: 'Grants a magician the ability to repeatedly weaken their foes.', magnitude: 14, source: 'imperial' },
  { name: 'Sorin\'s Chastising Touch', realm: 'Winter', effect: 'Grants a magician the ability to repeatedly call CLEAVE with a rod.', magnitude: 14, source: 'imperial' },
  { name: 'There Is No Welcome Here', realm: 'Winter', effect: 'Ward an area against eternals and heralds.', magnitude: 14, source: 'imperial' },
  { name: 'Ward of the Black Waste', realm: 'Winter', effect: 'Wards an area against vallornspawn.', magnitude: 14, source: 'imperial' },
  { name: 'Clarion Call of Ivory and Dust', realm: 'Winter', effect: 'Conjures members of the Grim Legion that grant 5 extra ranks to a military unit taking a campaigning action.', magnitude: 20, source: 'imperial' },
  { name: 'Coil of the Black Leech', realm: 'Winter', effect: 'Grants a target the ability to heal themselves when they cast weakness.', magnitude: 20, source: 'imperial' },
  { name: 'Devastating Scythe of Anguish and Loss', realm: 'Winter', effect: 'Grants ability to IMPALE foes with a staff.', magnitude: 20, source: 'imperial' },
  { name: 'Dreadful Ending', realm: 'Winter', effect: 'Destroys a Druj miasma pillar', magnitude: 20, source: 'imperial' },
  { name: 'Gnawing, Endless Hunger', realm: 'Winter', effect: 'Curses a character with endless hunger and inability to benefit from potions.', magnitude: 20, source: 'imperial' },
  { name: 'Last Breath Echoes', realm: 'Winter', effect: 'Restores a terminal character for a short period before they die.', magnitude: 20, source: 'imperial' },
  { name: 'Sorin\'s Rite of Agony', realm: 'Winter', effect: 'Grants 1 rank of winter lore for a season, and additional prowess with curses, at the cost of an unhealing wound', magnitude: 20, source: 'imperial' },
  { name: 'Retreat to the White Caves', realm: 'Winter', effect: 'Wards an area against heralds for a season', magnitude: 23, source: 'imperial' },
  { name: 'Wardens of the Black Waste', realm: 'Winter', effect: 'Wards an area against vallorn creatures for a season', magnitude: 23, source: 'imperial' },
  { name: 'Dreamscape of the Endless Hunt', realm: 'Winter', effect: 'Curses a character with nightmares and removes ability to recover hero points or mana naturally.', magnitude: 30, source: 'imperial' },
  { name: 'Icy Maw Devours the Spark of Essence', realm: 'Winter', effect: 'Curse a territory disrupting magicians, magical creatures, and mana sites.', magnitude: 30, source: 'imperial' },
  { name: 'Naeve\'s Twisting Blight', realm: 'Winter', effect: 'Blights all farms in a territory with a withering curse.', magnitude: 30, source: 'imperial' },
  { name: 'Whispers through the Black Gate', realm: 'Winter', effect: 'Summons a dead spirit to answer questions.', magnitude: 30, source: 'imperial' },
  { name: 'Flower is Withered on the Stalk', realm: 'Winter', effect: 'Withers plant life in a region, damaging some magically created structures', magnitude: 36, source: 'imperial' },
  { name: 'Inevitable Collapse into Ruin', realm: 'Winter', effect: 'Damages a battlefield fortification.', magnitude: 40, source: 'imperial' },
  { name: 'Curse of Decrepitude', realm: 'Winter', effect: 'Curses a target with persistent WEAKNESS for a year.', magnitude: 50, source: 'imperial' },
  { name: 'Howling Despite of the Yawning Maw', realm: 'Winter', effect: 'Allows one use of MASS WEAKNESS.', magnitude: 50, source: 'imperial' },
  { name: 'Winter\'s Ghosts', realm: 'Winter', effect: 'Curses a territory with misery, harming all personal resources save congregations.', magnitude: 50, source: 'imperial' },
  { name: 'Grave\'s Treacherous Edge', realm: 'Winter', effect: 'Allows one use of MASS VENOM.', magnitude: 60, source: 'imperial' },
  { name: 'Why Sulemaine Walked Away From The Baker', realm: 'Winter', effect: 'Enchants a campaign army to allow it to endure venomous attacks.', magnitude: 80, source: 'imperial' },
  { name: 'Basalt Citadel', realm: 'Winter', effect: 'Conjures a temporary supernatural fortification to defend a ruined region.', magnitude: 100, source: 'imperial' },
  { name: 'Quickening Cold Meat', realm: 'Winter', effect: 'Summons Winter spirits to create murderous animated corpses that fight alongside an enchanted army for a year.', magnitude: 120, source: 'imperial' },
  { name: 'Wind of Mundane Silence', realm: 'Winter', effect: 'Destroys a regio permanently.', magnitude: 150, source: 'imperial' },
  { name: 'Wither the Seed', realm: 'Winter', effect: 'Drastically reduces the fertility of an area for a generation.', magnitude: 150, source: 'imperial' },
  { name: 'Ascetic Star of Atun', realm: 'Day', effect: 'Removes venom.', magnitude: 2, source: 'imperial' },
  { name: 'Hakima\'s Glass', realm: 'Day', effect: 'Divine details of bonded item or person.', magnitude: 2, source: 'imperial' },
  { name: 'Piercing Light of Revelation', realm: 'Day', effect: 'Removes obscuring effects and opens night pouches.', magnitude: 2, source: 'imperial' },
  { name: 'Horizon\'s Razor Edge', realm: 'Day', effect: 'Grants ability to call CLEAVE with a weapon once each day.', magnitude: 3, source: 'imperial' },
  { name: 'Celestial Library', realm: 'Day', effect: 'Delivers book or scroll to Eternal for possible destruction.', magnitude: 4, source: 'imperial' },
  { name: 'Distillation of Diverse Parts', realm: 'Day', effect: 'Recover herbs from potion.', magnitude: 4, source: 'imperial' },
  { name: 'Gift of Knowledge', realm: 'Day', effect: 'Delivers book or scroll to Phaleron in return for Day mana.', magnitude: 4, source: 'imperial' },
  { name: 'Gralka\'s Gift to the Lost Seeker', realm: 'Day', effect: 'Divines the current location of the caster.', magnitude: 4, source: 'imperial' },
  { name: 'Illuminate the Higher Mind', realm: 'Day', effect: 'Shares knowledge of one spell with another magician for a season.', magnitude: 4, source: 'imperial' },
  { name: 'Bright Lantern of Ophis', realm: 'Day', effect: 'Analyses a magical effect.', magnitude: 6, source: 'imperial' },
  { name: 'Clear Lens of the Eternal River', realm: 'Day', effect: 'Divines the historical significance of the immediate area.', magnitude: 8, source: 'imperial' },
  { name: 'Crystal Clarity of the Rational Soul', realm: 'Day', effect: 'Grants an aura of calm and serenity to a character for a day.', magnitude: 8, source: 'imperial' },
  { name: 'Revelation of the Jewel\'s Sparkling Heart', realm: 'Day', effect: 'Adds 8 additional ingots to the production of a mine over the next season.', magnitude: 8, source: 'imperial' },
  { name: 'Sign of Aesh', realm: 'Day', effect: 'Reduces the magnitude of the next ritual you cast by yourself by 2.', magnitude: 8, source: 'imperial' },
  { name: 'Skein of Years', realm: 'Day', effect: 'When the ritual is complete, the ritualists receive a vision during which key events in the history of the target item are revealed.', magnitude: 8, source: 'imperial' },
  { name: 'Solace of Chimes', realm: 'Day', effect: 'Creates a calm roleplay aura.', magnitude: 8, source: 'imperial' },
  { name: 'Chimes of Annulment', realm: 'Day', effect: 'Suppresses the effect of a Druj miasma focus for one minute.', magnitude: 10, source: 'imperial' },
  { name: 'Eyes of the Soul\'s Past', realm: 'Day', effect: 'Reveals information about a past-life vision', magnitude: 10, source: 'imperial' },
  { name: 'Sharp Eyes of the Corsair', realm: 'Day', effect: 'Grants two extra ranks to a military unit taking a scouting action.', magnitude: 10, source: 'imperial' },
  { name: 'Sular\'s Promise', realm: 'Day', effect: 'Grants six extra ranks to a fleet taking a trading action.', magnitude: 12, source: 'imperial' },
  { name: 'Eye of the High Places', realm: 'Day', effect: 'Divines large-scale effects on a territory.', magnitude: 14, source: 'imperial' },
  { name: 'Eyes of the Sun and Moon', realm: 'Day', effect: 'Divines details of campaign forces in a territory.', magnitude: 14, source: 'imperial' },
  { name: 'Ascendance of the Highest Mind', realm: 'Day', effect: 'Target learns up to three spells known by the coven for a season.', magnitude: 15, source: 'imperial' },
  { name: 'Alignment of Mind and Blade', realm: 'Day', effect: 'Grant the use of one impale each day for a season when wielding one-handed weapon or one-handed spear.', magnitude: 18, source: 'imperial' },
  { name: 'Swim Leviathan\'s Depth', realm: 'Day', effect: 'Asks a specific question of the eternal Leviathan to divine a past cause or event that has led to a present-day state of affairs or consequence.', magnitude: 18, source: 'imperial' },
  { name: 'Kimus\' Glaring Eye', realm: 'Day', effect: 'Grants the ability to use repel on two targets at once.', magnitude: 19, source: 'imperial' },
  { name: 'Standing at the Threshold', realm: 'Day', effect: 'Allows a coven to perform an extra ritual each day for a season.', magnitude: 19, source: 'imperial' },
  { name: 'Carve the Crystal Guardian', realm: 'Day', effect: 'Transforms a mana site into a powerful military unit for a season.', magnitude: 20, source: 'imperial' },
  { name: 'Combing the Beach', realm: 'Day', effect: 'Provides guidance from the eternal Roshanwe.', magnitude: 20, source: 'imperial' },
  { name: 'Crystalline Focus of Aesh', realm: 'Day', effect: 'Grants one rank of Day lore for a season and additional prowess when performing divination rituals.', magnitude: 20, source: 'imperial' },
  { name: 'Garden of Teth-Anon', realm: 'Day', effect: 'Grants members of a coven +1 rank when performing a ritual they have not mastered.', magnitude: 23, source: 'imperial' },
  { name: 'Transcendent Mastery', realm: 'Day', effect: 'Target gains all spell knowledge.', magnitude: 26, source: 'imperial' },
  { name: 'All the World in a Grain of Sand', realm: 'Day', effect: 'Curses a character with madness that prevents ritual casting.', magnitude: 30, source: 'imperial' },
  { name: 'Netweaver\'s Eye', realm: 'Day', effect: 'Divines whether the target has performed specific magic in the last three days', magnitude: 30, source: 'imperial' },
  { name: 'Clarity of the Master Strategist', realm: 'Day', effect: 'Enchants an army granting additional strength towards determining victory in a campaign.', magnitude: 80, source: 'imperial' },
  { name: 'Revelatory Light of the Empyrean Spheres', realm: 'Day', effect: 'Grants one use of area-of-effect paralysis.', magnitude: 150, source: 'imperial' },
  { name: 'Bright Eyes Gleam in the Depths', realm: 'Day', effect: 'Enchants the Empire with power drawn from the Day realm.', magnitude: 210, source: 'imperial' },
  { name: 'Freedom of the Soul', realm: 'Night', effect: 'Creates an aura on a character that greatly heightens emotions.', magnitude: 2, source: 'imperial' },
  { name: 'Missive for Sadogua', realm: 'Night', effect: 'Sends a message to the eternal Sadogua.', magnitude: 2, source: 'imperial' },
  { name: 'Cast Off The Chain of Memory', realm: 'Night', effect: 'Excises memory via voluntary amnesia.', magnitude: 4, source: 'imperial' },
  { name: 'Incantation\'s Mystic Mask', realm: 'Night', effect: 'Obfuscate the next ritual cast by this coven.', magnitude: 4, source: 'imperial' },
  { name: 'Masque of the Blinded Weaver', realm: 'Night', effect: 'Obscures bonds between items or characters.', magnitude: 4, source: 'imperial' },
  { name: 'Secrets for the Shadow Courier', realm: 'Night', effect: 'Creates a year duration Ornate Pouch for a character.', magnitude: 4, source: 'imperial' },
  { name: 'Secrets of Skilful Artifice', realm: 'Night', effect: 'Grants ability to craft a single item.', magnitude: 4, source: 'imperial' },
  { name: 'Secrets of the Empty Heart', realm: 'Night', effect: 'Gives the ability to die rather than reveal a secret.', magnitude: 4, source: 'imperial' },
  { name: 'Signs and Portents', realm: 'Night', effect: 'Provides a coven with visions of important events.', magnitude: 4, source: 'imperial' },
  { name: 'Thief\'s Arcane Gambit', realm: 'Night', effect: 'Steals an enchantment.', magnitude: 4, source: 'imperial' },
  { name: 'Cuckoo\'s Egg', realm: 'Night', effect: 'Allows a willing target to pass through the Sentinel Gate as if they were an Imperial citizen, once within ten minutes.', magnitude: 6, source: 'imperial' },
  { name: 'Eight-spoked Wheel', realm: 'Night', effect: 'Transforms three ingots or measures of materials along an alchemical path.', magnitude: 6, source: 'imperial' },
  { name: 'Riddle Hides the Reward', realm: 'Night', effect: 'Curses an item or character making it difficult to sever magical bonds connected to them.', magnitude: 6, source: 'imperial' },
  { name: 'Shroud of Mist and Shadow', realm: 'Night', effect: 'Grants a concealing bonus to a military unit that takes a raiding action.', magnitude: 6, source: 'imperial' },
  { name: 'Verdant Bounty of the Twilight Bayou', realm: 'Night', effect: 'Adds five measures to the production of a forest over the next season.', magnitude: 6, source: 'imperial' },
  { name: 'Embrace the Living Flame', realm: 'Night', effect: 'Grants an additional hero point for a season.', magnitude: 7, source: 'imperial' },
  { name: 'Chamber of Delights', realm: 'Night', effect: 'Creates an aura in an area that encourages relaxation.', magnitude: 8, source: 'imperial' },
  { name: 'Drawing the Penumbral Veil', realm: 'Night', effect: 'Shrouds a territory from scrying.', magnitude: 8, source: 'imperial' },
  { name: 'Retrograde Wheel', realm: 'Night', effect: 'Transforms three ingots or measures of materials the other way along an alchemical path.', magnitude: 8, source: 'imperial' },
  { name: 'Ride the Noble Steed', realm: 'Night', effect: 'Grants two people a vivid dream of riding a horse next time they sleep.', magnitude: 8, source: 'imperial' },
  { name: 'Shadowed Glass of Sung', realm: 'Night', effect: 'Divines mysterious, secretive, or enigmatic information about the immediate area.', magnitude: 8, source: 'imperial' },
  { name: 'Silver Tongue of Virtue', realm: 'Night', effect: 'Enhances a congregation for the next season granting additional 3 liao and 6 votes in the synod.', magnitude: 8, source: 'imperial' },
  { name: 'Twilight Masquerade', realm: 'Night', effect: 'Creates a magical disguise that changes lineage.', magnitude: 8, source: 'imperial' },
  { name: 'Whispering Shadow Courtiers', realm: 'Night', effect: 'Enables limited communication with the Whisper Gallery.', magnitude: 8, source: 'imperial' },
  { name: 'Gardener\'s Wheel', realm: 'Night', effect: 'Transforms up to five drams of the same herb along a specific path.', magnitude: 10, source: 'imperial' },
  { name: 'Muffled Oar', realm: 'Night', effect: 'Grants five extra ranks to a fleet taking a scouting action.', magnitude: 10, source: 'imperial' },
  { name: 'Secrets of the Soul\'s Desire', realm: 'Night', effect: 'Reveals information about a past-life vision', magnitude: 10, source: 'imperial' },
  { name: 'Tithe of Bats', realm: 'Night', effect: 'Exchanges measures of iridescent gloaming and dragonbone for Night vis.', magnitude: 10, source: 'imperial' },
  { name: 'Unfettered Anarchy', realm: 'Night', effect: 'Curses a character with uncontrollable emotions.', magnitude: 10, source: 'imperial' },
  { name: 'Infant Starts with a Blank Slate', realm: 'Night', effect: 'Causes a willing character to forget all their mastered rituals.', magnitude: 12, source: 'imperial' },
  { name: 'Dreams in the Witch House', realm: 'Night', effect: 'Provides divinatory visions about important events taking place in a territory.', magnitude: 14, source: 'imperial' },
  { name: 'Clear Counsel of the Everflowing River', realm: 'Night', effect: 'Prompts Sung to deliver response to a question, which must have been asked on a previous day of the same event', magnitude: 20, source: 'imperial' },
  { name: 'Conclave of Trees and Shadow', realm: 'Night', effect: 'Transforms a forest into a powerful military unit for a season.', magnitude: 20, source: 'imperial' },
  { name: 'Rule of Risk and Reward', realm: 'Night', effect: 'Grants 2 additional ranks of lore for performing arcane projections', magnitude: 20, source: 'imperial' },
  { name: 'Sift the Dreamscape\'s Sands', realm: 'Night', effect: 'Grants 1 additional rank of any lore overnight, which can be changed each morning for a season.', magnitude: 20, source: 'imperial' },
  { name: 'Vale of Shadows', realm: 'Night', effect: 'Conceals a resource from invaders.', magnitude: 20, source: 'imperial' },
  { name: 'Still Waters, Running Deep', realm: 'Night', effect: 'Grants 3 additional hero points for a season.', magnitude: 29, source: 'imperial' },
  { name: 'Align the Celestial Net', realm: 'Night', effect: 'Realign regio for the next ritual cast at it.', magnitude: 30, source: 'imperial' },
  { name: 'Emulsion of Lye and Lightning', realm: 'Night', effect: 'Transforms ilium, tempest jade, and beggar\'s lye into a powerful cleaning substance.', magnitude: 60, source: 'imperial' },
  { name: 'Transmogrification of the Soul\'s Echo', realm: 'Night', effect: 'Permanently change the personality of a willing character, and remove some curses.', magnitude: 60, source: 'imperial' },
  { name: 'Amalgamation of Silver and Gold', realm: 'Night', effect: 'Transforms ilium, weltsilver, and ambergelt into a powerful curative substance.', magnitude: 70, source: 'imperial' },
  { name: 'Dripping Echoes of the Fen', realm: 'Night', effect: 'Conjures magical mists to defend a region with the marsh quality.', magnitude: 80, source: 'imperial' },
  { name: 'Distil the Serpent\'s Stone', realm: 'Night', effect: 'Creates a unique consumable alchemical item.', magnitude: 100, source: 'imperial' },
  { name: 'Wondrous Forests of the Night', realm: 'Night', effect: 'Enchants the Empire with power drawn from the Night realm.', magnitude: 210, source: 'imperial' },

  // ── Urizen Lore
  { name: 'Good Green Oak', realm: 'Spring', effect: 'Grants one rank of endurance for a season', magnitude: 6, source: 'urizen' },
  { name: 'Wellspring of the High Peak', realm: 'Spring', effect: 'Trades measures of ambergelt with an eternal to produce Spring vis', magnitude: 6, source: 'urizen' },
  { name: 'A Goblet of Stars', realm: 'Spring', effect: 'Enchants a physick with the ability to use any healing herb as if it were true vervain', magnitude: 8, source: 'urizen' },
  { name: 'Blood-dimmed Tide', realm: 'Spring', effect: 'With Siakha\'s aid, adds five ranks to a military unit that takes a raiding action during the next season.', magnitude: 10, source: 'urizen' },
  { name: 'Fountain\'s Bounty', realm: 'Spring', effect: 'Enchants a mana site to produce additional herbs, forest materials, and money', magnitude: 12, source: 'urizen' },
  { name: 'Woven Strands of Life', realm: 'Spring', effect: 'Transforms a mana site into a herb garden for a season that receives additional production', magnitude: 14, source: 'urizen' },
  { name: 'Rhythm of the Tempest', realm: 'Spring', effect: 'With Siakha\'s aid, grants a battle mage the ability to repeatedly repel their foes with a staff', magnitude: 16, source: 'urizen' },
  { name: 'Shark\'s Rampage', realm: 'Spring', effect: 'With Siakha\'s aid, fills the target with bloodthirsty prowess', magnitude: 24, source: 'urizen' },
  { name: 'Aspect of the Mountain', realm: 'Summer', effect: 'Grants a significant increase to the strength of a military unit when taking a guarding action.', magnitude: 20, source: 'urizen' },
  { name: 'Raise the Dragonsworn Cohort', realm: 'Summer', effect: 'Provides a powerful military unit for a season in return for a mine.', magnitude: 20, source: 'urizen' },
  { name: 'Vital Strength of the Earth', realm: 'Summer', effect: 'Grants additional power to uses of the unstoppable and relentless skills while touching earth or stone', magnitude: 28, source: 'urizen' },
  { name: 'Crown of Phoenix Fire', realm: 'Summer', effect: 'Grants two ranks of endurance to a group for a season', magnitude: 32, source: 'urizen' },
  { name: 'Hook of the Hoarfrost Guardian', realm: 'Summer', effect: 'Grants four strikedowns a day with a pole-arm for a season', magnitude: 40, source: 'urizen' },
  { name: 'Might of Vstaive', realm: 'Summer', effect: 'Strengthens a fortification', magnitude: 80, source: 'urizen' },
  { name: 'Swords in the Noonday Sun', realm: 'Summer', effect: 'Enchants a campaign army granting soldiers supernatural prowess', magnitude: 80, source: 'urizen' },
  { name: 'Stone\'s Unyielding Defiance', realm: 'Summer', effect: 'Enchants a fortification increasing the strength of the garrison by 1,500 and repairing the bastion over the coming season.', magnitude: 120, source: 'urizen' },
  { name: 'Ethereal Courier', realm: 'Autumn', effect: 'Send a specially prepared package to a named individual in a known location', magnitude: 10, source: 'urizen' },
  { name: 'Net of Gossamer Chains', realm: 'Autumn', effect: 'Enchants a congregation to provide 3 autumn vis', magnitude: 14, source: 'urizen' },
  { name: 'Quick Study', realm: 'Autumn', effect: 'Enchants a college of magic to speed codification of rituals', magnitude: 42, source: 'urizen' },
  { name: 'Bells of Silver and Brass', realm: 'Autumn', effect: 'Restores the garrison of a target fortification over the coming season', magnitude: 60, source: 'urizen' },
  { name: 'Eyes of the Hills', realm: 'Autumn', effect: 'Enchants a campaign army changing its quality and granting supernatural ability to defend a territory with hills', magnitude: 80, source: 'urizen' },
  { name: 'Treacher\'s Quill', realm: 'Winter', effect: 'Sends a message to the eternal Agramant', magnitude: 2, source: 'urizen' },
  { name: 'Mark of Agramant', realm: 'Winter', effect: 'Places an enduring magical mark on a target that can only be detected with detect magic', magnitude: 4, source: 'urizen' },
  { name: 'Silence of the Bronze Bell', realm: 'Winter', effect: 'Grants a character with the dedicate skill the ability to remove auras with additional potency', magnitude: 12, source: 'urizen' },
  { name: 'Chalice of Callidius', realm: 'Winter', effect: 'Allows a magician to gain extra personal mana when consuming something that restores mana..', magnitude: 14, source: 'urizen' },
  { name: 'The Crimson Feast', realm: 'Winter', effect: 'With Agramant\'s aid, target gains three ranks of endurance for a season.', magnitude: 15, source: 'urizen' },
  { name: 'Unleash the Beasts Within', realm: 'Winter', effect: 'With Agramants aid, grants an additional three ranks to a military unit that takes a campaigning action.', magnitude: 16, source: 'urizen' },
  { name: 'Chastise the Foolish', realm: 'Winter', effect: 'Curses a target making them unable to use religious skills for a year', magnitude: 20, source: 'urizen' },
  { name: 'Thirst of the Devourer', realm: 'Winter', effect: 'With Agramant\'s aid, grants a target the ability to heal themselves when they successfully deliver an IMPALE', magnitude: 24, source: 'urizen' },
  { name: 'Loosen the Shackles', realm: 'Winter', effect: 'Summons the power of Agramant to enchant a campaign army, granting murderous hunger.', magnitude: 120, source: 'urizen' },
  { name: 'Resolution of Falling Stars', realm: 'Day', effect: 'Grants a magician the ability to overcome roleplaying effects by spending personal mana', magnitude: 6, source: 'urizen' },
  { name: 'Peregrine and Ichimos', realm: 'Day', effect: 'Enchants a military unit to grant additional two additional ranks when taking a guarding action.', magnitude: 10, source: 'urizen' },
  { name: 'Blades of Clear Sight', realm: 'Day', effect: 'Enchants a character who has the Weapon master skill to call IMPALE three times per day', magnitude: 14, source: 'urizen' },
  { name: 'Irresistible Stance of Force and Focus', realm: 'Day', effect: 'Enchants a magician to allow them to cast REPEL four times a day', magnitude: 14, source: 'urizen' },
  { name: 'Arete and the Fields of War', realm: 'Day', effect: 'Enchants a warrior with various abilities dependent on weapons and armour', magnitude: 16, source: 'urizen' },
  { name: 'A Light That Moves', realm: 'Day', effect: 'Enchants a congregation for a season so that it provides additional votes and liao at the next summit', magnitude: 18, source: 'urizen' },
  { name: 'A Perfect Moment', realm: 'Day', effect: 'Enchants a character granting them the marksman skill for a season', magnitude: 22, source: 'urizen' },
  { name: 'Guardian Gate', realm: 'Day', effect: 'Enchants a fortification to gather information about a territory and impede spy networks', magnitude: 80, source: 'urizen' },
  { name: 'The Stargazer\'s Astrolabe', realm: 'Night', effect: 'Grants a magician the ability to repeatedly use detect magic', magnitude: 8, source: 'urizen' },
  { name: 'The Certainty of Doubt', realm: 'Night', effect: 'Curses a character so that any congregation they control provides half as much liao and votes for a year', magnitude: 16, source: 'urizen' },
  { name: 'Mirror of Perfection', realm: 'Night', effect: 'Upgrade a mana site with ilium', magnitude: 30, source: 'urizen' },
  { name: 'Flame and the Flood', realm: 'Night', effect: 'Upgrade a forest with ilium', magnitude: 30, source: 'urizen' },
  { name: 'An Echo of Songs', realm: 'Night', effect: 'Upgrade a mine with ilium', magnitude: 30, source: 'urizen' },
];
